### ISSUE TITLE
private trackers

### ISSUE THREAD

**Issue by mer2329** [ngosang/trackerslist#1]
the following domains/ip seem like a closed (as in non public) traker
tricitytorrents.com
trackerfix.com

and 91.218.230.81 is giving an error of "tracker reply has no peers field"

heres a snap
![image](https://cloud.githubusercontent.com/assets/6768243/15096010/d218d408-14aa-11e6-885c-7b843ca44e05.png)

**Comment by ngosang** [comment]
* `tricitytorrents.com` and `trackerfix.com` were added to the blacklist.
* `91.218.230.81` sometimes works correctly. I keep it by now.

**Thank you for reporting.**

**Comment by Hbo63** [comment]
Select custom DNS server for free with Protectstar's DNS Changer app, and make your internet experience more secure!

https://play.google.com/store/apps/details?id=com.protectstar.dnschanger

**Comment by Hbo63** [comment]
Select custom DNS server for free with Protectstar's DNS Changer app, and make your internet experience more secure!

https://play.google.com/store/apps/details?id=com.protectstar.dnschanger
