### ISSUE TITLE
http://tracker1.itzmx.com:8080/announce

### ISSUE THREAD

**Issue by sakurasdream** [ngosang/trackerslist#100]
http://tracker1.itzmx.com:8080/announce
http://tracker2.itzmx.com:6961/announce
http://tracker3.itzmx.com:6961/announce
http://tracker4.itzmx.com:2710/announce
udp://tracker1.itzmx.com:8080/announce
udp://tracker2.itzmx.com:6961/announce
udp://tracker3.itzmx.com:6961/announce
udp://tracker4.itzmx.com:2710/announce

**Comment by ngosang** [comment]
Added only 1 and 4. I'm having problems with the others...
http://tracker1.itzmx.com:8080/announce
http://tracker4.itzmx.com:2710/announce
udp://tracker1.itzmx.com:8080/announce
udp://tracker4.itzmx.com:2710/announce
