### ISSUE TITLE
mgtracker.org tracker domain being flagged as riskware via malwarebytes

### ISSUE THREAD

**Issue by xavier2k6** [ngosang/trackerslist#102]
mgtracker.org tracker domain being lagged as riskware via malwarebytes
multiple ip ranges affected as it's the domain that is being flagged.

**Comment by ngosang** [comment]
Bittorrent trackers can't be used to distribute malware. They only return a list of IP addresses (valid or invalid). The bittorrent client is in charge of validate all data received from that client.
