### ISSUE TITLE
red trackers

### ISSUE THREAD

**Issue by KonoromiHimaries** [ngosang/trackerslist#116]
![2018-09-18-window](https://user-images.githubusercontent.com/5884000/45663037-cd188680-bb04-11e8-8f2d-fd89a715383b.png)
`http://torrenteditor.com`

```
https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt
```

**Comment by f4nff** [comment]
[https://trackerlist.org/](https://trackerlist.org)

**Comment by ngosang** [comment]
@KonoromiHimaries that's because your ISP is blocking the domains. Try with the IP lists.
