### ISSUE TITLE
A request and a question

### ISSUE THREAD

**Issue by 6GVp8WcnM9TPDBrw** [ngosang/trackerslist#119]
Request : Can you remove the fact that blank lines are created between each tracker ?

Question : Do you think the "best" list is better than the "all" list (including if I download torrent with little to no seeders) ?

By the way : Thanks a lot for this repo !

**Comment by pahakalle** [comment]
The blank lines are there to separete tiers and also for universal ease of use https://forum.utorrent.com/topic/48784-trackers-separate-tiers-with-an-empty-line/

**Comment by ngosang** [comment]
@pahakalle is right,
About the second question, in that case is better to use the "all" list.
