### ISSUE TITLE
New tracker

### ISSUE THREAD

**Issue by gitgitgitgit11** [ngosang/trackerslist#12]
Info webpage: http://harry.lu/tracker/
I have seen it exist in my trackers list for a while, I do not know why it not in your list?

Announce URLs:
> http://ipv4.tracker.harry.lu:80/announce
> udp://ipv4.tracker.harry.lu:80/announce
>
> http://ipv6.tracker.harry.lu:80/announce
> udp://ipv6.tracker.harry.lu:80/announce

If you don't have IPv6 (I hope you do), IPv6 tracker will show is offline. But it works for me because I have IPv6. Both endpoints are public. Thank you.

**Comment by ngosang** [comment]
@gitgitgitgit11 added ipv4 trackers. I can't check ipv6 trackers. Sorry.
