### ISSUE TITLE
The tracker contribution[tracker.btsync.gq]

### ISSUE THREAD

**Issue by lirener** [ngosang/trackerslist#122]
http://tracker.btsync.gq:233/announce
udp://tracker.btsync.gq:233/announce
http://tracker.btsync.gq:2710/announce
udp://tracker.btsync.gq:2710/announce
http://tracker.btsync.gq:6969/announce
udp://tracker.btsync.gq:6969/announce

-----------------------------
Work period: not on a regular basis
Main work time: 0 ~ 5 PM in the morning
Survival: may be unknown
The available time: on October 19, 2019
-----------------------------
工作周期：不定期
主要工作时间：凌晨0点~5点
生存可能：未知
可用时长：截止2019年10月19日
-----------------------------
thankQ~

**Comment by ngosang** [comment]
Added some of them. Thank you!
