### ISSUE TITLE
Add tracker

### ISSUE THREAD

**Issue by kompowiec** [ngosang/trackerslist#123]
http://torrent.resonatingmedia.com:6969/announce
udp://tracker.trackerfix.com:85/announce
udp://tracker.pirateparty.gr:6969/announce
http://torrentsmd.me:8080/announce
http://tracker.tfile.co:80/announce
http://tracker.tfile.me:80/announce
udp://p4p.arenabg.com:1337/announce
udp://sd-95.allfon.net:2710/announce
udp://tracker.acg.gg:2710/announce
udp://tracker.bluefrog.pw:2710/announce
udp://tracker.christianbro.pw:6969/announce
udp://tracker.grepler.com:6969/announce
udp://tracker.halfchub.club:6969/announce
udp://tracker.safe.moe:6969/announce
udp://tracker.skyts.net:6969/announce
udp://wambo.club:1337/announce
http://www.torrent-downloads.to:2710/announce

**Comment by gasperko** [comment]
Will just add here instead of opening a new "issue"
udp://104.248.36.186:6969/announce

**Comment by yuangu** [comment]
udp://tracker.huoyaojing.com:4848/announce

**Comment by nash73** [comment]
http://tracker.d3fect.tk:80/announce

**Comment by nash73** [comment]
http://tracker.d3fect.tk:80/announce

**Comment by pahakalle** [comment]
@kompowiec could you remove zer0day.to from the list as the domain is no longer active

**Comment by kompowiec** [comment]
@pahakalle thx, delete

**Comment by ngosang** [comment]
Added some of them. Thank you all!

**Comment by douglasmilanesi** [comment]
ADD 
http://milanesitracker.tekcities.com/announce
