### ISSUE TITLE
My trackers

### ISSUE THREAD

**Issue by fstltna** [ngosang/trackerslist#125]
udp://torrentclub.tech:6969/announce
http://torrentclub.tech:6969/announce
udp://amigacity.xyz:6969/announce
http://amigacity.xyz:6969/announce
udp://newtoncity.org:6969/announce
http://newtoncity.org:6969/announce

**Comment by kompowiec** [comment]
#123

**Comment by ngosang** [comment]
Added some of them. Thank you!
