### ISSUE TITLE
New public tracker url

### ISSUE THREAD

**Issue by Power2All** [ngosang/trackerslist#133]
Hi, not sure where to submit this.
New public bittorrent tracker is online, supporting both TCP and UDP.

https://www.gbitt.info

Announce URL's:
http://tracker.gbitt.info/announce
https://tracker.gbitt.info/announce (optional when you want HTTPS instead of HTTP)
udp://tracker.gbitt.info/announce

**Comment by ngosang** [comment]
@Power2All Thank you, added http and https.
udp is not working, you should specify the port

**Comment by Power2All** [comment]
UDP is just port 80.
Good point, I'll fix that, thanks !

**Comment by ngosang** [comment]
@Power2All Added udp://tracker.gbitt.info:80/announce
I'm pretty sure you won't be able to handle all the traffic...

**Comment by Power2All** [comment]
I've handled high loaded servers before.
I'm paying cheap for 2x 1gbit right now, and I am able to handle more, but I can always load-balance my stuff to VPN servers, using cluster-mode in OpenTracker, so traffic ain't a issue.

**Comment by ngosang** [comment]
@Power2All I wish you good luck! Merry Christmas!

**Comment by Power2All** [comment]
@ngosang Thanks !
Happy xmas yourself too !
