### ISSUE TITLE
Use a CDN for raw files

### ISSUE THREAD

**Issue by regisbsb** [ngosang/trackerslist#138]
Example: https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all_ip.txt

**Comment by pahakalle** [comment]
Why use a CDN?
Does using it bring any benefits?

**Comment by rredford6** [comment]
raw.githubusercontent.com is already using a Fastly CDN

**Comment by regisbsb** [comment]
I thought raw github domain was only for download. If you host a script and load in a html page or a url that will be downloaded every day it would ban you. But if not then cool 😎.

**Comment by ngosang** [comment]
I think this isn't necessary by now. If the number of downloads increases I will thing about it.
