### ISSUE TITLE
Duplicates/Aliases

### ISSUE THREAD

**Issue by Theli93** [ngosang/trackerslist#143]
Aren't these both still the same tracker (a.k.a. aliases)?

udp://tracker.open-internet.nl:6969/announce
udp://tracker.leechers-paradise.org:6969/announce

"leechers-paradise" used to be in the blacklist as a duplicate.

ref: http://open-internet.nl/ & http://tracker.leechers-paradise.org/

Both are resolved to: 188.241.58.209

**Comment by ngosang** [comment]
You are right, I blacklisted `udp://tracker.open-internet.nl:6969/announce` Thank you!
