### ISSUE TITLE
Tracker "Forbidden"

### ISSUE THREAD

**Issue by 9Pigs** [ngosang/trackerslist#152]
http://172.64.164.23:8080/announce  not working message "Forbidden"

![a- 2](https://user-images.githubusercontent.com/6194720/54630908-24f26480-4a38-11e9-91c8-88da70653db8.jpg)
![a- 3](https://user-images.githubusercontent.com/6194720/54630909-258afb00-4a38-11e9-81fc-a642e5ff16c6.jpg)

**Comment by ngosang** [comment]
This could happen for some trackers if you use the "IP lists"
