### ISSUE TITLE
Missing public trackers

### ISSUE THREAD

**Issue by Micdu70** [ngosang/trackerslist#159]
DNS:

```
http://anidex.moe:6969/announce

http://tracker.minglong.org:8080/announce

http://nyaa.tracker.wf:7777/announce
```

IP:

```
http://91.121.145.207:6969/announce

http://85.17.29.160:8080/announce

http://193.70.85.1:7777/announce
```

EDIT: Don't understand about "registered torrents" thing in `blacklist.txt` for 2 of 3.

**Comment by ngosang** [comment]
These trackers are public but only work with registered torrents. For example, `http://nyaa.tracker.wf:7777/announce` tracker only work for torrents uploaded to https://nyaa.si/
All the trackers in the list must work for all torrents, regardless the upload site.

**Comment by Micdu70** [comment]
Oh okay I see...
Could you add "http://anidex.moe:6969/announce" in `blacklist.txt` please?
:-)

**Comment by ngosang** [comment]
Done
