### ISSUE TITLE
OpenBitTorrent public tracker

### ISSUE THREAD

**Issue by Micdu70** [ngosang/trackerslist#160]
DNS:

`udp://tracker.openbittorrent.com:80/announce`

IP:

`udp://185.19.107.254:80/announce`

is missing...

**Comment by ngosang** [comment]
I can see the web page `openbittorrent.com` but I can't connect to `tracker.openbittorrent.com`
Can you?

**Comment by Micdu70** [comment]
On my browser, I get a "connection not allowed" error but on BitTorrent client, it's working:

http://puu.sh/Drps5/4f23a9a01d.png

**Comment by ngosang** [comment]
@Micdu70 fixed, it's now in the list
