### ISSUE TITLE
Change DNS for UDP tracker URL (gbitt.info)

### ISSUE THREAD

**Issue by Power2All** [ngosang/trackerslist#164]
Hi,

Could you change the following:
udp://tracker.gbitt.info:80/announce

I'm changing this to a separate server:
udp://tracker-udp.gbitt.info:80/announce

Thanks.

**Comment by ngosang** [comment]
Changed. Will be updated this night. Thank you!

**Comment by Power2All** [comment]
Thanks too ;)
