### ISSUE TITLE
New tracker

### ISSUE THREAD

**Issue by connorw600** [ngosang/trackerslist#166]
http://tracker.publictorrent.net:80/announce
https://tracker.publictorrent.net:443/announce

**Comment by ngosang** [comment]
Added! Thank you!

**Comment by connorw600** [comment]
Hello,

Just wanted to make sure there was not an issue with the tracker as it's not been added to either the all tracker list or even the blacklist in the past 5/6 updates

**Comment by ngosang** [comment]
@connorw600 is responding `d14:failure reason14:Missing uploade`.

**Comment by connorw600** [comment]
@ngosang Should be resolved now, I've added default values for non-essential variables.

**Comment by ngosang** [comment]
@connorw600 the tracker response is not standard. The announce doesn't return the number of peers, seeds, completed...

**Comment by connorw600** [comment]
@ngosang I've double checked and the response is correct, its not because I was only accepting compact enabled clients? I've updated to accept non-compact clients now.
I've been using my tracker with transmission without any issues for a while

**Comment by ngosang** [comment]
@connorw600 It's listed now.
