### ISSUE TITLE
New HTTP tracker

### ISSUE THREAD

**Issue by Syc0x00** [ngosang/trackerslist#171]
`http://nibba.trade:1337/announce`

Full disclosure it's mine.

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by Syc0x00** [comment]
@ngosang 

`http://nibba.trade:1337/announce` has become `udp://tracker.nibba.trade:1337/announce`

**Comment by ngosang** [comment]
@Syc0x00 changed
