### ISSUE TITLE
Delete Cloudflare IPs from trackers_all_ip.txt

### ISSUE THREAD

**Issue by theel0ja** [ngosang/trackerslist#175]
They won't work as Cloudflare shares IP addresses.

**Comment by ngosang** [comment]
Nice idea. I will use that list => https://www.cloudflare.com/ips/

**Comment by ngosang** [comment]
Done:
Skipping Cloudflare IP: http://tracker1.itzmx.com:8080/announce
Skipping Cloudflare IP: https://tracker.fastdownload.xyz:443/announce
Skipping Cloudflare IP: https://t.quic.ws:443/announce
Skipping Cloudflare IP: http://open.trackerlist.xyz:80/announce
Skipping Cloudflare IP: https://tracker.vectahosting.eu:2053/announce
Skipping Cloudflare IP: https://tracker.gbitt.info:443/announce
Skipping Cloudflare IP: http://tracker.gbitt.info:80/announce
Skipping Cloudflare IP: http://tracker.bt4g.com:2095/announce
Skipping Cloudflare IP: http://torrent.nwps.ws:80/announce
Skipping Cloudflare IP: https://tracker.publictorrent.net:443/announce
Skipping Cloudflare IP: https://tracker.parrotsec.org:443/announce
Skipping Cloudflare IP: http://tracker.publictorrent.net:80/announce

**Comment by lib-xdown** [comment]
http://tracker1.itzmx.com:8080/announce     

This does not work, please delete

**Comment by theel0ja** [comment]
@lib-xdown Not related to this PR.
