### ISSUE TITLE
Delete HTTP trackers that don't support direct access via IP from trackers_all_ip.txt

### ISSUE THREAD

**Issue by theel0ja** [ngosang/trackerslist#178]
For example, `https://104.244.79.229:443/announce`

![](https://user-images.githubusercontent.com/5832930/60692332-2445e700-9ede-11e9-84a8-60e404b95616.png)

**Comment by ngosang** [comment]
I will. Related #175

**Comment by lib-xdown** [comment]
Cloudflare IP: https://tracker.fastdownload.xyz:443/announce
Cloudflare IP: https://t.quic.ws:443/announce
Cloudflare IP: http://open.trackerlist.xyz:80/announce


After testing, it works fine.

**Comment by theel0ja** [comment]
@lib-xdown Direct **IP** access, not with hostname.

**Comment by ngosang** [comment]
Implemented!
