### ISSUE TITLE
Grouped trackers

### ISSUE THREAD

**Issue by theel0ja** [ngosang/trackerslist#180]
Some trackers in https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt are the same, so grouping them like [shown here](https://support.tixati.com/edit%20trackers) should be done.

**Comment by ngosang** [comment]
In the best_trackers list I'm grouping and removing all but one, giving priority to udp.

About grouping... I prefer the current order, from better to worse.
For example, the following tracker share the domain but udp is more reliable.
```
udp://tracker.opentrackr.org:1337/announce
http://tracker.opentrackr.org:1337/announce
```
Other example. These share the top level domain, but they are different servers with different number of seeds/peers each one.
```
http://tracker1.itzmx.com:8080/announce	itzmx.com	104.24.104.127	24	189
http://tracker2.itzmx.com:6961/announce	itzmx.com	176.113.68.66	6	101
http://tracker3.itzmx.com:6961/announce	itzmx.com	176.113.71.19	24	189
http://tracker4.itzmx.com:2710/announce	itzmx.com	194.143.148.21	6	91
```
