### ISSUE TITLE
add https https://opentracker.co:443/announce	

### ISSUE THREAD

**Issue by lib-xdown** [ngosang/trackerslist#181]
https://opentracker.co:443/announce
--

After testing, it works fine

**Comment by lib-xdown** [comment]
add:
https://opentracker.xyz:443/announce

**Comment by lib-xdown** [comment]
delete :
http://tracker1.itzmx.com:8080/announce

This tracker can't get the correct peer at all.

**Comment by ngosang** [comment]
Added https://opentracker.co:443/announce
Thank you!
