### ISSUE TITLE
Can you go from double line breaks to single line breaks in your trackers files?

### ISSUE THREAD

**Issue by styromaniac** [ngosang/trackerslist#183]
ZeroNet seems to prefer single line breaks between trackers.

**Comment by styromaniac** [comment]
I can use online tools to automatically remove them instead. I'll consider this a non-issue. I just don't think double line breaks are necessary.

**Comment by ngosang** [comment]
@styromaniac this is not documented in Bittorrent protocol, but the main implementation uses 2 new lines between trackers.
