### ISSUE TITLE
TRACKER CHECKER

### ISSUE THREAD

**Issue by OR120** [ngosang/trackerslist#188]
http://tr.bangumi.moe:6969/announce
http://t.nyaatracker.com/announce
http://open.acgtracker.com:1096/announce
http://open.nyaatorrents.info:6544/announce
http://t2.popgo.org:7456/annonce
http://share.camoe.cn:8080/announce
http://opentracker.acgnx.se/announce
http://tracker.acgnx.se/announce
http://nyaa.tracker.wf:7777/announce
udp://208.67.16.113:8000/announce
http://208.67.16.113:8000/annonuce
https://tr.bangumi.moe:6969/announce
http://t.acg.rip:6699/announce
udp://tracker.openbittorrent.com:80/announce
udp://tracker.kamigami.org:2710/announce
http://tracker.kamigami.org:2710/announce
http://tracker.kisssub.org:2015/announce
udp://tracker.publicbt.com:80/announce
udp://tracker.prq.to:80/announce
udp://104.238.198.186:8000/announce
http://104.238.198.186:8000/announce
http://94.228.192.98/announce
http://share.dmhy.org/annonuce
http://tracker.btcake.com/announce
udp://bt.sc-ol.com:2710/announce
http://btfile.sdo.com:6961/announce
http://exodus.desync.com:6969/announce
udp://coppersurfer.tk:6969/announce
http://tracker3.torrentino.com/announce
http://tracker2.torrentino.com/announce
udp://open.demonii.com:1337/announce
udp://tracker.ex.ua:80/announce
http://pubt.net:2710/announce
http://tracker.tfile.me/announce
http://bigfoot1942.sektori.org:6969/announce
http://bt.sc-ol.com:2710/announce
http://sukebei.tracker.wf:8888/announce
udp://tracker.coppersurfer.tk:6969/announce
udp://tracker.internetwarriors.net:1337/announce
udp://tracker.leechers-paradise.org:6969/announce
udp://tracker.opentrackr.org:1337/announce
udp://open.stealth.si:80/announce
udp://p4p.arenabg.com:1337/announce
udp://mgtracker.org:6969/announce
udp://tracker.tiny-vps.com:6969/announce
udp://peerfect.org:6969/announce
http://t.nyaatracker.com:80/announce
https://open.kickasstracker.com:443/announce
http://tracker.ktxp.com:6868/announce
http://tracker.ktxp.com:7070/announce
https://t-115.rhcloud.com/only_for_ylbud
https://tr.bangumi.moe:9696/announce
http://tracker.dmhy.org:8000/announce
http://tracker.skyts.net:6969/announce
http://tracker.lintk.me:2710/announce
http://tracker.kuroy.me:5944/announce
http://tracker.skyts.cn:6969/announce
udp://tracker.dmhy.org:8000/announce
udp://tr.bangumi.moe:6969/announce
udp://tracker.skyts.net:6969/announce
udp://tracker.skyts.cc:6969/announce
udp://tracker.ink:6969/announce
udp://asia.tracker.ink:6969/announce
udp://open.tracker.ink:6969/announce
http://anidex.moe:6969/announce
udp://tracker.uw0.xyz:6969/announce
udp://104.238.198.186:8000/annonuce
http://tracker.anirena.com:80/announce
udp://exodus.desync.com:6969/announce
udp://torrent.gresille.org:80/announce
http://torrent.gresille.org/announce
http://tracker.kicks-ass.net/announce
http://retracker.krs-ix.ru/announce
http://tracker.anirena.com/announce
http://open.acgnxtracker.com/announce
https://open.acgnxtracker.com/announce
http://opentracker.acgnx.com:6869/announce
https://opentracker.acgnx.se/announce
udp://tracker.torrent.eu.org:451/announce
udp://tracker.sith.su:80/announce
udp://tracker.mg64.net:6969/announce
udp://tracker.kuroy.me:5944/announce
udp://tracker.grepler.com:6969/announce
udp://tracker.filetracker.pl:8089/announce
udp://tracker.desu.sh:6969/announce
udp://tracker.coppersurfer.tk:6969
udp://mgtracker.org:2710/announce
udp://ipv4.tracker.harry.lu:80/announce
udp://bt.xxx-tracker.com:2710/announce
udp://9.rarbg.com:2790/announce
udp://168.235.67.63:6969/announce
http://tracker2.wasabii.com.tw:6969/announce
http://tracker1.wasabii.com.tw:6969/announce
http://tracker1.itzmx.com:8080/announce
http://tracker.vanitycore.co:6969/announce
http://tracker.tiny-vps.com:6969/announce
http://tracker.mg64.net:6881/announce
http://tracker.grepler.com:6969/announce
http://tracker.filetracker.pl:8089/announce
http://tracker.dler.org:6969/announce
http://tracker.baravik.org:6970/announce
http://torrentsmd.com:8080/announce
http://p4p.arenabg.com:1337/announce
http://mgtracker.org:6969/announce
http://ipv4.tracker.harry.lu/announce
http://ipv4.tracker.harry.lu/annouce
http://inferno.demonoid.ph:3415/announce
http://inferno.demonoid.ooo:3418/announce
http://inferno.demonoid.ooo:3416/announce
http://inferno.demonoid.ooo:3412/announce
http://inferno.demonoid.ooo:3410/announce
http://inferno.demonoid.ooo:3395/announce
udp://explodie.org:6969/announce
http://bt.ttk.artvid.ru:6969/announce
http://bt.artvid.ru:6969/announce
http://87.248.186.252:8080/announce
http://5.79.83.193:2710/announce
http://0123456789nonexistent.com/announce
udp://9.rarbg.me:2770/announce
udp://62.138.0.158:6969/announce
http://inferno.demonoid.ph:3392/announce
http://173.254.204.71:1096/announce
udp://tracker.ilibr.org:6969/announce
http://www.skyts.net:6969/announce
http://tracker4.itzmx.com:2710/announce
http://mgtracker.org:2710/announce
http://tracker3.itzmx.com:6961/announce
http://tracker2.itzmx.com:6961/announce
http://retracker.gorcomnet.ru/announce
udp://tracker.piratepublic.com:1337/announce
http://tracker.xfsub.com:6868/announce
udp://shadowshq.yi.org:6969/announce
udp://eddie4.nl:6969/announce
udp://208.67.16.113:8000/annonuce
udp://shadowshq.eddie4.nl:6969/announce
udp://tracker.leechers-paradise.org:6969
udp://9.rarbg.to:2740/announce
udp://p4p.arenabg.ch:1337/announce
http://bt.cnscg.com:6969/announce
http://bt.cnscg.org:6969/announce
http://secure.pow7.com/announce
http://tracker.tfile.me/a
udp://tracker.ccc.de:80/announce
udp://zer0day.to:1337/announce
http://tracker.baka-sub.cf/announce
http://asnet.pw:2710/announce
udp://tracker.swateam.org.uk:2710/announce
udp://retracker.lanta-net.ru:2710/announce
udp://tracker.doko.moe:6969/announce
http://fxtt.ru/announce
udp://9.rarbg.com:2710/announce
udp://tracker.christianbro.pw:6969/announce
udp://tracker2.christianbro.pw:6969/announce
http://retracker.mgts.by/announce
udp://www.eddie4.nl:6969/announce
udp://91.218.230.81:6969/announce
udp://tracker1.wasabii.com.tw:6969/announce
http://agusiq-torrents.pl:6969/announce
udp://tracker.files.fm:6969/announce
udp://public.popcorn-tracker.org:6969/announce
udp://tracker.zer0day.to:1337/announce
udp://tracker.vanitycore.co:6969/announce
udp://tr.cili001.com:6666/announce
udp://zephir.monocul.us:6969/announce
udp://tracker.bluefrog.pw:2710/announce
http://ipv6.tracker.harry.lu/announce
udp://oscar.reyesleon.xyz:6969/announce
http://tracker.ipv6tracker.org/announce
http://tracker.xku.tv:6969/announce
http://tracker1.xku.tv:6969/announce
udp://9.rarbg.me:2780/announce
udp://9.rarbg.to:2780/announce
http://www.yqzuji.com/announce
udp://tracker.aletorrenty.pl:2710/announce
udp://tracker.bittor.pw:1337/announce
udp://tracker.ex.ua/announce
udp://tracker.openbittorrent.com/announce
udp://bt2.54new.com:8080
udp://tracker.yify-torrents.com/announce
udp://p4p.arenabg.ch:1337
udp://p4p.arenabg.com:1337
udp://bt.rutor.org:2710
udp://opentor.org:2710
http://retracker.local/announce
udp://tracker.openbittorrent.com:80
udp://open.demonii.com:1337
udp://tracker.blackunicorn.xyz:6969
udp://exodus.desync.com:6969
udp://tracker.istole.it:80
udp://tracker.publicbt.com:80
udp://9.rarbg.com:2710
udp://tracker.pomf.se:6969/announce
udp://tracker.torrent.eu.org:80/announce
udp://zer0day.ch:1337/announce
http://acg.rip:6699/announce
http://atrack.pow7.com/announce
http://open.tracker.skyts.net:6969/announce
http://pow7.com/announce
http://t.wahaha.work:6699/announce
http://t2.pow7.com/announce
http://tracker.acg.gg:1578/announce
http://tracker.acg.gg:2710/announce
http://tracker.btchdtv.com/announce
http://tracker.pow7.com/announce
http://wahaha.work:6699/announce
http://www.tlv.cc:7777/announce
udp://11.rarbg.com/announce
udp://141.255.161.22:80/announce
udp://89.234.156.205:80/announce
udp://9.rarbg.me:2710/announce
udp://glotorrents.pw:6969/announce
udp://stealth.si:80/announce
udp://tinsurfer.tk:6969/announce
http://45.33.104.104:6699/announce
udp://91.216.110.47:80/announce
http://133.130.108.127:6969/announce
http://178.175.143.27/announce
http://45.33.104.104:8080/announce
http://68.64.165.106:1578/announce
http://68.64.165.106:2710/announce
udp://indiumsurfer.tk:6969/announce
udp://178.162.222.231:1337/announce
udp://178.33.73.26:2710/announc
udp://191.101.229.236:1337/announce
udp://tracker.pomf.se:80/announce
udp://tracker.sktorrent.net:6969/announce
udp://194.106.216.222:80/announce
udp://195.123.209.40:80/announce
udp://37.59.56.110:1337/announce
udp://46.166.162.81:6969/announce
udp://tracker.yoshi210.com:6969/announce
http://83.234.146.252:6969/announce
http://open.touki.ru/announce
http://tracker.dutchtracking.com/announce
http://tracker.dutchtracking.nl/announce
http://tracker.swateam.org.uk:2710/announce
http://208.67.16.113:8000/announce
http://75.127.14.224:2710/announce
http://85.17.19.180/announce
http://academic-p2p.appspot.com/announce
http://academic-p2p.carlosdelfino.eti.br/announce
http://anisaishuu.de:2710/announce
http://bluraycd.wicp.net:2710/announce
http://bt.henbt.com:2710/announce
http://bt2.54new.com:8080/announce
http://tracker.comicat.org/announce
http://tracker.coppersurfer.tk:6969/announce
http://tracker.csze.com/announce
http://tracker.kisssub.org/announce
http://tracker.opentrackr.org:1337/announce
http://tracker.prq.to/announce
http://tracker.trackerfix.com/announce
udp://107.150.14.110:6969/announce
udp://11.rarbg.me/announce
udp://12.rarbg.me:80/announce
udp://91.216.110.47/announce
udp://bt.rghost.net:80/announce
http://bt2.careland.com.cn:6969/announce
http://coppersurfer.tk:6969/announce
http://cthulhu.regne.net:6969/announce
http://henbt.com:2710/announce
http://i.bandito.org/announce
http://inferno.demonoid.com:3413/announce
http://inferno.demonoid.me:3419/announce
http://leopard.raws.ws:6969/announce
http://sndabt.sdo.com/announce
udp://sugoi.pomf.se:80/announce
http://theheartofchronic.com/announce.php
http://tracker.beeimg.com:6969/announce
http://tracker.bittorrent.am/announce
http://tracker.blazing.de/announce
http://tracker.blucd.org:2710/announce
udp://pornleech.com:2710/announce
udp://tracker.istole.it:80/announce
udp://tracker.pomf.se/announce
http://grifon.info/announce
http://retracker.spark-rostov.ru/announce
http://tracker.devil-torrents.pl/announce
http://torrent.nwps.ws/announce
http://tracker.tfile.co/announce
http://retracker.bashtel.ru/announce
http://retracker.telecom.by/announce
udp://tracker.justseed.it:1337/announce
udp://thetracker.org:80/announce
https://opentracker-milanesi.rhcloud.com/announce
udp://tracker.halfchub.club:6969/announce
http://tracker.yoshi210.com:6969/announce
http://tracker.electro-torrent.pl/announce
http://tracker.torrentyorg.pl/announce
udp://tracker.cyberia.is:6969/announce
udp://tracker.cypherpunks.ru:6969/announce
udp://retracker.nts.su:2710/announce
udp://tracker.dler.org:6969/announce
https://bigfoot1942.sektori.org/announce
http://tracker.tlm-project.org:6969/announce
udp://tracker.tvunderground.org.ru:3218/announce
http://torrentsmd.eu:8080/announce
https://open.kickasstracker.com/announce
http://torrentsmd.me:8080/announce
http://messenger.reyesleon.xyz:443/announce
udp://open.facedatabg.net:6969/announce
udp://inferno.demonoid.pw:3418/announce
udp://z.crazyhd.com:2710/announce
udp://aqua.reyesleon.xyz:2710/announce
https://cernet-tracker.appspot.com/announce
http://tor.reyesleon.xyz:443/announce
https://lgtracker.org/announce
udp://tracker.safe.moe:6969/announce
udp://auratorrent.pl:8089/announce
http://tr.cili001.com:6666/announce
udp://tracker.auratorrent.pl:8089/announce
udp://wambo.club:1337/announce
http://121.14.98.151:9090/announce
http://bt.dmhy.net/annonuce
http://share.dmhy.me/annonuce
udp://tracker.pirateparty.gr:6969/announce
udp://inferno.demonoid.ooo:3389/announce
udp://allesanddro.de:1337/announce
udp://9.rarbg.com:2720/announce
udp://tracker.mg64.net:2710/announce
http://retracker.omsk.ru:2710/announce
http://182.190.4.38:6969/announce
http://182.190.4.52:6969/announce
http://77.106.108.90:2710/announce
http://tracker.anirena.com:6969/announce
http://tracker.frozen-layer.net:6969/announce
http://mkfs.ru/announce
http://tracker.levelup.cn:8080/announce
http://bt.wiiyi.com:6969/announce
udp://bt.wiiyi.com:6969/announce
http://tracker.dmguo.com:2710/announce
http://bt1.the9.com:6969/announce
http://torrent-download.to:5869/announce
http://torrent-download.to:5869/announce.php
http://tracker.internetwarriors.net:1337/announce
http://210.244.71.25:6969/announce
http://91.218.230.81:6969/announce
http://alpha.torrenttracker.nl:443/announce
http://tracker.videodrugproject.com/announce
http://pt.lax.mx/announce
http://tr.cili001.com:8070/announce
http://107.174.238.55/announce
http://123.249.16.65:6961/announce
http://149.202.60.146/announce
http://163.172.140.46:6969/announce
http://163.172.180.68/announce
http://163.172.81.35:1337/announce
http://164.132.200.122/announce
http://185.217.0.76/announce
http://188.165.220.112/announce
http://188.68.224.156:6969/announce
http://195.88.220.21/announce
http://198.251.81.243:8080/announce
http://213.184.225.53/announce
http://45.33.11.224/announce
http://5.79.83.194:6881/announce
http://5.79.83.194:6969/announce
http://51.15.4.13:1337/announce
http://64.78.163.242:2710/announce
http://74.82.52.209:6969/announce
http://82.209.230.66/announce
http://85.28.1.169:2710/announce
http://87.233.192.220/announce
http://tracker.city9x.com:2710/announce
http://tracker.x4w.co:6969/announceUDP
udp://109.236.91.32:6969/announce
udp://123.249.16.65:2710/announce
udp://125.227.35.196:6969/announce
udp://138.68.225.164:6969/announce
udp://151.80.120.112:2710/announce
udp://163.172.140.46:6969/announce
udp://163.172.177.129:80/announce
udp://163.172.180.68:80/announce
udp://163.172.81.35:1337/announce
udp://167.114.97.225:2710/announce
udp://167.160.84.129:6969/announce
udp://173.254.219.72:6969/announce
udp://176.31.253.219:80/announce
udp://178.32.221.207:6969/announce
udp://185.53.178.8:6969/announce
udp://185.82.217.160:1337/announce
udp://188.209.52.105:1337/announce
udp://191.96.249.114:6969/announce
udp://191.96.249.23:6969/announce
udp://193.203.61.5:2710/announce
udp://194.108.159.10:1337/announce
udp://198.167.223.75:6969/announce
udp://210.244.71.25:6969/announce
udp://211.149.236.45:6969/announce
udp://212.47.227.58:6969/announce
udp://213.153.68.28:1337/announce
udp://213.153.71.37:1337/announce
udp://37.187.123.8:2710/announce
udp://37.19.5.155:6969/announce
udp://45.77.11.89:6969/announce
udp://46.4.102.51:8082/announce
udp://46.4.109.148:6969/announce
udp://5.226.21.164:6969/announce
udp://5.255.86.8:6969/announce
udp://5.79.209.57:6969/announce
udp://5.79.83.194:6969/announce
udp://50.116.42.225:8000/announce
udp://51.15.4.13:1337/announce
udp://62.212.85.66:2710/announce
udp://68.64.165.106:2710/announce
udp://74.82.52.209:6969/announce
udp://75.127.14.224:2710/announce
udp://77.51.181.209:6969/announce
udp://78.142.19.218:1337/announce
udp://82.117.175.6:2710/announce
udp://82.45.40.204:1337/announce
udp://85.204.49.104:2710/announce
udp://86.19.29.160:6969/announce
udp://87.110.219.191:6969/announce
udp://87.120.254.233:6969/announce
udp://87.233.192.220:6969/announce
udp://89.234.156.205:451/announce
udp://91.134.182.38:6969/announce
udp://91.212.150.191:3418/announce
udp://91.217.91.21:3218/announce
udp://94.23.217.90:1337/announce
udp://bt.aoeex.com:8000/announce
udp://packages.crunchbangplusplus.org:6969/announce
udp://sandrotracker.biz:1337/announce
udp://santost12.xyz:6969/announce
udp://tc.animereactor.ru:8082/announce
udp://tracker.acg.gg:2710/announce
udp://tracker.coppersurfer.tk:6969/announc
udp://tracker.dutchtracking.com:6969/announce
udp://tracker1.itzmx.com:8080/announce
udp://tracker2.itzmx.com:6961/announce
udp://tracker3.itzmx.com:6961/announce
udp://tracker4.itzmx.com:2710/announce
http://tracker4.itzmx.com:2710/stats
http://tracker.openbittorrent.com:80/announce
http://tracker.publicbt.com:80/announce
http://tracker.prq.to/announce.php
http://nyaatorrents.info:3277/announce
udp://tracker.ktxp.com:6868/announce
udp://tracker.ktxp.com:7070/announce
http://tracker.ipv6tracker.org:80/announce
udp://t.nyaatracker.com:80/announce
https://tracker.nanoha.org/announce

**Comment by ngosang** [comment]
Added some of them. Thank you!
