### ISSUE TITLE
New public tracker

### ISSUE THREAD

**Issue by psharma04** [ngosang/trackerslist#190]
New public tracker: http://npserver.intranet.pw:4201
Supports UDP, HTTP and WS torrenting.
Disclaimer: Owned by me

**Comment by psharma04** [comment]
Links: 
udp://npserver.intranet.pw:4201
http://npserver.intranet.pw:4201
ws://npserver.intranet.pw:4201

**Comment by ngosang** [comment]
Added. Thank you
