### ISSUE TITLE
check tracker，thanks

### ISSUE THREAD

**Issue by OR120** [ngosang/trackerslist#195]
http://tracker.minglong.org:8080/announce
http://open.touki.ru/announce.php
http://share.camoe.cn:8080/announce
udp://tracker.xku.tv:6969/announce
http://alpha.torrenttracker.nl:443/announce
udp://tracker.christianbro.pw:6969/announce
http://retracker.spark-rostov.ru:80/announce
udp://sd-95.allfon.net:2710/announce
http://tracker.electro-torrent.pl:80/announce
udp://tc.animereactor.ru:8082/announce
udp://tracker.dutchtracking.com:6969/announce
udp://tracker.open-internet.nl:6969/announce
http://tracker.internetwarriors.net:1337/announce
udp://tracker1.itzmx.com:8080/announce
udp://tracker1.wasabii.com.tw:6969/announce
http://tracker.port443.xyz:6969/announce
http://private.minimafia.nl:443/announce
http://prestige.minimafia.nl:443/announce
http://opentracker.xyz:80/announce
http://tracker.novg.net:6969/announce
wss://tracker.openwebtorrent.com:443/announce
udp://packages.crunchbangplusplus.org:6969/announce
http://tracker.open-tracker.org:1337/announce
http://peersteers.org:80/announce
http://ehtracker.org/1350470/2999625xEuFo1NzT6D/announce
http://open.acgnxtracker.com/announce
https://open.acgnxtracker.com/announce
http://tracker.acg.gg:2710/scrape
http://tracker.acg.gg:2710/announce
http://www.loushao.net:8080/announce
http://tracker2.torrentino.com:80/announce
http://tracker3.torrentino.com:80/announce
http://t.nyaatracker.com/announce
http://104.238.198.186:8000/announce
http://tracker.ipv6tracker.ru/announce
http://tracker.36dm.com:2710/announce
http://www.36dm.com:2710/announce
http://tracker.36dm.com:2710/scrape
http://bt.avbt123.com:2710/announce
http://tracker.1zy.io:2710/announce
udp://tracker.dmhy.org:8000/announce
http://tracker.dmhy.org:8000/announce
udp://104.238.198.186:8000/announce
https://t-115.rhcloud.com/only_for_ylbud
udp://tracker.publicbt.com:80/announce
http://tr.bangumi.moe:6969/announce
http://open.nyaatorrents.info:6544/announce
http://t2.popgo.org:7456/annonce
http://opentracker.acgnx.se/announce
http://tracker.acgnx.se/announce
http://nyaa.tracker.wf:7777/announce
udp://t.nyaatracker.com:80/announce
https://tr.bangumi.moe:9696/announce
http://tracker.kamigami.org:2710/announce
https://tracker.nanoha.org/announce
http://bigfoot1942.sektori.org:6969/announce
udp://tracker.prq.to:80/announce
http://94.228.192.98/announce
http://share.dmhy.org/annonuce
http://tracker.btcake.com/announce
http://tracker.ktxp.com:6868/announce
http://tracker.ktxp.com:7070/announce
http://bt.sc-ol.com:2710/announce
http://btfile.sdo.com:6961/announce
http://exodus.desync.com:6969/announce
udp://coppersurfer.tk:6969/announce
http://tracker3.torrentino.com/announce
http://tracker2.torrentino.com/announce
udp://open.demonii.com:1337/announce
udp://tracker.ex.ua:80/announce
http://pubt.net:2710/announce
http://tracker.tfile.me/announce
udp://bt.sc-ol.com:2710/announce
http://tracker.acgsou.com:2710/announce
http://tracker.acgsou.com:2710/scrape
http://www.acgsou.com:2710/announce
udp://tracker.gbitt.info:80/announce
http://announce.xxx-tracker.com:2710/announce
http://tracker1.wasabii.com.tw:6969/announce
http://www.megatorrents.kg/announce.php
http://tracker.etree.org:6969/announce
http://nethd.org/announce.php
https://tracker.hdcmct.org/announce.php
udp://tracker.nwps.ws:6969/announce
udp://00.syo.mx:53/announce
https://linetorrent.xyz:443/announce
http://secure.pow7.com:80/announce
udp://tracker.baravik.org:6970/announce
udp://tracker2.wasabii.com.tw:6969/announce
udp://tracker.piratepublic.com:1337/announce
udp://tracker.filetracker.pl:8089/announce
http://retracker.gorcomnet.ru:80/announce
udp://ulfbrueggemann.no-ip.org:6969/announce
udp://tracker.files.fm:6969/announce
http://tracker.kuroy.me:5944/announce
udp://tracker.bbnet.io:3005/announce
http://tracker.zaerc.com:80/announce
udp://tracker.bluefrog.pw:2710/announce
http://tracker.calculate.ru:6969/announce
http://grifon.info:80/announce
http://retracker.krs-ix.ru:80/announce
https://lgtracker.org:443/announce
http://tracker.devil-torrents.pl:80/announce
udp://leecherhaven.zapto.org:6969/announce
udp://open.facedatabg.net:6969/announce
http://asnet.pw:2710/announce
udp://auratorrent.pl:8089/announce
https://p2pdl.com:443/announce
http://tr.cili001.com:6666/announce
udp://tracker.safe.moe:6969/announce
http://tracker.videodrugproject.com:80/announce
http://sound-park.ru:80/announce
udp://wambo.club:1337/announce
https://opentracker-milanesi.rhcloud.com:443/announce
https://tracker.baka-sub.cf:443/announce
udp://tracker.halfchub.club:6969/announce
udp://tracker.sktorrent.net:6969/announce
udp://tracker.auratorrent.pl:8089/announce
udp://tracker1.xku.tv:6969/announce
http://pt.lax.mx:80/announce
udp://trackerxyz.tk:1337/announce
http://hlotsof.hopto.org:5000/announce
http://ns349743.ip-91-121-106.eu:80/announce
udp://santost12.xyz:6969/announce
udp://bt.aoeex.com:8000/announce
http://tlm-project.org:6969/announce
udp://t.xk.is:1337/announce
http://tracker.btsync.cf:233/announce
http://tracker.miruict.nl:80/announce

**Comment by ngosang** [comment]
added some of them. thank you
