### ISSUE TITLE
【tracker.btsync.gq】更新(update)

### ISSUE THREAD

**Issue by lirener** [ngosang/trackerslist#196]
udp://tracker.btsync.gq:233/announce
udp://tracker.btsync.gq:2710/announce
udp://tracker.btsync.gq:6969/announce

原地址 域名 即将过期（The original address domain name will expire）
更新(update)

udp://qg.lorzl.gq:233/announce
udp://qg.lorzl.gq:2710/announce
udp://qg.lorzl.gq:6969/announce

其他镜像(other standby)
lm.lorzl.ml
fc.lorzl.cf
kt.lorzl.tk
ag.lorzl.ga
qg.lorzl.gq

目前均开放了233、2710、6969这3个端口（Are opening up 233, 2710, 6969, the three ports）

**Comment by ngosang** [comment]
the new / stable domain is qg.lorzl.gq. right?
changed thank you

**Comment by lirener** [comment]
yes~

**Comment by ngosang** [comment]
udp://qg.lorzl.gq:2710/announce is in the list

**Comment by lirener** [comment]
sure~
thankQ~

**Comment by lirener** [comment]
new tracker for IPV6：

http://ipv6.tracker.btsync.gq:2710/announce
or
http://ipv6.lorzl.gq:2710/announce

同时，我想233和6969端口也同时在工作；
(At the same time, I want to ports 233 and 6969 also at work at the same time;)
ws://目前只有2710开放，并且我不确定他是否工作
(Ws: / / at present only 2710 open, and I'm not sure if he is working)

**Comment by lirener** [comment]
udp在IPV6工作遇到问题 短时间内 我无法解决 可能要等以后了
Udp works in IPV6 encounter problems in a short period of time I can't solve may have to wait for later
