### ISSUE TITLE
Add new tracker with dns

### ISSUE THREAD

**Issue by gfoligna** [ngosang/trackerslist#199]
http://caramelo.ddns.net:8000/announce
udp://caramelo.ddns.net:8000/

Thanks :)

**Comment by kompowiec** [comment]
http://www.sumotracker.org/announce

**Comment by ngosang** [comment]
> http://caramelo.ddns.net:8000/announce
udp://caramelo.ddns.net:8000/

Added. Thank you!

> http://www.sumotracker.org/announce
http://www.torrent-downloads.to:2710/announce

They are not working.
