### ISSUE TITLE
Gathered List Duplicates Removed.

### ISSUE THREAD

**Issue by Inysal** [ngosang/trackerslist#2]
Not All were Tested.

http://133.130.108.127:6969/announce

http://149.5.241.17:6969/announce

http://173.254.204.71:1096/announce

http://182.176.139.129:6969/announce

http://193.107.16.156:2710/announce

http://210.244.71.11:6969/announce

http://3dfreedom.ru:6969/announce

http://5.79.83.193:2710/announce

http://77.247.178.8:80/announce

http://91.218.230.81:6969/announce

http://academic-p2p.appspot.com/announce

http://academic-p2p.carlosdelfino.eti.br/announce

http://announce.torrentsmd.com:6969/announce

http://atrack.moviesndroids.com/announce

http://atrack.pow7.com/announce

http://bt-club.ws/announce.php

http://bt.careland.com.cn:6969/announce

http://bt.henbt.com:2710/announce

http://bt.pusacg.org:8080/announce

http://bt.rutracker.cc/ann

http://bt2.careland.com.cn:6969/announce

http://bt2.rutracker.cc/ann

http://bt3.rutracker.cc/ann

http://bt4.rutracker.cc/ann

http://bt4.rutracker.cc/ann?magnet

http://bttracker.crunchbanglinux.org:6969/announce

http://cernet-tracker.appspot.com/announce

http://cpleft.com:2710/announce

http://exodus.desync.com/announce

http://explodie.org:6969/announce

http://glotorrents.com:6969/announce

http://glotorrents.pw:6969/announce

http://inferno.demonoid.me:3414/announce

http://mgtracker.org:2710/announce

http://mgtracker.org:6969/announce

http://open.acgtracker.com:1096/announce

http://open.touki.ru/announce.php

http://open.tracker.skyts.net:6969/announce

http://p4p.arenabg.ch:1337/announce

http://p4p.arenabg.com:1337/announce

http://pow7.com/announce

http://pow7.com:80/announce

http://retracker.2kom.ru/announce

http://retracker.hotplug.ru:2710/announce

http://retracker.kld.ru/announce

http://retracker.kld.ru:2710/announce

http://retracker.krs-ix.ru/announce

http://retracker.krs-ix.ru:80/announce

http://secure.pow7.com/announce

http://server1.9sheng.cn:6969/announce

http://t.bitlove.org/announce

http://t1.pow7.com/announce

http://t2.pow7.com/announce

http://thetracker.org/announce

http://thetracker.org:80/announce

http://torrent.gresille.org/announce

http://torrent.gresille.org:80/announce

http://torrentsmd.com:8080/announce

http://tracker.aletorrenty.pl:2710/announce

http://tracker.baravik.org:6970/announce

http://tracker.best-torrents.net:6969/announce

http://tracker.bittor.pw:1337/announce

http://tracker.bittorrent.am/announce

http://tracker.btcake.com/announce

http://tracker.coppersurfer.tk/announce

http://tracker.coppersurfer.tk:6969/announce

http://tracker.dler.org:6969/announce

http://tracker.dutchtracking.com/announce

http://tracker.dutchtracking.com:80/announce

http://tracker.dutchtracking.nl/announce

http://tracker.dutchtracking.nl:80/announce

http://tracker.edoardocolombo.eu:6969/announce

http://tracker.ex.ua/announce

http://tracker.ex.ua:80/announce

http://tracker.filetracker.pl:8089/announce

http://tracker.flashtorrents.org:6969/announce

http://tracker.glotorrents.com:6969/announce

http://tracker.grepler.com:6969/announce

http://tracker.kicks-ass.net:80/announce

http://tracker.kuroy.me:5944/announce

http://tracker.mg64.net:6881/announce

http://tracker.novalayer.org:6969/announce

http://tracker.ohys.net:80/announce

http://tracker.opentrackr.org:1337/announce

http://tracker.pubt.net:2710/announce

http://tracker.skyts.net:6969/announce

http://tracker.tfile.me/announce

http://tracker.tiny-vps.com:6969/announce

http://tracker.torrentbay.to:6969/announce

http://tracker.torrenty.org:6969/announce

http://tracker.trackerfix.com/announce

http://tracker.tricitytorrents.com:2710/announce

http://tracker.tvunderground.org.ru:3218/announce

http://tracker.veryamt.com/announce

http://tracker.yoshi210.com:6969/announce

http://tracker.yoshi210.com:6969/announce

http://tracker1.itzmx.com:8080/announce

http://tracker1.wasabii.com.tw:6969/announce

http://tracker2.itzmx.com:6961/announce

http://tracker2.wasabii.com.tw:6969/announce

http://tracker3.infohash.org/announce

http://trackeropenbittorrent.uni.me/announce

http://ulfbrueggemann.no-ip.org:6969/announce

http://www.skyts.net:6969/announce

http://www.wareztorrent.com:80/announce

udp://107.150.14.110:6969/announce

udp://11.rarbg.com/announce

udp://11.rarbg.com:6969/announce

udp://11.rarbg.com:80/announce

udp://11.rarbg.me:6969/announce

udp://11.rarbg.me:80/announce

udp://11.rarbg.to:6969/announce

udp://11.rarbg.to:80/announce

udp://168.235.67.63:6969/announce

udp://168.235.67.63:6969/announce

udp://174.140.167.167:5944/announce

udp://182.176.139.129:6969/announce

udp://182.176.139.129:6969/announce

udp://185.50.198.188:1337/announce

udp://208.67.16.113:8000/annonuce

udp://62.138.0.158:6969/announce

udp://9.rarbg.com:2710/announce

udp://9.rarbg.me:2710/announce

udp://9.rarbg.to:2710/announce

udp://91.218.230.81:6969/announce

udp://berylliumsurfer.tk:6969/announce

udp://bismuthsurfer.tk:6969/announce

udp://bt.rutor.org:2710

udp://bt.xxx-tracker.com:2710/announce

udp://coppersurfer.tk:6969/announce

udp://eddie4.nl:6969/announce

udp://exodus.desync.com:6969/announce

udp://explodie.org:6969/announce

udp://fr33dom.h33t.com:3310/announce

udp://galliumsurfer.tk:6969/announce

udp://germaniumsurfer.tk:6969/announce

udp://glotorrents.com:6969/announce

udp://glotorrents.pw:6969/announce

udp://indiumsurfer.tk:6969/announce

udp://ipv4.tracker.harry.lu:80/announce

udp://ironsurfer.tk:6969/announce

udp://mgtracker.org:2710/announce

udp://open.demonii.com:1337/announce

udp://open.stealth.si:80/announce

udp://p4p.arenabg.ch:1337

udp://p4p.arenabg.ch:1337/announc

udp://p4p.arenabg.com:1337

udp://p4p.arenabg.com:1337/announce

udp://poloniumsurfer.tk:6969/announce

udp://pow7.com:80/announce

udp://pubt.net:2710/announce

udp://rhodiumsurfer.tk:6969/announce

udp://shadowshq.eddie4.nl:6969/announce

udp://shadowshq.yi.org:6969/announce

udp://thetracker.org/announce

udp://tinsurfer.tk:6969/announce

udp://torrent.gresille.org:80/announce

udp://torrentsmd.com:8080/announce

udp://tracker.1337x.org:80/announce

udp://tracker.aletorrenty.pl:2710/announce

udp://tracker.bittor.pw:1337

udp://tracker.bittorrent.am/announce

udp://tracker.blackunicorn.xyz:6969/announce

udp://tracker.btcake.com/announce

udp://tracker.btzoo.eu:80/announce

udp://tracker.ccc.de:80/announce

udp://tracker.coppersurfer.tk/announce

udp://tracker.coppersurfer.tk:1337/announce

udp://tracker.coppersurfer.tk:6969

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.dler.org:6969/announce

udp://tracker.dutchtracking.com:80/announce

udp://tracker.dutchtracking.nl:80/announce

udp://tracker.eddie4.nl:6969/announce

udp://tracker.edoardocolombo.eu:6969/announce

udp://tracker.ex.ua:80/announce

udp://tracker.filetracker.pl:8089/announce

udp://tracker.flashtorrents.org:6969/announce

udp://tracker.glotorrents.com:6969/announce

udp://tracker.grepler.com:6969/announce

udp://tracker.internetwarriors.net:1337

udp://tracker.istole.it:80/announce

udp://tracker.kicks-ass.net:80/announce

udp://tracker.kuroy.me:5944/announce

udp://tracker.leechers-paradise.org:6969

udp://tracker.leechers-paradise.org:6969/announce

udp://tracker.mg64.net:2710/announce

udp://tracker.mg64.net:6969/announce

udp://tracker.ohys.net:80/announce

udp://tracker.openbittorrent.com:6969/announce

udp://tracker.openbittorrent.com:80

udp://tracker.openbittorrent.com:80/announce

udp://tracker.opentrackr.org:1337/announce

udp://tracker.pomf.se:80/announce

udp://tracker.prq.to/announce

udp://tracker.publicbt.co:6969/announce

udp://tracker.publicbt.com:80/announce

udp://tracker.pubt.net:2710/announce

udp://tracker.sktorrent.net:6969

udp://tracker.skyts.net:6969/announce

udp://tracker.tiny-vps.com:6969/announce

udp://tracker.trackerfix.com:80/announce

udp://tracker.tricitytorrents.com:2710/announce

udp://tracker.yoshi210.com:6969/announce

udp://tracker2.indowebster.com:6969/announce

udp://tracker2.itzmx.com:6961/announce

udp://tracker4.infohash.org:80/announce

udp://www.eddie4.nl:6969/announce

udp://www.wareztorrent.com:80/announce

**Comment by ngosang** [comment]
All working trackers are already listed.
Thanks for reporting.
