### ISSUE TITLE
Cannot access githubusercontents

### ISSUE THREAD

**Issue by fxqy** [ngosang/trackerslist#202]
Cannot access githubusercontents，Why don't you turn on githubpages service?

**Comment by ngosang** [comment]
I will think about that. The main concern is I have to change the repository name and that will break the installation of many users.

**Comment by yilin101** [comment]
trackers更新任务已存在。

wget: bad address 'raw.githubusercontent.com'

awkNF: /tmp/trackers_all.txt: No such file or directory 

更新文件未正确下载，更新未成功，请检查网络。

**Comment by makeworld-the-better-one** [comment]
@ngosang you wouldn't have to change the repository name I don't think.

**Comment by ngosang** [comment]
Github Pages enabled and running. Check the readme.
