### ISSUE TITLE
new tracker

### ISSUE THREAD

**Issue by borekon** [ngosang/trackerslist#203]
I've _installed_ another tracker, until it lasts:
https://vps2.avc.cx/announce.php

**Comment by MaleiSiyin** [comment]
http://tracker.googlecn.cc:1997
udp://tracker.googlecn.cc:1997

**Comment by ngosang** [comment]
> https://vps2.avc.cx/announce.php

It's not working. Anyway, I don't want to add temporary / amateur trackers...

> http://tracker.googlecn.cc:1997
udp://tracker.googlecn.cc:1997

Not working well. Always returning 0 peers...

**Comment by borekon** [comment]
Yes, it is working. It's not temporary / amateur but no problem anyway.

**Comment by borekon** [comment]
One year working flawlessly, now added the udp capability:
udp://vps2.avc.cx:7171
http://vps2.avc.cx:7171

**Comment by ngosang** [comment]
Added. Thank you!
