### ISSUE TITLE
New tracker udp://tracker.pomf.se:80

### ISSUE THREAD

**Issue by Redxtorm** [ngosang/trackerslist#207]
Just found a nice tracker that was not in this repo: **udp://tracker.pomf.se:80/announce**. Please add it to [trackers_best.txt](https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt) or [trackers_all_udp.txt](https://github.com/ngosang/trackerslist/blob/master/trackers_all_udp.txt)

**Comment by ngosang** [comment]
> udp://p4p.arenabg.com:1337
udp://tracker.pomf.se:80

Added both. Thank you!

**Comment by fotofrank** [comment]
pomf.se triggers Malwarebytes Anti Malware
