### ISSUE TITLE
What makes a tracker "good"?

### ISSUE THREAD

**Issue by MikeLund** [ngosang/trackerslist#21]
Hi, interesting list, nice work!

Just wondering a bit behind your calculation algorithms though. How do you determine if a tracker is "good"/"best" or whatnot? 

You say they are sorted on popularity and latency, but most trackers have hidden stats. And latency doesn't make a difference on a tracker, as long as it's under a couple seconds.. so I don't really understand the theory behind your "best" list. Or is there some other data source you're using?

(Would love to have your scanning script public so I could just answer these for myself :p)
Thanks for any explanation! :)

**Comment by ngosang** [comment]
My bot ask to all trackers for several popular torrents. Trackers are sorted by uptime, number of peers+seeds and latency (in that oorder).

**Comment by MikeLund** [comment]
So if some tracker is very widely used in China for example, having tens of million of peers, it might not be classified as a "best" tracker if popular English-Internet users don't use it much.
Makes sense, thanks!
