### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by appmakerz00** [ngosang/trackerslist#212]
How do i use this Blacklist to automatically remove duplicate trackers?
I want it to remove copies of the same tracker even though it has a other hostname 

"udp://9.rarbg.to:2730/announce # duplicate of udp://9.rarbg.to:2710/announce"

 I only wanna keep on of them of course so i dont clug up my torrent client with unnecessary trackers

**Comment by ngosang** [comment]
The list provided by this site are already clean. Just use one of them.
