### ISSUE TITLE
new open tracker (opentracker.i2p.rocks)

### ISSUE THREAD

**Issue by majestrate** [ngosang/trackerslist#216]
announce urls: 

http://opentracker.i2p.rocks:6969/announce 
udp://opentracker.i2p.rocks:6969/announce

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by sastofficial** [comment]
doesnt work for me anymore

**Comment by majestrate** [comment]
yea the datacenter the box is is having.... issues. i am looking for a better host that isn't OVH. have not spent lots of time to find one, may do hetzner.

**Comment by majestrate** [comment]
issues with dc rectified. 
suggestion: use https instead of plaintext http on 6969 if you can.

udp://opentracker.i2p.rocks:6969
https://opentracker.i2p.rocks/announce

**Comment by ngosang** [comment]
@majestrate only HTTPS is working. UDP and HTTP are down from here.

**Comment by majestrate** [comment]
i had a straggling firewall rule that i just removed dropping port 6969. it should be reachable via udp/6969 and tcp/6969 shortly.

**Comment by ngosang** [comment]
It's working now. It will appear on the list tomorrow.
