### ISSUE TITLE
New open tracker : ZeroBytes

### ISSUE THREAD

**Issue by z3r0byt3s** [ngosang/trackerslist#217]
IPv4
```
http://tracker.zerobytes.xyz:1337
udp://tracker.zerobytes.xyz:1337
```

Thx!

**Comment by z3r0byt3s** [comment]
ZeroBytes IPv6 support added on port **16661** and ip **2001:bc8:1830:506::1**

http://[2001:bc8:1830:506::1]:16661

udp://[2001:bc8:1830:506::1]:16661

**Comment by ngosang** [comment]
Added ipv4, we don't support ipv6 yet #72
Thank you!
