### ISSUE TITLE
This is all I know public trackers

### ISSUE THREAD

**Issue by tkp206093** [ngosang/trackerslist#218]
http://tr.bangumi.moe:6969/announce

http://tracker.gcvchp.com:2710/announce

udp://tracker.internetwarriors.net:1337/announce

udp://tracker.opentrackr.org:1337/announce

udp://exodus.desync.com:6969/announce

udp://explodie.org:6969/announce

udp://tracker1.itzmx.com:8080/announce

udp://ipv4.tracker.harry.lu:80/announce

udp://denis.stalker.upeer.me:6969/announce

udp://tracker.vanitycore.co:6969/announce

udp://tracker.torrent.eu.org:451/announce

udp://thetracker.org:80/announce

udp://open.stealth.si:80/announce

udp://open.demonii.si:1337/announce

udp://bt.xxx-tracker.com:2710/announce

udp://retracker.lanta-net.ru:2710/announce

udp://tracker.uw0.xyz:6969/announce

udp://tracker.tiny-vps.com:6969/announce

udp://tracker.nibba.trade:1337/announce

udp://bt.dy20188.com:80/announce

http://gwp2-v19.rinet.ru:80/announce

http://sub4all.org:2710/announce

udp://tracker.kamigami.org:2710/announce

http://tracker.kamigami.org:2710/announce

http://open.acgtracker.com:1096/announce

http://tracker4.itzmx.com:2710/announce

http://tracker3.itzmx.com:6961/announce

http://tracker.vanitycore.co:6969/announce

http://tracker.tiny-vps.com:6969/announce

http://tracker.grepler.com:6969/announce

http://tracker.baravik.org:6970/announce

http://torrentsmd.com:8080/announce

http://inferno.demonoid.ooo:3416/announce

http://inferno.demonoid.ooo:3412/announce

http://t.nyaatracker.com/announce

http://tracker.xfsub.com:6868/announce

udp://shadowshq.yi.org:6969/announce

udp://shadowshq.eddie4.nl:6969/announce

https://trackerslis.com/announce

http://tracker.tfile.me/a

http://tracker.tfile.me/announce

http://trun.tom.ru:80/announce

wws://tracker.darli.net:6611/announce

udp://165.231.0.116:80/announce

udp://89.234.156.205:451/announce

udp://95.216.171.255:6969/announce

udp://91.217.91.21:3218/announce

http://51.38.230.101:80/announce

http://52.203.255.14:80/announce

udp://194.143.148.21:2710/announce

udp://176.113.68.67:6961/announce

https://212.237.22.141:443/announce

http://212.1.226.176:2710/announce

http://176.113.68.66:6961/announce

http://80.209.252.132:1337/announce

https://tracker.nyaa.tk:443/announce

udp://bt.hackfront.tk:6969/announce

udp://cx42light.cn:39652/announce

https://bt.proxy-for.ga:443/announce

udp://www.loushao.net:8080/announce

https://rt.msk-server.ga:443/announce

https://rt6.msk-server.ga:443/announce

udp://opentracker.arg.bz:6969/announce

udp://tracker.btsync.gq:233/announce

https://2.tracker.eu.org:443/announce

https://tracker.no-dmca.ninja:2087/announce

http://atrack.pow7.com:80/announce

https://tracker.fr.eu.org:8443/announce

https://tracker.heaterdown.eu:443/announce

https://3.tracker.eu.org:443/announce

https://tracker6.lelux.fi:443/announce

https://1.tracker.eu.org:443/announce

udp://z.crazyhd.com:2710/announce

http://wegkxfcivgx.chickenkiller.com:80/announce

http://re-tracker.uz:80/announce

http://tracker.darli.net:6611/announce

http://retracker.joxnet.ru:80/announce

udp://tracker.edoardocolombo.eu:6969/announce

udp://mgtracker.org:6969/announce

http://tracker.skyts.cn:6969/announce

http://torrent.nwps.ws:80/announce

udp://tracker.acg.gg:2710/announce

http://omg.wtftrackr.pw:1337/announce

https://evening-badlands-6215.herokuapp.com:443/announce

https://open.acgnxtracker.com:443/announce

http://bt.dl1234.com:80/announce

udp://torr.ws:2710/announce

udp://inferno.demonoid.ooo:3389/announce

http://retracker.spb.ru:80/announce

udp://tr.greenhat.be:80/announce

udp://tracker.qt.is:6969/announce

http://tracker.seedboxing.tk:9000/announce

https://1.track.ga:443/announce

udp://mydmplus.com:8080/announce

https://tracker.torrentsnows.com:443/announce

http://peach.urown.cloud:6969/announce

udp://tracker.sandrotracker.biz:6969/announce

http://therightsize.net:80/announce

http://nbz.f3322.net:36006/announce

http://tracker.y34r.net:80/announce

https://tracker.trackerlist.org:443/announce

https://2.track.ga:443/announce

http://node.611.to:9000/announce

udp://hk1.opentracker.ga:6969/announce

udp://prestige.minimafia.nl:443/announce

http://tracker.openzim.org:80/announce

udp://tracker.skynetcloud.tk:6969/announce

udp://tracker.freddit.nl:6969/announce

udp://tracker.open-tracker.org:1337/announce

udp://bt.oiyo.tk:6969/announce

https://tracker.parrotsec.org:443/announce

udp://tracker.kiwifarms.net:8000/announce

http://trk.kuzko.eu:6969/announce

http://web4.obit.ru:80/announce

http://tracker.vivancos.eu:80/announce

udp://retracker.maxnet.ua:80/announce

http://bt1.xxxxbt.cc:6969/announce

udp://tracker.fixr.pro:6969/announce

http://vps.tracker.eu.org:9000/announce

udp://tracker01.loveapp.com:6789/announce

http://retracker.goodline.info:80/announce

udp://opentracker.sktorrent.org:6969/announce

udp://tracker123.cn:8080/announce

udp://tracker.patatje.eu:6969/announce

udp://npserver.intranet.pw:4201/announce

http://tracker.noobsubs.net:80/announce

https://tr.zhina.org:443/announce

http://tracker.paypp.xyz:2783/announce

wss://tracker.btorrent.xyz:443/announce

udp://151.80.120.115:2710/announce

udp://5.206.3.65:6969/announce

udp://78.142.18.55:1337/announce

udp://78.142.18.61:6969/announce

http://54.165.216.26:80/announce

udp://218.5.41.120:2710/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://p4p.arenabg.com:1337/announce

udp://tracker.openbittorrent.com:80/announce

udp://tracker.moeking.me:6969/announce

udp://tracker.cyberia.is:6969/announce

udp://tracker3.itzmx.com:6961/announce

udp://zephir.monocul.us:6969/announce

udp://xxxtor.com:2710/announce

udp://valakas.rollo.dnsabr.com:2710/announce

udp://tracker.zum.bi:6969/announce

udp://tracker.yoshi210.com:6969/announce

udp://tracker.sbsub.com:2710/announce

udp://tracker.nyaa.uk:6969/announce

udp://tracker.nextrp.ru:6969/announce

udp://tracker.lelux.fi:6969/announce

udp://tracker.iamhansen.xyz:2000/announce

udp://tracker-udp.gbitt.info:80/announce

udp://retracker.sevstar.net:2710/announce

udp://retracker.netbynet.ru:2710/announce

udp://retracker.akado-ural.ru:80/announce

udp://opentor.org:2710/announce

udp://open.nyap2p.com:6969/announce

udp://bt2.archive.org:6969/announce

udp://bt1.archive.org:6969/announce

udp://bt.okmp3.ru:2710/announce

https://tracker.nanoha.org:443/announce

http://www.proxmox.com:6969/announce

http://tracker.internetwarriors.net:1337/announce

http://tracker.bz:80/announce

http://tracker.bt4g.com:2095/announce

http://retracker.sevstar.net:2710/announce

http://h4.trakx.nibba.trade:80/announce

udp://tracker4.itzmx.com:2710/announce

udp://tracker2.itzmx.com:6961/announce

udp://tracker.zerobytes.xyz:1337/announce

udp://tracker.filemail.com:6969/announce

udp://tr.bangumi.moe:6969/announce

udp://qg.lorzl.gq:2710/announce

udp://opentracker.i2p.rocks:6969/announce

udp://chihaya.toss.li:9696/announce

udp://bt2.54new.com:8080/announce

https://tracker.parrotlinux.org:443/announce

https://tracker.opentracker.se:443/announce

https://tracker.lelux.fi:443/announce

https://tracker.gbitt.info:443/announce

http://www.loushao.net:8080/announce

http://vps02.net.orel.ru:80/announce

http://tracker2.itzmx.com:6961/announce

http://tracker1.itzmx.com:8080/announce

http://tracker01.loveapp.com:6789/announce

http://tracker.zerobytes.xyz:1337/announce

http://tracker.yoshi210.com:6969/announce

http://tracker.nyap2p.com:8080/announce

http://tracker.lelux.fi:80/announce

http://tracker.gbitt.info:80/announce

http://opentracker.i2p.rocks:6969/announce

http://open.acgnxtracker.com:80/announce

http://mail2.zelenaya.net:80/announce

wss://tracker.sloppyta.co:443/announce

wss://tracker.openwebtorrent.com:443/announce

wss://tracker.novage.com.ua:443/announce

udp://62.138.0.158:6969/announce

udp://188.241.58.209:6969/announce

udp://93.158.213.92:1337/announce

udp://80.209.252.132:1337/announce

udp://62.210.97.59:1337/announce

udp://151.80.120.112:2710/announce

udp://151.80.120.114:2710/announce

udp://208.83.20.20:6969/announce

udp://35.156.19.129:6969/announce

udp://159.100.245.181:6969/announce

udp://37.235.174.46:2710/announce

udp://185.181.60.67:80/announce

udp://51.15.40.114:80/announce

udp://184.105.151.164:6969/announce

udp://176.113.71.19:6961/announce

http://184.105.151.164:6969/announce

udp://185.83.215.123:6969/announce

udp://212.47.227.58:6969/announce

udp://95.211.168.204:2710/announce

udp://46.148.18.250:2710/announce

udp://165.227.0.51:6969/announce

udp://149.129.65.231:2710/announce

udp://15.188.67.15:6969/announce

udp://185.97.255.30:6969/announce

udp://51.158.23.91:6969/announce

udp://207.246.121.172:2000/announce

udp://109.72.83.214:80/announce

udp://78.30.254.12:2710/announce

udp://212.1.226.176:2710/announce

udp://217.76.183.53:80/announce

udp://46.148.18.254:2710/announce

udp://23.95.32.130:6969/announce

udp://207.241.231.226:6969/announce

udp://207.241.226.111:6969/announce

udp://207.180.241.35:2710/announce

http://79.133.36.244:6969/announce

http://93.158.213.92:1337/announce

http://176.123.5.118:80/announce

http://78.30.254.12:2710/announce

http://62.210.177.88:1096/announce

http://34.204.156.91:80/announce

udp://51.15.55.204:1337/announce

udp://52.58.128.163:6969/announce

udp://51.15.3.74:6969/announce

udp://185.83.214.123:6969/announce

udp://80.211.26.119:9696/announce

udp://139.99.100.97:8080/announce

https://51.158.23.91:443/announce

http://182.150.53.61:8080/announce

http://95.107.48.115:80/announce

http://95.211.168.204:2710/announce

http://176.113.71.19:6961/announce

http://34.92.10.197:6789/announce

http://51.15.55.204:1337/announce

http://51.254.249.186:6969/announce

http://51.158.23.91:80/announce

http://185.83.214.123:6969/announce

http://51.68.122.172:80/announce

http://91.207.136.85:80/announce

http://t.acg.rip:6699/announce

udp://9.rarbg.to:2740/announce

udp://9.rarbg.com:2770/announce

udp://9.rarbg.me:2710/announce

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by tkp206093** [comment]
I will secretly update here from time to time
