### ISSUE TITLE
is it possible to have additional lists?

### ISSUE THREAD

**Issue by tekko** [ngosang/trackerslist#22]
lists like udp_preferred and http_preferred?

For sites that support both udp and http:
udp_preferred removes the http
http_preferred removes the udp

I don't know how hard it is to do that. It's just a suggestion. 
Right now, I clean them manually. Is there a benefit to have both http and udp for the same tracker added to a torrent?

Thanks

**Comment by ngosang** [comment]
Sure, but I don't have time now. I will in the future.

**Comment by bug-me-not** [comment]
>**tekko** commented on 2 Oct 2016

>Sure, but I don't have time now. I will in the future.

>**bug-me-not** commented on 2 Oct 2017 :fireworks: :champagne:

'Nuff said :smile:

**Comment by ngosang** [comment]
I did the change. Instead of having 2 preferred lists, I'm giving priority udp over http/https in `trackers_best` list.
