### ISSUE TITLE
itzmx.com trackers manipulating torrent stats

### ISSUE THREAD

**Issue by L4yer** [ngosang/trackerslist#220]
trackers belonging to itzmx.com have been reported as manipulating torrent stats and will get you banned for using them on some public torrent sites. Please remove them from the list.

udp://tracker3.itzmx.com:6961/announce
udp://tracker4.itzmx.com:2710/announce
udp://tracker2.itzmx.com:6961/announce
http://tracker4.itzmx.com:2710/announce
http://tracker3.itzmx.com:6961/announce
http://tracker2.itzmx.com:6961/announce
http://tracker1.itzmx.com:8080/announce

**Comment by Tmp341** [comment]
Do you have a source for those reports?

**Comment by ngosang** [comment]
I need references or profs to remove any tracker.

**Comment by ragnaroks** [comment]
maybe he saw [this](https://bt.itzmx.com/)

**Comment by ngosang** [comment]
I did my own tests and I can't see anything wrong.
