### ISSUE TITLE
Missing leechers-paradise.org ?

### ISSUE THREAD

**Issue by Fluffkin** [ngosang/trackerslist#221]
I see a note at https://github.com/ngosang/trackerslist/issues/182 that a duplicate dns entry for udp://tracker.leechers-paradise.org:6969/announce got fixed, but now I see neither "open-internet.nl" or "leechers-paradise.org" in the trackers_all.txt list.

Did the fix manage to wipe out both entries?

**Comment by Fluffkin** [comment]
And now I see it's back, along with a bunch of duplicate IP's in the trackers_all_ip list (on the 30th Jan 2020). As far as I could be bothered to check by a line count, more than one duplicate.

For those struggling with the duplicates:
`perl -i -ne 'print if ! $x{$_}++' trackers_all_ip.txt`
Will strip out the dupes but leave the sort order intact.

**Comment by ngosang** [comment]
`udp://tracker.leechers-paradise.org:6969/announce` is up and running.

About duplicate IPs => https://github.com/ngosang/trackerslist/issues/222#issuecomment-581169684
