### ISSUE TITLE
Some trackers that you're missing are in this list.

### ISSUE THREAD

**Issue by styromaniac** [ngosang/trackerslist#225]
https://newtrackon.com/list

These are very stable.

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by styromaniac** [comment]
You added all the other ones from that site too, correct? Not just from that page?

I update a trackers list for ZeroNet, so I'm trying to be sure. Other people want as many trackers as possible.

**Comment by ngosang** [comment]
Yes, but the algorithm to check the trackers is different so the list can be.
In addition to checking that the tracker is online, my algorithm checks duplicate trackers, fake peers, response time, torrents with many seeds ... to ensure that the lists are stable and reliable over time.
