### ISSUE TITLE
All the collected trackers

### ISSUE THREAD

**Issue by maliks911** [ngosang/trackerslist#226]
http://explodie.org:6969/announce

wss://tracker.openwebtorrent.com:443/announce

udp://62.138.0.158:6969/announce

https://tracker.nanoha.org:443/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://tracker.opentrackr.org:1337/announce

udp://p4p.arenabg.com:1337/announce

udp://9.rarbg.to:2710/announce

udp://9.rarbg.me:2710/announce

udp://tracker.internetwarriors.net:1337/announce

udp://exodus.desync.com:6969/announce

udp://tracker.tiny-vps.com:6969/announce

udp://tracker.sbsub.com:2710/announce

udp://retracker.lanta-net.ru:2710/announce

udp://open.stealth.si:80/announce

udp://open.demonii.si:1337/announce

udp://tracker.torrent.eu.org:451/announce

udp://tracker.moeking.me:6969/announce

udp://tracker.cyberia.is:6969/announce

udp://denis.stalker.upeer.me:6969/announce

udp://explodie.org:6969/announce

udp://ipv4.tracker.harry.lu:80/announce

udp://zephir.monocul.us:6969/announce

udp://tracker.openbittorrent.com:80

udp://open.demonii.com:1337

udp://tracker.coppersurfer.tk:6969

udp://tracker.acg.gg:2710/announce

http://tracker3.itzmx.com:8080/announce

http://bt.acg.gg:1578/announce

http://open.acgnxtracker.com/announce

http://retracker.spb.ru:80/announce

http://tracker.tfile.co:80/announce

https://open.acgnxtracker.com:443/announce

http://share.camoe.cn:8080/announce

udp://open.stealth.si:80/announce

udp://bt.xxx-tracker.com:2710/announce

udp://tracker.trackerfix.com:80/announce

udp://tracker.0o.is:6969/announce

udp://public.popcorn-tracker.org:6969/announce

udp://tracker.open-internet.nl:6969/announce

udp://ipv4.tracker.harry.lu:80/announce

udp://tracker.cypherpunks.ru:6969/announce

udp://tracker.vanitycore.co:6969/announce

udp://thetracker.org:80/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.justseed.it:1337/announce

udp://tracker.tiny-vps.com:6969/announce

udp://exodus.desync.com:6969/announce

udp://tracker.ds.is:6969/announce

udp://9.rarbg.me:2730/announce

udp://9.rarbg.to:2770/announce

udp://tracker.qt.is:6969/announce

udp://open.demonii.si:1337/announce

udp://tracker.port443.xyz:6969/announce

udp://tracker.torrent.eu.org:451/announce

udp://glotorrents.pw:6969/announce

udp://ipv6.tracker.harry.lu:80/announce

udp://asnet.pw:2710/announce

udp://tracker.zer0day.to:1337/announce

udp://tracker.cyberia.is:6969/announce

udp://inferno.demonoid.pw:3418/announce

udp://tracker.mg64.net:6969/announce

udp://eddie4.nl:6969/announce

udp://shadowshq.yi.org:6969/announce

udp://denis.stalker.upeer.me:1337/announce

udp://p4p.arenabg.ch:1337/announce

udp://IPv6.open-internet.nl:6969/announce

udp://tracker.torrent.eu.org:451

udp://9.rarbg.me:2710/announce

udp://9.rarbg.me:2770/announce

udp://9.rarbg.me:2740/announce

udp://9.rarbg.to:2710/announce

udp://9.rarbg.to:2720/announce

udp://9.rarbg.to:2740/announce

udp://9.rarbg.to:2730/announce

udp://tracker.opentrackr.org:1337/announce

udp://tracker.internetwarriors.net:1337/announce

udp://tracker.pirateparty.gr:6969/announce

udp://tracker.coppersurfer.tk:80/announce

udp://tracker.coppersurfer.tkg:6969/announce

udp://explodie.org:6969/announce

udp://exodus.desync.com:6969

udp://tracker.coppersurfer.tk:6969/announce

udp://9.rarbg.com:2710/announce

udp://p4p.arenabg.com:1337

udp://tracker.internetwarriors.net:1337

udp://tracker.opentrackr.org:1337/announce

udp://tracker.zer0day.to:1337/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://coppersurfer.tk:6969/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://9.rarbg.com:2710/announce

udp://p4p.arenabg.com:1337

udp://tracker.internetwarriors.net:1337

udp://tracker.opentrackr.org:1337/announce

udp://tracker.zer0day.to:1337/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://coppersurfer.tk:6969/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://9.rarbg.com:2710/announce

udp://p4p.arenabg.com:1337

udp://tracker.internetwarriors.net:1337

udp://tracker.opentrackr.org:1337/announce

udp://tracker.zer0day.to:1337/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://coppersurfer.tk:6969/announce

http://220.162.244.175:53880/announce 

http://www.ipmart-forum.com:2710/announce 

http://tracker2.istole.it:60500/announce 

http://tracker.deluxebits.to:3552/announce 

udp://coppersurfer.tk:6969/announce 

udp://tracker.prq.to/announce

udp://tracker.btzoo.eu:80/announce 

http://tracker.torrentbox.com:2710/announce 

http://tracker.hexagon.cc:2710/announce 

http://tracker.torrent.to:2710/announce 

http://axxo.sladinki007.net:6500/announce 

http://www.torrent-downloads.to:2710/announce 

udp://9.rarbg.com:2710/announce 

http://inferno.demonoid.com:3400/announce 

http://tracker.prq.to/announce 

http://tracker.torrenty.org:6969/announce 

http://tpb.tracker.thepiratebay.org/announce 

http://t.ppnow.net:2710/announce 

http://tracker.paradise-tracker.com:12000/announce 

http://www.torrentvideos.com:6969/announce 

http://tracker.sladinki007.net:6500/announce 

http://tracker.bitebbs.com:6969/announce 

udp://tracker.opentrackr.org:1337/announce 

udp://tracker.openbittorrent.com:80 

udp://tracker.publicbt.com:80 

udp://tracker.istole.it:80 

udp://tracker.btzoo.eu:80/announce 

http://opensharing.org:2710/announce 

udp://open.demonii.com:1337/announce 

http://announce.torrentsmd.com:8080/announce.php 

http://announce.torrentsmd.com:6969/announce 

http://bt.careland.com.cn:6969/announce 

http://i.bandito.org/announce 

http://bttrack.9you.com/announce 

udp://coppersurfer.tk:6969/announce 

http://tracker.pubt.net:2710/announce 

udp://glotorrents.pw:6969/announce 

udp://tracker.pomf.se/announce 

udp://9.rarbg.com:2710/announce 

udp://tracker.istole.it:80/announce 

udp://tracker.publicbt.com:80/announce 

udp://open.demonii.com:1337/announce 

udp://p4p.arenabg.ch:1337/announce 

udp://tracker.openbittorrent.com:80/announce 

udp://tracker4.piratux.com:6969/announce 

udp://open.demonii.com:1337/announce 

http://bt1.the9.com:6969/announce 

http://tracker.ydy.com:102/announce 

udp://tracker.blackunicorn.xyz:6969/announce 

udp://inferno.demonoid.ph:3389/announce 

http://eztv.sladinki007.eu:60500/announce 

http://moviesb4time.biz/announce.php 

http://tracker.deadfrog.us:42426/announce 

http://mpggalaxy.mine.nu:6969/announce 

http://www.sumotracker.org/announce 

http://9.rarbg.com:2710/announce 

http://mgtracker.org:2710/announce 

http://announce.torrentsmd.com:6969/announce 

http://bt.careland.com.cn:6969/announce 

http://explodie.org:6969/announce 

http://tracker1.wasabii.com.tw:6969/announce

 http://tracker.best-torrents.net:6969/announce 

http://tracker.tfile.me/announce 

udp://tracker.publicbt.com:80/announce 

http://tracker.torrenty.org:6969/announce 

udp://tracker.openbittorrent.com:80/announce 

udp://9.rarbg.com:2710/announce 

udp://explodie.org:6969/announce 

udp://coppersurfer.tk:6969/announce 

udp://tracker.openbittorrent.com:80/announce 

udp://11.rarbg.com:80/announce 

udp://tracker.openbittorrent.com:80 

udp://exodus.desync.com:6969/announce 

udp://tracker.istole.it:80/announce 

udp://tracker.openbittorrent.com:80/announce 

http://denis.stalker.h3q.com:6969/announce 

udp://9.rarbg.me:2710/announce

udp://9.rarbg.com:2710/announce

udp://explodie.org:6969/announce

udp://mgtracker.org:2710/announce

udp://9.rarbg.com:2710/announce

udp://9.rarbg.me:2710/announce

udp://coppersurfer.tk:6969/announce

udp://open.demonii.com:1337/announce

udp://tracker.openbittorrent.com:80/announce

udp://11.rarbg.com:80/announce

udp://tracker.openbittorrent.com:80/

udp://tracker.openbittorrent.com:80/announce

udp://9.rarbg.com:2710/announce

udp://open.acgtracker.com:1096/announce

http://open.acgtracker.com:1096/announce

udp://tracker.aletorrenty.pl:2710/announce

http://tracker.aletorrenty.pl:2710/announce

udp://anisaishuu.de:2710/announce

http://anisaishuu.de:2710/announce

udp://p4p.arenabg.com:1337/announce

udp://p4p.arenabg.com:1337

udp://tracker.dutchtracking.com:80/announce

http://tracker.dutchtracking.com:80/announce

udp://tracker.dutchtracking.nl:80/announce

http://tracker.dutchtracking.nl:80/announce
udp://tracker.ex.ua:80/announce

http://tracker.ex.ua:80/announce

udp://explodie.org:6969/announce

udp://explodie.org:6969/announce

udp://torrent.gresille.org:80/announce

udp://torrent.gresille.org:80/announce

udp://tracker.kicks-ass.net:80/announce

http://tracker.kicks-ass.net:80/announce

udp://retracker.krs-ix.ru:80/announce

http://retracker.krs-ix.ru:80/announce

udp://megapeer.org:6969/announce

http://megapeer.org:6969/announce

http://mgtracker.org:2710/announce

http://mgtracker.org:2710/announce

udp://tracker.ohys.net:80/announce

http://tracker.ohys.net:80/announce

udp://tracker.opentrackr.org:1337/announce

udp://tracker.opentrackr.org:1337/announce

udp://tracker4.piratux.com:6969/announce

http://tracker4.piratux.com:6969/announce

udp://tracker.pubt.net:2710/announce

http://tracker.pubt.net:2710/announce

udp://pubt.net:2710/announce

http://pubt.net:2710/announce

udp://9.rarbg.com:80/announce

udp://9.rarbg.com:2710/announce

udp://tracker.skyts.net:6969/announce

http://tracker.skyts.net:6969/announce

udp://retracker.telecom.kz:80/announce

http://retracker.telecom.kz:80/announce

udp://tracker.tiny-vps.com:6969/announce

http://tracker.tiny-vps.com:6969/announce

udp://tracker2.torrentino.com:80/announce

http://tracker2.torrentino.com:80/announce

udp://torrentsmd.com:6969/announce

udp://torrentsmd.com:8080/announce

http://torrentsmd.com:6969/announce

http://torrentsmd.com:8080/announce

udp://tracker.tricitytorrents.com:2710/announce

http://tracker.tricitytorrents.com:2710/announce

udp://www.wareztorrent.com:80/announce

udp://www.wareztorrent.com:6969/announce

http://www.wareztorrent.com:80/announce

http://www.wareztorrent.com:6969/announce

udp://tracker1.infohash.org:80/announce

udp://tracker1.infohash.org:6969/announce

http://tracker1.infohash.org:80/announce

http://tracker1.infohash.org:6969/announce

udp://tracker4.infohash.org:80/announce

udp://tracker4.infohash.org:6969/announce

http://tracker4.infohash.org:80/announce

http://tracker4.infohash.org:6969/announce

udp://91.218.230.81:80/announce

udp://91.218.230.81:6969/announce

http://91.218.230.81:80/announce

http://91.218.230.81:6969/announce

http://mgtracker.org:2710/announce

http://tracker.tfile.me/announce

udp://9.rarbg.me:2710/announce

udp://coppersurfer.tk:6969/announce

udp://open.demonii.com:1337/announce

udp://tracker.openbittorrent.com:80/announce

udp://p4p.arenabg.ch:1337

udp://p4p.arenabg.com:1337

http://tracker.aletorrenty.pl:2710/announce

udp://torrent.gresille.org:80/announce

udp://glotorrents.pw:6969/announce

udp://www.eddie4.nl:6969/announce

udp://tracker.leechers-paradise.org:6969

udp://9.rarbg.com:2710/announce

udp://explodie.org:6969/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://11.rarbg.com/announce

udp://9.rarbg.com:2710/announce

http://bt.careland.com.cn:6969/announce

http://mgtracker.org:2710/announce

http://tracker.tfile.me/announce

udp://9.rarbg.com:2710/announce

udp://9.rarbg.me:2710/announce

udp://coppersurfer.tk:6969/announce

udp://open.demonii.com:1337/announce

udp://tracker.openbittorrent.com:80/announce

udp://11.rarbg.com:80/announce

udp://9.rarbg.com:2710/announce

http://bt.careland.com.cn:6969/announce

http://mgtracker.org:2710/announce

http://tracker.tfile.me/announce

udp://9.rarbg.me:2710/announce

udp://coppersurfer.tk:6969/announce

udp://open.demonii.com:1337/announce

udp://tracker.openbittorrent.com:80/announce

udp://p4p.arenabg.ch:1337

udp://p4p.arenabg.com:1337

udp://torrent.gresille.org:80/announce

udp://glotorrents.pw:6969/announce

udp://www.eddie4.nl:6969/announce

udp://tracker.leechers-paradise.org:6969

udp://9.rarbg.com:2710/announce

http://tracker.coppersurfer.tk:6969/announce

udp://11.rarbg.com/announce

udp://tracker.openbittorrent.com:80/announce

udp://torrent.gresille.org:80/announce

udp://glotorrents.pw:6969/announce

udp://www.eddie4.nl:6969/announce

udp://tracker.leechers-paradise.org:6969

udp://9.rarbg.com:2710/announce

udp://explodie.org:6969/announce

http://mgtracker.org:2710/announce

http://tracker.tfile.me/announce

udp://9.rarbg.me:2710/announce

http://tracker.coppersurfer.tk:6969/announce

udp://9.rarbg.com:2710/announce

udp://coppersurfer.tk:6969/announce

udp://open.demonii.com:1337/announce

udp://11.rarbg.com/announce

udp://tracker.openbittorrent.com:80/announce

udp://tracker.openbittorrent.com:80/announce

udp://9.rarbg.me:2710/announce

udp://11.rarbg.me:80/announce

udp://9.rarbg.com:2710/announce

udp://tracker.openbittorrent.com:80/announce
udp://tracker.openbittorrent.com:80

udp://tracker.openbittorrent.com:80/announce
udp://open.demonii.com:1337/announce

udp://coppersurfer.tk:6969/announce

udp://tracker.openbittorrent.com:80/announce

udp://tracker.openbittorrent.com:80/announce

udp://coppersurfer.tk:6969/announce

udp://tracker.openbittorrent.com:80/announce
udp://9.rarbg.com:2710/announce

udp://9.rarbg.me:2710/announce

udp://tracker.openbittorrent.com:80/announce

udp://9.rarbg.me:2710/announce

udp://9.rarbg.com:2710/announce

udp://tracker.openbittorrent.com:80/announce

udp://11.rarbg.me:80/announce

udp://tracker.openbittorrent.com:80/announce

udp://9.rarbg.com:2710/announce

http://explodie.org:6969/announce

udp://coppersurfer.tk:6969/announce

udp://tracker.openbittorrent.com:80/announce
udp://11.rarbg.com:80/announce

udp://tracker.openbittorrent.com:80

udp://tracker.yify-torrents.com/announce

udp://p4p.arenabg.com:1337/announce

http://bttracker.crunchbanglinux.org:6969/announce

http://tracker.yify-torrents.com/announce

udp://p4p.arenabg.ch:1337

http://tracker.aletorrenty.pl:2710/announce

http://torrent.gresille.org:80/announce

udp://glotorrents.pw:6969/announce

udp://tracker.trackerfix.com:80/announce

udp://www.eddie4.nl:6969/announce

udp://tracker.leechers-paradise.org:6969

http://retracker.kld.ru:2710/announce

udp://9.rarbg.com:2710/announce

http://bt.careland.com.cn:6969/announce

http://explodie.org:6969/announce

http://mgtracker.org:2710/announce

http://tracker.best-torrents.net:6969/announce

http://tracker.tfile.me/announce

http://tracker.torrenty.org:6969/announce

http://tracker1.wasabii.com.tw:6969/announce

udp://9.rarbg.me:2710/announce

udp://tracker.btzoo.eu:80/announce

http://pow7.com/announce

http://tracker.novalayer.org:6969/announce

http://193.107.16.156:2710/announce

http://cpleft.com:2710/announce

http://retracker.hotplug.ru:2710/announce

http://retracker.kld.ru/announce

http://tracker.coppersurfer.tk:6969/announce

http://inferno.demonoid.me:3414/announce

http://announce.torrentsmd.com:6969/announce

http://9.rarbg.com:2710/announce

udp://coppersurfer.tk:6969/announce

udp://exodus.desync.com:6969/announce

udp://open.demonii.com:1337/announce

udp://tracker.prq.to/announce

http://exodus.desync.com/announce

http://ipv4.tracker.harry.lu/announce

http://tracker.torrentbay.to:6969/announce

udp://11.rarbg.com/announce

udp://tracker.1337x.org:80/announce

udp://tracker.istole.it:80/announce

udp://tracker.ccc.de:80/announce

udp://fr33dom.h33t.com:3310/announce

udp://tracker.openbittorrent.com:80/announce

udp://tracker.publicbt.com:80/announce

http://tracker.coppersurfer.tk:6969/announce

http://tracker.opentrackr.org:1337/announce

udp://tracker.zer0day.to:1337/announce

udp://tracker.torrent.eu.org:451/announce

udp://tracker.leechers-paradise.org:6969/announce

http://p4p.arenabg.com:1337/announce

udp://tracker.internetwarriors.net:1337/announce

udp://tracker.zer0day.to:1337/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://coppersurfer.tk:6969/announce

**Comment by petesimon** [comment]
many trackers are written two or more times.

and most of those trackers are already in the lists
https://ngosang.github.io/trackerslist/

**Comment by ngosang** [comment]
Added only 2 of them. The others were already in the list or dead. Thank you!

**Comment by petesimon** [comment]
udp://tracker.cypherpunks.ru:6969/announce

is working for me right now.

**Comment by ngosang** [comment]
> udp://tracker.cypherpunks.ru:6969/announce

Not from here
