### ISSUE TITLE
new chihaya tracker

### ISSUE THREAD

**Issue by SolSoCoG** [ngosang/trackerslist#229]
I've started a chihaya tracker here:

udp://chihaya.de:6969/announce

It's in the newTrackon stable list with 95%+ uptime (which is tbh not hard, started it a day ago).

Intending to keep it going as long as I possibly can, with at max 8 2min interruptions a year for important patches to the tracker or OS.

**Comment by ngosang** [comment]
Added, thank you! Expect high traffic in the following days.
