### ISSUE TITLE
add trackers

### ISSUE THREAD

**Issue by petesimon** [ngosang/trackerslist#231]
udp://bt.rutor.org:2710/announce
http://bt2.rutracker.cc:80
http://tracker.dler.org:6969/announce

**Comment by ngosang** [comment]
Added `http://tracker.dler.org:6969/announce`

I'm getting errors in the others:
* udp://bt.rutor.org:2710/announce => timed out
* http://bt2.rutracker.cc:80/announce => HTTP Error 404: Not Found

**Comment by petesimon** [comment]
> http://tracker.dler.org:6969/announce

I've also seen `utp://tracker.dler.org:6969/announce`

**Comment by ngosang** [comment]
both are in the list
