### ISSUE TITLE
new https trackers

### ISSUE THREAD

**Issue by jamiew0w** [ngosang/trackerslist#232]
https://t1.leech.ie/announce
https://t2.leech.ie/announce
https://t3.leech.ie/announce

Thanks!

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by jamiew0w** [comment]
added http & udp

http://t1.leech.ie:80/announce
udp://t1.leech.ie:6969/announce

http://t2.leech.ie:80/announce
udp://t2.leech.ie:6969/announce

http://t3.leech.ie:80/announce
udp://t3.leech.ie:6969/announce

**Comment by ngosang** [comment]
Added. Thank you!
