### ISSUE TITLE
Remove tracker.lelux.fi from IP list

### ISSUE THREAD

**Issue by theel0ja** [ngosang/trackerslist#238]

**Comment by rautamiekka** [comment]
Why, though ?

**Comment by theel0ja** [comment]
@rautamiekka I do not have my own IP blocks, so whoever gets the IP after me will get ton of junk traffic

**Comment by ngosang** [comment]
The IP list is discouraged and is used by few people. This problem exists in other trackers as well, but I don't want to start applying complex rules. It is possible that you will get a block of IPs in the future and I don't remove the exception.
