### ISSUE TITLE
IP addresses trackers (hm?)

### ISSUE THREAD

**Issue by petesimon** [ngosang/trackerslist#240]
got an automated way to check all these IP addresses?

`http://104.28.1.30:8080/announce

http://104.28.16.69/announce

http://107.150.14.110:6969/announce

http://109.121.134.121:1337/announce

http://114.55.113.60:6969/announce

http://125.227.35.196:6969/announce

http://128.199.70.66:5944/announce

http://157.7.202.64:8080/announce

http://158.69.146.212:7777/announce

http://173.254.204.71:1096/announce

http://178.175.143.27/announce

http://178.33.73.26:2710/announce

http://182.176.139.129:6969/announce

http://185.5.97.139:8089/announce

http://188.165.253.109:1337/announce

http://194.106.216.222/announce

http://195.123.209.37:1337/announce

http://210.244.71.25:6969/announce

http://210.244.71.26:6969/announce

http://213.159.215.198:6970/announce

http://213.163.67.56:1337/announce

http://37.19.5.139:6969/announce

http://37.19.5.155:6881/announce

http://46.4.109.148:6969/announce

http://5.79.249.77:6969/announce

http://5.79.83.193:2710/announce

http://51.254.244.161:6969/announce

http://59.36.96.77:6969/announce

http://74.82.52.209:6969/announce

http://80.246.243.18:6969/announce

http://81.200.2.231/announce

http://85.17.19.180/announce

http://87.248.186.252:8080/announce

http://87.253.152.137/announce

http://91.216.110.47/announce

http://91.217.91.21:3218/announce

http://91.218.230.81:6969/announce

http://93.92.64.5/announce`

**Comment by ngosang** [comment]
In qBittorrent, if you add all of them to a working torrent, you can see if the tracker is working or now.

**Comment by petesimon** [comment]
okay. but i don't use qBittorrent, so I use Transmission. thanks.

**Comment by duramato** [comment]
You can also do the same in transmission
