### ISSUE TITLE
added udp to three trackers

### ISSUE THREAD

**Issue by jamiew0w** [ngosang/trackerslist#251]
```
udp://t1.leech.ie:1337/announce
udp://t2.leech.ie:1337/announce
udp://t3.leech.ie:1337/announce
```

Thanks as always!

edit;

Please also deprecate the following three as I can no longer support them:

```
https://t1.leech.ie:443/announce
https://t2.leech.ie:443/announce
https://t3.leech.ie:443/announce
```

**Comment by ngosang** [comment]
Please, be more explicit. I receive more than 250 emails a day..
I have to keep upd and http, and remove https?

**Comment by jamiew0w** [comment]
That's correct.

**Comment by ngosang** [comment]
Added
