### ISSUE TITLE
some public trackers

### ISSUE THREAD

**Issue by petesimon** [ngosang/trackerslist#253]
got these trackers from this torrent 89bc93650e0af60c6b35064061f37b2a197d51ed on nyaa index website.

`i don't like markdown. it's no good for URL text`

http://nyaa.tracker.wf:7777/announce

http://tracker.anirena.com:80/announce

http://open.trackerlist.xyz:80/announce

http://tracker.vanitycore.co:6969/announce

**Comment by ngosang** [comment]
Added:
http://open.trackerlist.xyz:80/announce
http://tracker.vanitycore.co:6969/announce

Rejected because they only allow registered torrents:
http://nyaa.tracker.wf:7777/announce
http://tracker.anirena.com:80/announce

Thank you!
