### ISSUE TITLE
What time(s) do your trackers lists update?

### ISSUE THREAD

**Issue by styromaniac** [ngosang/trackerslist#255]
6:00pm Eastern Daylight Time (GMT-4)?

I can have cron set to download one of your lists ASAP.

This would be good to know the time(s).

**Comment by ngosang** [comment]
Every at 00:00 UTC/GMT +1 the process starts. It takes ~10 min so I recommend you to download the list one hour after that.
You can see the update time in your timezone. See the commit dates => https://github.com/ngosang/trackerslist/commits/master

**Comment by styromaniac** [comment]
I'm a little confused, because it seems there's an hour difference between 00:00 UTC and 00:00 GMT+1. Am I correct?

**Comment by ngosang** [comment]
yes, you are

**Comment by styromaniac** [comment]
😕 Could you give the recommended time again so I'm not confused?

**Comment by styromaniac** [comment]
I just need it clarified, because it seems you've given me two different time zones. Or... I'll wait until an app detects a change to a file.

**Comment by Tmp341** [comment]
I think he meant UTC+1/GMT+1. @styromaniac

**Comment by styromaniac** [comment]
> I think he meant UTC+1/GMT+1. @styromaniac

Thank you!
