### ISSUE TITLE
Finding More websocket trackers WebTorrent

### ISSUE THREAD

**Issue by C0nw0nk** [ngosang/trackerslist#257]
Currently you only have the following tracker.

https://ngosang.github.io/trackerslist/trackers_all_ws.txt

These are the others.

```
wss://tracker.btorrent.xyz/announce
wss://tracker.openwebtorrent.com/announce
wss://tracker.fastcast.nz/announce
```

As the Webtorrent website will also show you https://webtorrent.io/docs

Can we please find some more web socket trackers.

Also this tracker `https://tracker.sloppyta.co:443/announce`

Needs to be added to the unsecured HTTP list because it accepts both HTTPS and HTTP connections as seen here.

```
http://tracker.sloppyta.co/announce
https://tracker.sloppyta.co:443/announce
```

**Comment by C0nw0nk** [comment]
https://tracker.btorrent.xyz/stats
https://tracker.sloppyta.co/stats

**Comment by C0nw0nk** [comment]
Another HTTPS tracker to be added.

```
https://tracker.btorrent.xyz/announce
```

**Comment by C0nw0nk** [comment]
Might be worth testing but existing trackers in your HTTP and HTTPS lists might also accept websocket connections worth testing to see if more can be found that way :)

**Comment by ngosang** [comment]
Most of them are not working. That's the reason why they are not in the list.

>wss://tracker.btorrent.xyz/announce

'websocket._exceptions.WebSocketBadStatusException'>: Handshake status 403 Forbidden

> wss://tracker.openwebtorrent.com/announce

'websocket._exceptions.WebSocketConnectionClosedException'>: Connection is already closed.

> wss://tracker.fastcast.nz/announce

[Errno -2] Name or service not known

> https://tracker.btorrent.xyz/announce 

<class 'urllib.error.HTTPError'>: HTTP Error 403: Forbidden


Added:
>http://tracker.sloppyta.co:80/announce
https://tracker.sloppyta.co:443/announce

**Comment by C0nw0nk** [comment]
@ngosang Thanks for adding those.

So with the existing trackers in the HTTP and HTTPS list have you tested to see if any of them support websocket connections.

**Comment by C0nw0nk** [comment]
@ngosang Also Peertube has websocket trackers.

```
wss://video.blender.org/tracker/socket
wss://peertube.live/tracker/socket
wss://open.tube/tracker/socket
```

https://github.com/Chocobozzz/PeerTube
https://www.reddit.com/r/PeerTube/

**Comment by ngosang** [comment]
> So with the existing trackers in the HTTP and HTTPS list have you tested to see if any of them support websocket connections.

I did. None of them work with wss.
Webtorrent is not quite popular. After this PR is merged https://github.com/arvidn/libtorrent/issues/223 will be supported by some popular torrent clients like qBittorrent and Deluge. But right now it's just an experiment.

> wss://video.blender.org:443/tracker/socket
wss://peertube.live:443/tracker/socket
wss://open.tube:443/tracker/socket

Added. Thank you!

**Comment by C0nw0nk** [comment]
@ngosang You are welcome the links i posted should help you find more when you look at any peertube website in browser connection console you can see the websocket tracker connection watching a video :)

Also wow that issue is from 2015 its taking a long time to impliment :'(

**Comment by C0nw0nk** [comment]
@ngosang Found more.

```
ws://tracker.files.fm:7072/announce
wss://tracker.files.fm:7073/announce
ws://tracker.btsync.cf:233/announce
ws://tracker.btsync.cf:2710/announce
ws://tracker.btsync.cf:6969/announce
ws://hub.bugout.link/announce
wss://hub.bugout.link/announce
ws://tracker.lab.vvc.niif.hu/announce
wss://tracker.lab.vvc.niif.hu/announce
```

Need help finding more :) Lets build this list!

**Comment by C0nw0nk** [comment]
@ngosang More.

```
ws://track.file.pizza/announce
wss://track.file.pizza/announce
```

**Comment by ngosang** [comment]
> ws://tracker.btsync.cf:233/announce
ws://tracker.btsync.cf:2710/announce

Not working. Added the others. Thank you!
