### ISSUE TITLE
New trackers

### ISSUE THREAD

**Issue by Cter666** [ngosang/trackerslist#260]
Here is the link:
https://zooqle.com/api/json_trackers.php?txt=1&limit=100

Can you add these trackers?

**Comment by tim1103** [comment]
```text
udp://tracker.zer0day.to:1337/announce
udp://tracker.internetwarriors.net:1337/announce
```
This is unusable Trackers?

**Comment by Cter666** [comment]
> ```
> udp://tracker.zer0day.to:1337/announce
> udp://tracker.internetwarriors.net:1337/announce
> ```
> 
> This is unusable Trackers?
I'am sorry.That's really unusable now.
The trackers is Partially usable in the link "https://zooqle.com/api/json_trackers.php?txt=1&limit=100".That's public,maybe it will shutdown anytime.

**Comment by kompowiec** [comment]
```
wss://tube.privacytools.io:443/tracker/socket
https://tube.privacytools.io/tracker/announce
```

**Comment by ngosang** [comment]
Added most of them. Thank you!
