### ISSUE TITLE
Use jsdelivr mirror for poor network region

### ISSUE THREAD

**Issue by ShallowAi** [ngosang/trackerslist#261]
### In some region, github content was loaded slower than Dial-up Internet access.

jsdelivr provide free CDN for github content. add an jsdelivr link as mirror2 in README.md can improve speed.

Base Directory: https://cdn.jsdelivr.net/gh/ngosang/trackerslist/

trackers_best (20 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_best.txt
trackers_all (94 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_all.txt
trackers_all_udp (50 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_all_udp.txt
trackers_all_http (29 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_all_http.txt
trackers_all_https (15 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_all_https.txt
trackers_all_ws (14 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_all_ws.txt
trackers_best_ip (16 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_best_ip.txt
trackers_all_ip (64 trackers) => https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_all_ip.txt

**Comment by ngosang** [comment]
Added. Thank you!
