### ISSUE TITLE
not working trackers in trackers_best.txt

### ISSUE THREAD

**Issue by mrx23dot** [ngosang/trackerslist#262]
http://ipv6-publictracker.zooki.xyz:6969/announce	hostname not found	updating...	0	0	0	
http://t.nyaatracker.com:80/announce	Failure: torrent does not exist	28m 23s	0	0	0	
http://torrent.nwps.ws:80/announce	HTTP Error 404	28m 24s	0	0	0	
http://tracker.ipv6tracker.ru:80/announce	hostname not found	updating...	0	0	0	
http://tracker4.itzmx.com:2710/announce	offline (timed out)	5s	0	0	0	
udp://exodus.desync.com:6969	Connection timed out.	20m 3s	0	0	0	
udp://tracker.internetwarriors.net:1337	Connection timed out.	18m 59s	0	0	0	
udp://tracker.leechers-paradise.org:6969	Connection timed out.	19m 0s	0	0	0	
udp://tracker.trackerfix.com:81/announce	Connection timed out.	1m 0s	0	0	0

**Comment by ngosang** [comment]
All those trackers are working from here. It looks like your ISP is blocking them. Change the DNS or use VPN.
