### ISSUE TITLE
2 new Third-party tools

### ISSUE THREAD

**Issue by Jorman** [ngosang/trackerslist#267]
Hi, I created 2 script that use your list and inject trackers inside the client, all can works with sonarr/radarr with automatic way or manually from cli. Hope someone can use these
https://github.com/Jorman/Scripts/blob/master/AddTransmissionTrackers.sh
https://github.com/Jorman/Scripts/blob/master/AddqBittorrentTrackers.sh

For now only for transmission and qbittorrent

J

**Comment by ngosang** [comment]
Added. Thank you!
