### ISSUE TITLE
New tracker

### ISSUE THREAD

**Issue by tryzombie501** [ngosang/trackerslist#27]
So i tried to get a tracker added to the list before and it was dead, Turns out it just moved home its now at 
http://tracker.obbuh.com/

its a php http tracker.

**Comment by tryzombie501** [comment]
Seems like it really needs some help
stats are dead but it seems to work and with a bit of help we can help this tracker out.
http://tracker.obbuh.com/scrape?stats

**Comment by ngosang** [comment]
It's not enough popular. Sorry.
