### ISSUE TITLE
the newest trackers from rarbg.to

### ISSUE THREAD

**Issue by NB-Dragon** [ngosang/trackerslist#279]
I get this from [rarbg.to](https://rarbg.to/) today, and which are different from yours. Maybe is it the newest trackers. Please check.
```
udp://9.rarbg.to:2730/announce
udp://9.rarbg.me:2820/announce

udp://151.80.120.112:2730/announce
udp://151.80.120.115:2820/announce
```

**Comment by ngosang** [comment]
I don't want to add duplicate trackers. I'm using the old ones that have been working for years.
> udp://9.rarbg.to:2710/announce
udp://9.rarbg.me:2710/announce
