### ISSUE TITLE
Compare your list to the newtrackon.com

### ISSUE THREAD

**Issue by JonnyRedHed** [ngosang/trackerslist#28]
This site: https://newtrackon.com

Your list shows best 20 and then top 50. What factors go into deciding your best 20.  The newtrackon.com just shows uptime 95% and 100% uptime as a gauge of the tracker.

Do you use other factors in your best 20 list, like known issues or malicious trackers etc.  'Banned Trackers list' found here for example: 

https://extratorrent.cc/forum/topic/7621/suggested+public+trackers.html?page=4

https://katcr.co/show/community/index.php/topic,483.0.html

**Comment by lewisje** [comment]
I believe that newTrackon actually pulls down the "all" list and checks the trackers therein.

**Comment by JonnyRedHed** [comment]
Factoring in bad trackers seems like a good idea if not already done.

**Comment by chovy** [comment]
Any chance we can get some websocket trackers? ie: (`ws://` and `wss://`)

**Comment by ngosang** [comment]
> This site: https://newtrackon.com
Your list shows best 20 and then top 50. What factors go into deciding your best 20. The newtrackon.com just shows uptime 95% and 100% uptime as a gauge of the tracker.
Do you use other factors in your best 20 list, like known issues or malicious trackers etc. 'Banned Trackers list' found here for example:
https://extratorrent.cc/forum/topic/7621/suggested+public+trackers.html?page=4
https://katcr.co/show/community/index.php/topic,483.0.html

I'm going to add several trackers from https://newtrackon.com when I have some free time.
There are several criteria for sorting. My bot query the trackers with popular torrents and checks which trackers are returning more seeds/peers, latency, reliability, offline time...

> Any chance we can get some websocket trackers? ie: (ws:// and wss://)

Do you have any?

**Comment by lewisje** [comment]
What torrent client even uses the `ws:` or `wss:` schemes?

**Comment by chovy** [comment]
Yeah those are the only three I could find too. webtorrent.io uses websocket trackers.

**Comment by ngosang** [comment]
> What torrent client even uses the ws: or wss: schemes?

It's interesting. I will add that trackers but I have to do the code implementation first.

**Comment by ngosang** [comment]
Implemented WS/WSS support.
