### ISSUE TITLE
New HTTPS Tracker

### ISSUE THREAD

**Issue by AzukaChan** [ngosang/trackerslist#281]
Tested and working
`https://bitstorm.azukachan.com/` - Tracker for torrents
`https://bitstorm.azukachan.com/publicindex.php` - Public Web Index (Hash, DL, UP)

**Comment by ngosang** [comment]
Not working from here. Maybe they are supporting only registered torrents.

**Comment by AzukaChan** [comment]
@ngosang How are you testing the connection?
I have added the tracker to 3 torrents as well as made 1 fresh torrent of my own, all successfully registering the tracker in my torrent client.
![tracker](https://user-images.githubusercontent.com/42724187/98976430-10df6d00-2563-11eb-97d6-d9b387736b33.PNG)

**Comment by ngosang** [comment]
https://bitstorm.azukachan.com/announce

**Comment by AzukaChan** [comment]
No need for the `/announce` at the end there.
`https://bitstorm.azukachan.com/` - this is the link for the tracker.

**Comment by ngosang** [comment]
That's working but it's not standard. https://wiki.theory.org/BitTorrentSpecification#Tracker_.27scrape.27_Convention

**Comment by AzukaChan** [comment]
Its been setup like this for the past month give or take (doesnt get much use at the moment) so I'm unlikely to change it while its working, at least for a while.

If it doesn't meet standards feel free to close this issue and I'll open another ticket once those changes have been made.

**Comment by txtsd** [comment]
If you fix it to work on `/announce`, it will get tracked on newtrackon.com too.

**Comment by AzukaChan** [comment]
I notice on the wiki it states:
`~http://example.com/announce.php  -> ~http://example.com/scrape.php`

Does this mean `/announce.php` is also acceptable?
If not will make some changes tonight and see if I can get it working on `/announce`

**Comment by ngosang** [comment]
It's down

**Comment by AzukaChan** [comment]
@ngosang Will be down for the next day or two; moving the server go a gigabit connection.
Was getting too much traffic too handle.

**Comment by ngosang** [comment]
I'm pretty sure you won't be able to handle the traffic using HTTPS. The next bottleneck will be the CPU. If you want to scale you need gigabit + opentrackr + udp. Anyway I will add it to the list when it's up.
