### ISSUE TITLE
Add tracker

### ISSUE THREAD

**Issue by zamanuhina** [ngosang/trackerslist#283]
Very popular tracker:
https://www.similarweb.com/website/rutracker.org/

```
http://bt3.t-ru.org/ann?magnet
```

**Comment by zamanuhina** [comment]
And maybe

```
http://xbtrutor.com:2710/announce
```

**Comment by ngosang** [comment]
Added => http://bt3.t-ru.org/ann?magnet
http://xbtrutor.com:2710/announce is for registered torrents only

Thank you!
