### ISSUE TITLE
Tracker banned

### ISSUE THREAD

**Issue by soulspark666** [ngosang/trackerslist#288]
The following tracker is banned on some site;
![Screenshot_2020-12-11_Tokyo_Toshokan_tokyotosho_irc_rizon_net_Submit_New_Torrent](https://user-images.githubusercontent.com/37495396/101978686-b95e1b00-3c4e-11eb-8aba-99df05ec6241.png)

> udp://explodie.org:6969/announce

**Comment by ngosang** [comment]
Thank you for reporting!
That tracker have been working fine for years. I can't find anything suspect so I'm going to keep it.
