### ISSUE TITLE
New Tracker

### ISSUE THREAD

**Issue by MoeKing** [ngosang/trackerslist#289]
http://tracker-cdn.moeking.me:2095/announce

**Comment by ihavenoid** [comment]
```udp://11.rarbg.com/announce 

udp://11.rarbg.com:80/announce 

udp://11.rarbg.me:80/announce```

**Comment by ngosang** [comment]
> http://tracker-cdn.moeking.me:2095/announce

Added, thank you!

@ihavenoid not working from here.
