### ISSUE TITLE
Popcorn Tracker, a new OpenTracker-based UDP tracker

### ISSUE THREAD

**Issue by lewisje** [ngosang/trackerslist#29]
`udp://public.popcorn-tracker.org:6969/announce`

[info](https://popcorn-tracker.org/)

[coverage by *TorrentFreak*](https://torrentfreak.com/popcorn-time-launches-new-bittorrent-tracker-fight-copyright-monopolies-161230/)

**Comment by ngosang** [comment]
@lewisje It's not working for me. Could you check?
