### ISSUE TITLE
New tracker wss://ws.peer.ooo

### ISSUE THREAD

**Issue by draeder** [ngosang/trackerslist#295]
wss://ws.peer.ooo

As a note: I also created a Heroku package to enable anyone to use their free-tier Heroku account to deploy the same tracker server under their own account: [https://github.com/draeder/p2p-tracker](https://github.com/draeder/p2p-tracker)

**Comment by draeder** [comment]
Looks like you're not interested in adding my tracker, so I'm closing this issue.

**Comment by ngosang** [comment]
Added. Thank you!
