### ISSUE TITLE
New Tracker

### ISSUE THREAD

**Issue by psharma04** [ngosang/trackerslist#299]
Personal tracker now ready to go public, already over 2000 active torrents at time of writing.

HTTP: http://tracker.nighthawk.pw:4201/announce
UDP: udp://tracker.nighthawk.pw:4201
WS: ws://tracker.nighthawk.pw:4201

SSL support for the HTTP and WS trackers is coming soon, I just need to get a reverse proxy set up.

Statistics: http://tracker.nighthawk.pw:4201/stats

**Comment by ngosang** [comment]
Added. Thank you!
You should expect high traffic in the following hours.

**Comment by psharma04** [comment]
We've moved the tracker to port 2052. 4201 will stay up for now, but ping times will be much better on 2052.

**Comment by psharma04** [comment]
So its now:
HTTP: http://tracker.nighthawk.pw:2052/announce
UDP: udp://tracker.nighthawk.pw:2052
WS: ws://tracker.nighthawk.pw:2052

**Comment by ngosang** [comment]
I think they are dead... :thinking:

**Comment by psharma04** [comment]
Looks like I misconfigured the DNS. Should work now!

**Comment by ngosang** [comment]
done
