### ISSUE TITLE
Trackers Tested Issues

### ISSUE THREAD

**Issue by Inysal** [ngosang/trackerslist#3]
udp://91.218.230.81:6969/announce   -Tracker reply has no peers field
http://bt2.careland.com.cn:6969/announce -Tracker offline (timed out)
http://tracker.mg64.net:6881/announce  -Tracker offline (timed out)
http://tracker.aletorrenty.pl:2710/announce -Tracker offline (timed out)
udp://tracker.mg64.net:6969/announce  -Connection timed out.

**Comment by ngosang** [comment]
http://tracker.aletorrenty.pl:2710/announce is down sometimes. If it's offline this night will be removed automatically.
Other trackers are working properly:
![](https://i.imgur.com/KZ6buL4.png)

Thanks for reporting.
