### ISSUE TITLE
Add TRACKER server

### ISSUE THREAD

**Issue by laoqijun** [ngosang/trackerslist#303]
I want to add a TRACKER server
http://tracker.xn--vzyr4p.top:80/announce
ws: //tracker.xn--vzyr4p.top: 80 / announce
UDP: //tracker.xn--vzyr4p.top: / announce
Can you agree?

**Comment by laoqijun** [comment]
http://tracker.xn--vzyr4p.top:80/announce

ws://tracker.xn--vzyr4p.top:80/announce

udp://tracker.xn--vzyr4p.top:80/announce

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by ngosang** [comment]
You should expect very high traffic soon.
