### ISSUE TITLE
OpenBitTorrent is alive?

### ISSUE THREAD

**Issue by andreymal** [ngosang/trackerslist#306]
I don't know what happened, but I found this note in Wikipedia:

>In 2020, the website was redirecting to Opentrackr, another torrent tracker. However a year later in January 2021, OpenBitTorrent came back online again with its own tracker and website.

udp://tracker.openbittorrent.com:6969 works fine for me today. Perhaps it can be returned to the list?

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by andreymal** [comment]
[Remove from blacklist?](https://github.com/ngosang/trackerslist/blob/master/blacklist.txt#L170)

**Comment by ngosang** [comment]
The tracker in the black list has the same domain but different port. I think is better to have only 1 in the tracker list.

**Comment by rautamiekka** [comment]
If the domain's identical but port differs, I'd have them in ascending order in the same group. I'm all for getting the max peers/seed, but if only the port differs, it's highly likely they're synced.
