### ISSUE TITLE
Adding tracker.breizh.pm

### ISSUE THREAD

**Issue by Br31zh** [ngosang/trackerslist#311]
Hello,

That’s my own tracker, now running since some months, but it’s better if it’s known and other people actually use it, it’s available in http and udp:

```
udp://tracker.breizh.pm:6969/announce
http://tracker.breizh.pm:6969/announce
```

It works in both IPv4 and IPv6 (I’ve seen #72): if you make your request in IPv4, you’ll only get IPv4 peers, and if you make your request in IPv6, you’ll only get IPv6 peers (and stats).

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by Br31zh** [comment]
Hello,

My tracker is behind the router of my FAI (in France, FAI give you their own router, called a box), and the tracker traffic makes it crash regularly. I don't have the motivation to buy and configure a proper router at the moment, so can you remove my tracker from the list?

Thank you.

**Comment by ngosang** [comment]
Done but I'm sure you will receive traffic for long time.

**Comment by Br31zh** [comment]
Probably, yes. But currently I’m on the edge, so if I don’t have more peers than now, it’ll be okay. It’s mainly to not have new users.

Thank you.
