### ISSUE TITLE
request for removal/modification of trackers

### ISSUE THREAD

**Issue by jamiew0w** [ngosang/trackerslist#319]
hello!

i'm changing my setup from this:

```
udp://t1.leech.ie:1337/announce
udp://t2.leech.ie:1337/announce
udp://t3.leech.ie:1337/announce
```

to just this:

```
udp://tracker.leech.ie:1337/announce
```

if possible could you remove t1/t2/t3 and instead add the new tracker? 
thanks again for your time!

**Comment by ngosang** [comment]
Changed. Thank you, nice tracker!
