### ISSUE TITLE
Add the Yggdrasil Network BitTorrent Tracker by Neil Alexander

### ISSUE THREAD

**Issue by styromaniac** [ngosang/trackerslist#321]
https://yggdrasil-network.github.io/services.html#bittorrent

The address to add is:
```
http://[300:7232:2b0e:d6e9:216:3eff:fe34:ec44]:6969/announce
```

It's alive and well, just like the developer himself.

**Comment by ngosang** [comment]
Sorry, we don't have IPv6 support yet. #72

**Comment by styromaniac** [comment]
It works without IPv6 internet connections.

**Comment by ngosang** [comment]
No, your server doesn't have IPv4 connectivity.
Tested => http://tracker.y.neilalexander.eu:6969/announce
