### ISSUE TITLE
More Trackers To Review

### ISSUE THREAD

**Issue by Elshara** [ngosang/trackerslist#328]
[Torrent Master Tracker List.txt](https://github.com/ngosang/trackerslist/files/6963482/Torrent.Master.Tracker.List.txt)
Check to see if these trackers work. I've compiled these in real time from Jackett, and all of its supported torrent sites across the web.

**Comment by torres3490** [comment]
thank you will try

**Comment by ngosang** [comment]
Added 10 new trackers. Thank you!

**Comment by Elshara** [comment]
Hello,
I wanted to update this issue.
I have some more trackers (not duplicates of the original file) you can review if you like.
Hope this helps.
[Trackers Continued.txt](https://github.com/ngosang/trackerslist/files/7450991/Trackers.Continued.txt)

**Comment by ngosang** [comment]
Added few of them
