### ISSUE TITLE
My public tracker

### ISSUE THREAD

**Issue by HooKedOne** [ngosang/trackerslist#33]
https://open.kickasstracker.com:443/announce

**Comment by tryzombie501** [comment]
Welcome to the tracker family :D.

The only way for these trackers to be useful is if people share them and the more trackers the better so here i started one too its very a simple sometimes stats don't display(Trying to fix that now) but it works.

for utorrent it must be added like so
http://185.61.138.106:80/

**Comment by ngosang** [comment]
Added
