### ISSUE TITLE
Open tracker: Achilles

### ISSUE THREAD

**Issue by virtadpt** [ngosang/trackerslist#331]
I've had an open tracker running for a while.  If anybody thinks it might be useful, please add it to the list: https://achilles.virtadpt.net/announce.php

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by virtadpt** [comment]
Thank you very much!

**Comment by virtadpt** [comment]
Hi.  Could you please remove Achilles from the list?  I just got shut down by my service provider because all the activity was messing with the server it was on.

Sorry, everybody.
