### ISSUE TITLE
Remove Pomf tracker from blacklist.txt

### ISSUE THREAD

**Issue by nokonoko** [ngosang/trackerslist#338]
Regarding the Pomf tracker(s) in the blacklist, as of today these no longer mirror to those other trackers but instead is it's own tracker again. So I'd suggest removing them from the blacklist.

udp://tracker.pomf.se:80/announce # duplicate of udp://tracker.openbittorrent.com:80/announce
udp://sugoi.pomf.se:80/announce # duplicate of udp://tracker.opentrackr.org:1337/announce

**Comment by ngosang** [comment]
Both are down

**Comment by nokonoko** [comment]
Heh, it's back up again. Instantly tracking around 500,000+ torrents sunk it temporarily, tweaked a bit and should be better now.

**Comment by ngosang** [comment]
Done, thank you!
