### ISSUE TITLE
TCP tracker online again (gbitt.info)

### ISSUE THREAD

**Issue by Power2All** [ngosang/trackerslist#344]
Hi, just want to let you know that the Gbitt.info tracker is online again.
After a lot of pondering and having a memory issue, I kind of fixed it as it should.
UDP implementation will be coded again after the TCP server is deemed stable.
Just so you know, it's right now in "beta" mode, as I did a total rewrite of the core.

**Comment by Power2All** [comment]
Applied a fix, NewTrackOn works with the new back-end code as expected, and going up again in uptime.
UDP tracker implementation is going to be worked on this week.

**Comment by Power2All** [comment]
UDP implemention done.
I noticed http://tracker-udp.gbitt.info is not in the list, could you please add this @ngosang ?
Thanks !

**Comment by ngosang** [comment]
```
http://tracker.gbitt.info:80/announce
udp://tracker-udp.gbitt.info:80/announce
```

udp://tracker.gbitt.info:80/announce is removed because it's the same as udp://tracker-udp.gbitt.info:80/announce
I will list only one of them. Which one do you prefer?

**Comment by Power2All** [comment]
Separate them, I'm enabling Cloudflare again for the HTTP one, since Cloudflare supports KeepAlive for the connections, and diminish the load on my HTTP part of the tracker.
tracker-udp.gbitt.info will be specifically used for UDP connections.

**Comment by ngosang** [comment]
Done
