### ISSUE TITLE
Looks like the trackers_all_ip does not contains all IP addresses if the domain name has multiple IPs

### ISSUE THREAD

**Issue by larrychannon** [ngosang/trackerslist#348]
for example:
# dig +short 9.rarbg.me                  
151.80.120.115
151.80.120.114
151.80.120.112
151.80.120.113

the trackers_all_ip file contains only one IP.

**Comment by ngosang** [comment]
Yes, it is intentional. I only use one IP from each tracker to reduce the load on the servers.
