### ISSUE TITLE
New Open Tracker

### ISSUE THREAD

**Issue by babico** [ngosang/trackerslist#359]
udp://tracker.babico.name.tr:8000/announce
https://tracker.babico.name.tr/announce

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by babico** [comment]
Hi, I changed the links and add IPv6 here the links.

udp://tracker.4.babico.name.tr:3131/announce
https://tracker.4.babico.name.tr/announce
udp://tracker.6.babico.name.tr:6969/announce
https://tracker.6.babico.name.tr/announce

**Comment by babico** [comment]
@ngosang  Hi, I changed the links and add IPv6 here the links.

udp://tracker.4.babico.name.tr:3131/announce
https://tracker.4.babico.name.tr/announce
udp://tracker.6.babico.name.tr:6969/announce
https://tracker.6.babico.name.tr/announce

**Comment by ngosang** [comment]
Thank you! Added IPv4 trackers only.
IPv6 trackers are not supported yet => #72
