### ISSUE TITLE
My list tracker, I hope it helps you

### ISSUE THREAD

**Issue by 97carmine** [ngosang/trackerslist#36]
http://opentrackr.org/announce

http://tracker.trackerfix.com/announce

http://t.bitlove.org/announce

udp://tracker.coppersurfer.tk:1337/announce

http://tracker.calculate.ru:6969/announce

http://www.mvgroup.org:2710/announce

http://glotorrents.pw:6969/announce

http://bt1.archive.org:6969/announce

http://bt2.archive.org:6969/announce

http://atrack.pow7.com/announce

http://p4p.arenabg.ch:1337/announce

http://t1.pow7.com/announce

http://tracker.kicks-ass.net:80/announce

udp://tracker.mg64.net:2710/announce

http://open.kickasstracker.com:443/announce

udp://tracker.piratepublic.com:1337/announce

http://photodiode.mine.nu:6969/announce

http://open.touki.ru/announce.php

http://tracker.dunnsearch.org/announce.php

http://tracker.skyts.net:6969/announce

http://open.lolicon.eu:7777/announce

http://5.79.83.193:2710/announce

udp://168.235.67.63:6969/announce

udp://37.19.5.155:2710/announce

http://37.19.5.139:6969/announce

udp://5.79.83.193:6969/announce

http://125.227.35.196:6969/announce

udp://37.19.5.155:6881/announce

http://60.249.6.78:6969/announce

http://182.176.139.129:6969/announce

udp://37.19.5.155:2710/announce

http://87.248.186.252:8080/announce

udp://89.234.156.205:451/announce

udp://144.76.32.100:6969/announce

udp://77.73.64.251:80/announce

http://123.249.16.5:6961/announce

http://5.79.83.193:6881/announce

http://5.79.83.194:6969/announce

**Comment by ngosang** [comment]
Added:
* http://t.bitlove.org/announce
* http://tracker.calculate.ru:6969/announce
