### ISSUE TITLE
Remove multiple trackers

### ISSUE THREAD

**Issue by crimist** [ngosang/trackerslist#360]
Reworking my infrastructure, remove anything related to trakx ie `*trakx.*`

Thanks.

**Comment by ngosang** [comment]
Done. Thank you!

**Comment by crimist** [comment]
@ngosang 

`udp://u4.trakx.crim.ist:1337/announce`

Should be stable!

**Comment by zyyr365** [comment]
您好，您发给我的邮件已经收到，谢谢。

**Comment by ngosang** [comment]
Added! Thank you!
