### ISSUE TITLE
Leet tracker has a new tracker?

### ISSUE THREAD

**Issue by R2004GEO** [ngosang/trackerslist#373]
According to his site, there are 3 tracker:

udp://leet-tracker.moe:23861/announce
udp://leet-tracker.moe:36783/announce
udp://leet-tracker.moe:38151/announce

One runs Chihaya, one runs Aquatic and one runs Opentracker.

But, since all trackers are hosted on a Raspberry PI, I see this as an absolute waste of power.

**Comment by ngosang** [comment]
Thank you! I added all of them but I'm pretty sure there are going to collapse soon if they are not hosted in a proper infrastructure.
