### ISSUE TITLE
Malicious tracker: pow7.com

### ISSUE THREAD

**Issue by rlgo** [ngosang/trackerslist#374]
![image](https://user-images.githubusercontent.com/32289083/160049663-872b2e43-19dd-4fb4-b506-0f77a7ca8d70.png)
![image](https://user-images.githubusercontent.com/32289083/160055826-f8f8e1f7-e23c-43e4-a46d-b2e7a5ca18e7.png)

I have seen this tracker return the same amount of peers/seeds in different torrent

**Comment by Xarcotic** [comment]
While I don't agree that the tracker is malicious, I can confirm that it's returning non-correct values for seeds/peers/downloaded.

**Comment by R2004GEO** [comment]
![pow7](https://i.postimg.cc/PxDRwVSD/image.png)
Same here.

**Comment by kast1450** [comment]
This tracker is malicious, I agree. I recommend removing it from the list.

**Comment by rautamiekka** [comment]
Begs the Q: how long has it done all that by now ?

**Comment by CN-Cyber-Jacky** [comment]
Please remove pow7.com.

**Comment by NuclearCow** [comment]
just noticed it. had to remove the tracker from my huge list of torrents. please remove all pow7 related trackers

**Comment by Descear** [comment]
@Xarcotic, they are intentionally returning those values. Returning those incorrect values causes harm to the operation of my software. The tracker is intentionally causing harm, so, yes, it is malicious.

**Comment by ngosang** [comment]
Confirmed. Blacklisted from now.
