### ISSUE TITLE
New tracker

### ISSUE THREAD

**Issue by ieeyaY** [ngosang/trackerslist#376]
- From [36dm](https://www.36dm.club/)
  http://www.36dm.club:2710/announce
  http://tracker.36dm.club:2710/announce

- From [comicat](https://www.comicat.org/), [KissSub](https://kisssub.org/). Both of them have tracker list involving "open acgtracker" mentioned above. But I don't know if they are same.

**Comment by ngosang** [comment]
Sorry, those trackers are not working from here.
