### ISSUE TITLE
New tracker

### ISSUE THREAD

**Issue by andy539** [ngosang/trackerslist#382]
Pleace add new tracker: https://tracker.srv00.com:443/announce

**Comment by zyyr365** [comment]
您好，您发给我的邮件已经收到，谢谢。

**Comment by ngosang** [comment]
The tracker is not working. Maybe is something related to the HTTPS certificate.

**Comment by devillD** [comment]
@andy539
Use http instead
http://tracker.srv00.com:80/announce

**Comment by ngosang** [comment]
> http://tracker.srv00.com:80/announce

Added
