### ISSUE TITLE
New Tracker

### ISSUE THREAD

**Issue by SakuraChanNya** [ngosang/trackerslist#383]
This is my self-built server, which supports both IPv4 and IPv6 dual stacks.
https://tracker.logirl.moe:443/announce
udp://tracker.logirl.moe:17052/announce

**Comment by ngosang** [comment]
Added, thank you!

**Comment by SakuraChanNya** [comment]
> Added, thank you!

Thanks for the inclusion, but may I request to replace "https://tracker.logirl.moe/announce" with "http://tracker.logirl.moe:17052/announce"?  Because I noticed that there are a lot of torrents connected to me, causing tls to consume too much CPU resources, causing the tracker to not run stably.

**Comment by SakuraChanNya** [comment]
> 

The above change request is no longer needed, I purchased a new server and now it can run stably under https "https://tracker.logirl.moe/announce"
