### ISSUE TITLE
Blacklist Tracker Request

### ISSUE THREAD

**Issue by gfxlight55** [ngosang/trackerslist#384]
Please add the following trackers to the blacklist as they producing the following errors: 

https://tr.highstar.shop:443/announce - has been detected as suspicious
http://btracker.top:11451/announce - has been detected with suspicious activity
https://tr.fuckbitcoin.xyz:443/announce - has been detected as suspicious

**Comment by Legendary117** [comment]
Yes, please, my antivirus is going crazy.
 
https://imgur.com/a/bUa1ur7

**Comment by ngosang** [comment]
Are you sure about http://btracker.top:11451/announce ? 
What is the antivirus software?

**Comment by Legendary117** [comment]
I didn't see any hits with that one from Bitdefender, just the other two.

**Comment by gfxlight55** [comment]
I am indeed 100% sure about http://btracker.top:11451/announce . Below is a link to the screenshot of the capture showing it's being flagged.

Screenshot: https://imgbox.com/BzD2PY4y

**Comment by ngosang** [comment]
Those 3 trackers were blacklisted. Thank you for reporting.
