### ISSUE TITLE
[ADD] tracker.encrypted-data.xyz

### ISSUE THREAD

**Issue by encryptedxdata** [ngosang/trackerslist#389]
HTTP:
http://tracker.encrypted-data.xyz:1337/announce

UDP:
udp://tracker.encrypted-data.xyz:1337/announce

**Comment by ngosang** [comment]
Not working from here

**Comment by encryptedxdata** [comment]
Online :)
Sorry was on holiday..

**Comment by ngosang** [comment]
Is offline again. I think you don't have enough resources to keep with the huge traffic.

**Comment by encryptedxdata** [comment]
Online again

**Comment by ngosang** [comment]
Added. Thank you!
