### ISSUE TITLE
Gbitt.info up and running with new code

### ISSUE THREAD

**Issue by Power2All** [ngosang/trackerslist#393]
Hey,

Just want to let you know that the new tracker runs now on Gbitt.
Coded completely in RUST, with a HTTP/HTTPS and UDP protocol again, with IPv4 and IPv6 full stack support.
HTTP/HTTPS runs through CloudFlare (cause of the many socket connections), and UDP goes directly to the server IP, thus both protocols are accessible through 2 different connections.
Code is still actively in development, but a "final" version is running right now.
NewTrackOn.com shows both protocols accessible and working, and I will be monitoring it now for stability, and eventually release the source code to the public.

Just want to let you know :)

https://www.gbitt.info/

Trackers:
http://tracker.gbitt.info:80/announce
https://tracker.gbitt.info:443/announce
udp://tracker-udp.gbitt.info:80/announce

Kind regards,
Power2All

**Comment by ngosang** [comment]
>  Coded completely in RUST, with a HTTP/HTTPS and UDP protocol again, with IPv4 and IPv6 full stack support.

Nice.

I added the 3 trackers. They are not popular enough to be in the top list but they will if you keep it up!.

**Comment by Power2All** [comment]
Thanks !
I also released my tracker code as Torrust-Axum for people to use as well :)

**Comment by ngosang** [comment]
Could you post the link to the source code? Maybe someone else is interested too.

**Comment by Power2All** [comment]
> Could you post the link to the source code? Maybe someone else is interested too.

https://github.com/Power2All/torrust-axum
You can find the project here ;)
