### ISSUE TITLE
New UDP tracker

### ISSUE THREAD

**Issue by TheVoxcraft** [ngosang/trackerslist#396]
Hello,

I've setup a UDP tracker http://tracker.jonaslsa.com/
It is hosted **very** close to the NIX (Norwegian Internet eXchange)

Max capacity: ~90,000 requests per second

Link: udp://tracker.jonaslsa.com:6969/announce

Thanks for the great trackers!

**Comment by TheVoxcraft** [comment]
Capacity: ~100,000 requests per second

**Comment by ngosang** [comment]
Added. Thank you!

> Max capacity: ~90,000 requests per second

We will see :smile:

**Comment by Antorell** [comment]
@TheVoxcraft  your tracker udp://tracker.jonaslsa.com:6969/announce seem to have some issues with rtorrent/libtorrent

That's with the tracker in the list
![Capture](https://user-images.githubusercontent.com/25066224/190801217-d7117fbc-0f41-495a-945e-cd398b52b149.PNG)

And that's without
![Screenshot 2022-09-16 234921](https://user-images.githubusercontent.com/25066224/190801667-6d8a4cc6-1e22-4f83-98ae-e34cd6f7e9cf.png)

I also tried the tracker with qbittorrent, nothing weird happened and it showed the correct amount a peers/seeds.

**Comment by TheVoxcraft** [comment]
@Antorell Thank you for your issue submission.
It should now be resolved.
