### ISSUE TITLE
A few trackers to blacklist

### ISSUE THREAD

**Issue by KIPdeKIP** [ngosang/trackerslist#4]
Found these on a few torrents. Apparently they're not on any of these lists.
Also, how does the blacklist work exactly? Is it useful to report these?

<h2>Registered torrents only</h2>
<h3>bt.edwardk.info</h3>

    http://bt.edwardk.info:2710/announce
    
    http://bt.edwardk.info:4040/announce
    
    http://bt.edwardk.info:6969/announce

Duplicates?:
    
    http://bt2.edwardk.info:2710/announce
    
    http://bt2.edwardk.info:4040/announce
    
    http://bt2.edwardk.info:6969/announce

<h3>open.nyaatorrents.info</h3>

    http://open.nyaatorrents.info:6544/announce

**Comment by ngosang** [comment]
I added them to the blacklist.

> how does the blacklist work exactly?

Trackers included in the blacklist aren't included in the trackers lists published in this site.
> Is it useful to report these?

Yes.This may help to know why a tracker is not included in the lists.
