### ISSUE TITLE
Big list

### ISSUE THREAD

**Issue by Leproide** [ngosang/trackerslist#40]
https://raw.githubusercontent.com/Leproide/trackerslist/master/trackers_all.txt

**Comment by ngosang** [comment]
Most of the trackers are already included. In addition, you have many duplicates. Anyway I will check the list in the following days.

**Comment by Leproide** [comment]
Hi,
I removed duplicate with notepad++
If you see much tracker listening on one or multiple ports, for example:
http://inferno.demonoid.me:3389/announce
http://inferno.demonoid.me:3390/announce
http://inferno.demonoid.me:3391/announce
http://inferno.demonoid.me:3392/announce
http://inferno.demonoid.me:3393/announce
http://inferno.demonoid.me:3394/announce
http://inferno.demonoid.me:3395/announce
http://inferno.demonoid.me:3396/announce
http://inferno.demonoid.me:3397/announce
http://inferno.demonoid.me:3398/announce
http://inferno.demonoid.me:3399/announce
http://inferno.demonoid.me:3401/announce
http://inferno.demonoid.me:3402/announce
http://inferno.demonoid.me:3403/announce
http://inferno.demonoid.me:3404/announce
http://inferno.demonoid.me:3405/announce
http://inferno.demonoid.me:3406/announce
http://inferno.demonoid.me:3407/announce
http://inferno.demonoid.me:3408/announce
http://inferno.demonoid.me:3409/announce
http://inferno.demonoid.me:3410/announce
http://inferno.demonoid.me:3411/announce
http://inferno.demonoid.me:3412/announce
http://inferno.demonoid.me:3413/announce
http://inferno.demonoid.me:3414/announce
http://inferno.demonoid.me:3415/announce
http://inferno.demonoid.me:3416/announce
http://inferno.demonoid.me:3417/announce
http://inferno.demonoid.me:3418/announce
http://inferno.demonoid.me:3419/announce
http://inferno.demonoid.ph:3389/announce
http://inferno.demonoid.ph:3390/announce

In any case, thanks for the reply and have a nice day :)

**Comment by ngosang** [comment]
I added all working and not duplicated trackers. Thank you.
