### ISSUE TITLE
Tracker detected as suspicious

### ISSUE THREAD

**Issue by alluringmoon31** [ngosang/trackerslist#402]
There seems to be an issue with the following tracker: https://tracker.jiesen.life:8443/announce

BitDefender Total Security detection:

```
Suspicious web page detected
Feature: Online Threat Prevention

The webpage https://tracker.jiesen.life/ has been detected as suspicious. Although the page is not blocked, it is not recommended to continue browsing this page.
Accessed by: qbittorrent.exe
```

**Comment by ngosang** [comment]
What is your Antivirus software?

**Comment by alluringmoon31** [comment]
Oh I'm sorry, I was sure I put that information there 😅
It's BitDefender.

**Comment by ngosang** [comment]
I can not verify the issue. If other users report the same problem I will blacklist the tracker.

**Comment by Usernameistoolong** [comment]
>I will blacklist the tracker. 

Like the fake seeder trackers you won't blacklist?

https://github.com/ngosang/trackerslist/issues/343

**Comment by lslqtz** [comment]
Sometimes fake seeder is due to the implementation of software. If this phenomenon is not enough to affect use, then I don't think it is necessary to list the blacklist.

**Comment by ngosang** [comment]
> Like the fake seeder trackers you won't blacklist?

These lists are used by thousands of users around the world. One complain is not enough to blacklist a tracker.
Anyway, a tracker can not be dangerous by any means. The worst case is the tracker returns fake peers and that is already managed by Bittorrent clients. They only get a small number of peers from each tracker and they only try to connect to each peer once. The overhead of having 1 in 100 trackers returning fake seeds is negligible.

**Comment by ngosang** [comment]
I still think that tracker is not dangerous but I'm blacklisting anyway. There are much better trackers.
