### ISSUE TITLE
Add New Public Tracker

### ISSUE THREAD

**Issue by bifeldy** [ngosang/trackerslist#406]
🌏 Announce Tracker URL
http://tracker.fansub.id:80/announce
<s>udp://tracker.fansub.id:33333</s> (edit: udp unavailable due to cloudflare reverse proxy 'free' plan 😥)
ws://tracker.fansub.id:80

ℹ Stats
https://tracker.fansub.id/stats
https://tracker.fansub.id/stats.json

📍 Location
Jakarta, Indonesia 🇮🇩

⚡ Using
https://github.com/webtorrent/bittorrent-tracker

✔ Support IP v4 & v6

**Comment by ngosang** [comment]
Added. Thank you!
