### ISSUE TITLE
Adding my tracker to the list

### ISSUE THREAD

**Issue by sudaox2001** [ngosang/trackerslist#409]
Hello, I would like to add my BitTorrent tracker to the list. Latency should be pretty low and is hosted in Kentucky, USA

UDP: udp://ky.sudaox.com:1337
HTTP: http://ky.sudaox.com:1337/announce

**Comment by sudaox2001** [comment]
If needed, here are the trackers in IP form

UDP: udp://216.211.145.236:1337
HTTP: 216.211.145.236:1337/announce

**Comment by ngosang** [comment]
Not working from here.
