### ISSUE TITLE
some tracker(s)

### ISSUE THREAD

**Issue by Lypt** [ngosang/trackerslist#41]
http://agusiq-torrents.pl:6969/announce
udp://oscar.reyesleon.xyz:6969/announce
udp://tracker.swateam.org.uk:2710/announce
udp://thetracker.org:80/announce
udp://tracker.safe.moe:6969/announce
udp://allesanddro.de:1337/announce
udp://open.facedatabg.net:6969/announce
udp://tracker.cypherpunks.ru:6969/announce
udp://tr.cili001.com:6666/announce
http://tr.cili001.com:6666/announce
http://tracker.videodrugproject.com:80/announce
http://tracker.torrentyorg.pl:80/announce
http://tracker.devil-torrents.pl:80/announce
http://tracker.electro-torrent.pl:80/announce
http://tracker.tlm-project.org:6969/announce
http://retracker.telecom.by:80/announce
http://grifon.info:80/announce

**Comment by ngosang** [comment]
Added all but:
http://retracker.telecom.by:80/announce
http://grifon.info:80/announce
because they we already in the list
