### ISSUE TITLE
tracker with gigabit fiber ~25ms ping

### ISSUE THREAD

**Issue by tailz303** [ngosang/trackerslist#410]
http://www.peckservers.com:9000/announce

**Comment by tailz303** [comment]
This is a tracker I am hosting

IP form is http://97.117.78.100:9000/announce

**Comment by rautamiekka** [comment]
Usually the upload is much smaller than the download, though.

**Comment by tailz303** [comment]
I understand. Is gigabit upload enough to qualify for any of the lists? I
am currently seeding from my home data center at gigabit, but thought
hosting a tracker would also be a good use for that bandwidth. What all
would you like me to do to be best accommodating? Or is it just not
feasible? It's bidirectional gigabit if that helps clarify.

Thanks,
Cody

**Comment by tailz303** [comment]
Sorry, I mixed upload for download.

**Comment by ngosang** [comment]
Added. Thank you!
There aren't requirements to be listed but you will suffer a DDoS if you can't handle the requests.

**Comment by tailz303** [comment]
Awesome, thanks! Hopefully it's not too late but I've added udp support aswell. udp://www.peckservers.com:9000/announce
