### ISSUE TITLE
Downloading torrents only from private trackers only

### ISSUE THREAD

**Issue by katastrophe92** [ngosang/trackerslist#420]
Hello. I'm downloading torrents only from private trackers only, is it safe to add public trackers lists to qbit? Thanks

**Comment by zyyr365** [comment]
您好，您发给我的邮件已经收到，谢谢。

**Comment by ngosang** [comment]
Yes, it's safe.
qBittorrent and other Bittorrent clients like Deluge do not add public trackers into private torrents.

**Comment by katastrophe92** [comment]
> Yes, it's safe.
> qBittorrent and other Bittorrent clients like Deluge do not add public trackers into private torrents.

Should i bother then adding extra lists to qbit if i download only from private trackers?

**Comment by ngosang** [comment]
No

**Comment by katastrophe92** [comment]
@ngosang Thanks for the help
