### ISSUE TITLE
restfull api for trackerslist?

### ISSUE THREAD

**Issue by ghost** [ngosang/trackerslist#426]
Hi.

I wonder if you all have thought of developing a full API so that one or more people can access certain trackerslist torrent responses through http.  

*example 1*
`GET https://ngosang.github.io/trackerslist/year`

*example 1.1*
`GET https://ngosang.github.io/trackerslist/2023`

*example 1.2*
`GET https://ngosang.github.io/trackerslist/2023?format=json`

*example 1.3*
`GET https://ngosang.github.io/trackerslist/2023?format=xml`

*example 1.4*
`GET https://ngosang.github.io/trackerslist/2023?format=csv`

*example 1.5*
`GET https://ngosang.github.io/trackerslist/2023?format=txt`

*example 2*
`GET https://ngosang.github.io/trackerslist/blacklist`

*example 2.1*
`GET https://ngosang.github.io/trackerslist/blacklist/all`

*example 2.2*
`GET https://ngosang.github.io/trackerslist/blacklist/http`

*example 2.3*
`GET https://ngosang.github.io/trackerslist/blacklist/https`

*example 3*
`GET https://ngosang.github.io/trackerslist/all/https`

*example 4*
`GET https://ngosang.github.io/trackerslist/all/http`

*example 5*
`GET https://ngosang.github.io/trackerslist/all/http`

*example 6*
`GET https://ngosang.github.io/trackerslist/all/ip`

*example 7*
`GET https://ngosang.github.io/trackerslist/all/udp`

*example 8*
`GET https://ngosang.github.io/trackerslist/all/ws`

*example 9*
`GET https://ngosang.github.io/trackerslist/all/best`

*example 9.1*
`GET https://ngosang.github.io/trackerslist/all/best/ip`

*Have you all thought of developing a restfull API so that one or more people can access certain trackerlist-torrent  responses through http?*

**Comment by zyyr365** [comment]
您好，您发给我的邮件已经收到，谢谢。
