### ISSUE TITLE
Question: Is there is a way to add them automatically to qBittorrent?

### ISSUE THREAD

**Issue by GoldMath** [ngosang/trackerslist#43]
Hi,

qBittorrent have a function to automatically add trackers to new downloads via a box where you add urls.

Question: it's possible to use the following list to automatically add the 20 trackers to new downloads or it's still have to be done manual?
https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt

**Comment by ngosang** [comment]
Manual, but you can copy trackers_all list and forget about it.
