### ISSUE TITLE
Public Tracker

### ISSUE THREAD

**Issue by Anaphylaxis** [ngosang/trackerslist#435]
Has a :443 to help bypass censorship, UDP ports 6969/1337
```
udp://t.zerg.pw:6969
udp://t.zerg.pw:1337
https://t.zerg.pw/announce
```

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by Anaphylaxis** [comment]
@ngosang I saw the requests for IPv6, so I have configured this.
t.zerg.pw has an AAAA but if you want to add it to the IP list -> [2607:5300:203:ac02::1337]:1337
