### ISSUE TITLE
hash

### ISSUE THREAD

**Issue by li-dianzheng** [ngosang/trackerslist#436]
I want to use python to push the tracker server, but the prompt needs hash, how can I get the hash of the link

**Comment by ngosang** [comment]
I don't understand the question.

**Comment by renfei** [comment]
> I want to use python to push the tracker server, but the prompt needs hash, how can I get the hash of the link

嘿，@li-dianzheng 

BT 网络中，是通过 Hash 值来识别文件的，例如：```5dea4f2b157537c9c5ceeca7ebe63fe42e852674```

在磁力链中使用Hash：```magnet:?xt=urn:btih:5dea4f2b157537c9c5ceeca7ebe63fe42e852674&tr=http%3a%2f%2ftracker.renfei.net%3a8080%2fannounce```

在 Tracker 服务器中使用时：```http://tracker.renfei.net:8080/announce?info_hash=%5D%EAO%2B%15u7%C9%C5%CE%EC%A7%EB%E6%3F%E4.%85%26t&peer_id=-BC0198-e%5C9.%EA%B6%A1%9D5%EC5E&port=8082&natmapped=1&localip=192.168.199.162&port_type=lan&uploaded=0&downloaded=0&left=0&numwant=50&compact=1&no_peer_id=1&key=9565```

## info_hash

这个 info_hash 应该就是你说的 hash。

**Comment by TheK0tYaRa** [comment]
The hash is roughly the download link in torrents. The part that links to files. You find it yourself. It's in every magnet link.

**Comment by li-dianzheng** [comment]
yes，this is
&nbsp;


我爱你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianling ***@***.***&gt;; 
发送时间: 2023年4月20日(星期四) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ngosang/trackerslist] hash (Issue #436)





  
I want to use python to push the tracker server, but the prompt needs hash, how can I get the hash of the link
  
***@***.***
 
BT 网络中，是通过 Hash 值来识别文件的，例如：5dea4f2b157537c9c5ceeca7ebe63fe42e852674
 
在磁力链中使用Hash：magnet:?xt=urn:btih:5dea4f2b157537c9c5ceeca7ebe63fe42e852674&amp;tr=http%3a%2f%2ftracker.renfei.net%3a8080%2fannounce
 
在 Tracker 服务器中使用时：http://tracker.renfei.net:8080/announce?info_hash=%5D%EAO%2B%15u7%C9%C5%CE%EC%A7%EB%E6%3F%E4.%85%26t&amp;peer_id=-BC0198-e%5C9.%EA%B6%A1%9D5%EC5E&amp;port=8082&amp;natmapped=1&amp;localip=192.168.199.162&amp;port_type=lan&amp;uploaded=0&amp;downloaded=0&amp;left=0&amp;numwant=50&amp;compact=1&amp;no_peer_id=1&amp;key=9565
 
info_hash
 
这个 info_hash 应该就是你说的 hash。
