### ISSUE TITLE
Robot Confirmation

### ISSUE THREAD

**Issue by renfei** [ngosang/trackerslist#438]
Hi, there.

At ( 4:00 UTC / 12:00 CST ) every day, I will receive a large number of /scrape requests, and the instantaneous request volume is very large. I want to confirm whether it is a robot of this project?

IP List:

- 65.109.27.171
- 65.108.140.145
- 65.108.237.226

User-Agent: ```Typhoeus - https://github.com/typhoeus/typhoeus```

**Comment by ngosang** [comment]
Bot IP is 85.61.x.x (Spain)
I only make 3 requests per tracker / 24 hours to test different torrents
