### ISSUE TITLE
http://bt.okmp3.ru:2710/announce returns fake information

### ISSUE THREAD

**Issue by Rascal** [ngosang/trackerslist#439]
http://bt.okmp3.ru:2710/announce returns fake information, if there are no seeds, it always returns information that there is 1 seed

**Comment by renfei** [comment]
In mainland China, this Tracker cannot connect.

![image](https://user-images.githubusercontent.com/6532952/234159359-a425426b-242b-43f4-ada0-49280f005ee4.png)

**Comment by ngosang** [comment]
Added to blacklist. Thank you for reporting.
