### ISSUE TITLE
Changing my tracker URL

### ISSUE THREAD

**Issue by tailz303** [ngosang/trackerslist#440]
The traffic became too much for a single instance of opentracker so I had to put it behind a load balancer. This load balancer could not handle UDP traffic so I am an http tracker only. Is there any way to remove the http://www.peckservers.com:9000/announce and replace it with the dedicated "http://tracker.peckservers.com:9000/announce"? the www variant will still remain online for those who have it in their torrent software, but since newtrackon is only checking UDP on that url, it makes it look bad.

Thanks!

For those who are curious how its doing after the transition to a load balancer, Its a cluster of 8 instances and it peaked at almost 10,000 active connections, with 2,500 new connections being established a second. Pretty crazy and fun!

**Comment by zyyr365** [comment]
您好，您发给我的邮件已经收到，谢谢。

**Comment by tailz303** [comment]
> You can use [BEP34](https://www.bittorrent.org/beps/bep_0034.html) to delete your tracker from newTrackon, or change the port and protocol.

Thanks for the response! I have been poking around with configuration options but there doesn't seem to be a way to specify that it is an HTTP tracker, so now newtrackon is trying the https one which obviously didnt work. after converting the tracker to https, theres virtually no traffic because everyone has the http version hard coded. I would be fine with switching to https but there doesn't seem to be away of informing current users of the tracker that it has changed.

**Comment by renfei** [comment]
> > You can use [BEP34](https://www.bittorrent.org/beps/bep_0034.html) to delete your tracker from newTrackon, or change the port and protocol.
> 
> Thanks for the response! I have been poking around with configuration options but there doesn't seem to be a way to specify that it is an HTTP tracker, so now newtrackon is trying the https one which obviously didnt work. Are you aware of any ways to specify http explicitly because after converting the tracker to https, theres virtually no traffic since everyone has the http version hard coded. I would be fine with switching to https but there doesn't seem to be away of informing current users of the tracker that it has changed.

This is a bug of newTrackon, see: https://github.com/CorralPeltzer/newTrackon/issues/218

* Delete the tracker using the [BEP34](https://www.bittorrent.org/beps/bep_0034.html) protocol and resubmit.
* Deleted the TXT record in DNS.

**Comment by ngosang** [comment]
You tracker is down from here.

**Comment by tailz303** [comment]
Indeed, that's a development from about 6 hours ago. I'll take care of
getting it back online tomorrow.

**Comment by smiba** [comment]
> For those who are curious how its doing after the transition to a load balancer, Its a cluster of 8 instances and it peaked at almost 10,000 active connections, with 2,500 new connections being established a second. Pretty crazy and fun!

FYI, Opentracker should've been easily be able to handle this on a single instance, many trackers are handling >100k/connections per second on a single instance. You might be running into kernel limits where you'll either need to increase the sockets in /etc/limits or increase udp&tcp values in your kernel parameter configuration. 

Running strace on a worker process may show you what it's waiting on

(Also make sure you're using a somewhat recent version, in 2021 a bug was fixed where parallelism was being held back by mutex locks)

**Comment by Anaphylaxis** [comment]
running 1 instance of opentracker and have seen it hit over 700k torrents before it segfaults. i have it just restart when it has an error. hovers around 200k-400k now. 
if i had your issue i would find a udp load balancer such as traefik or looks like even nginx can do udp load balancing(?)
