### ISSUE TITLE
pfblocker format

### ISSUE THREAD

**Issue by iovcho** [ngosang/trackerslist#446]
Hello there. Can you make this lists for pfblocker format?
here example (this is for adult content websites, but its working perfectly for pfsense -> pfblocker):
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

Thanks!

**Comment by ngosang** [comment]
The objective of this project is to promote the use of the BitTorrent network. We will not provide blocking lists.
