### ISSUE TITLE
New trackers

### ISSUE THREAD

**Issue by AnAverageBeing** [ngosang/trackerslist#457]
tracker1: "udp://tracker.therarbg.com:6969/announce"
tracker2: "udp://tracker.t-rb.org:6969/announce"

these trackers are used by
our site - https://therarbg.com
our frnds site - https://mirrorbay.org/ and https://piratebay.pro/

**Comment by bulletproof2k** [comment]
Will you add them to the main list?

**Comment by AnAverageBeing** [comment]
thanks

**Comment by Satrier** [comment]
https://nnmclub.to/ > http://bt02.nnm-club.cc:2710
https://rutracker.org/ > http://bt4.t-ru.org/ann / http://retracker.local/announce

**Comment by volschin** [comment]
retracker.local? You made my day.

**Comment by Satrier** [comment]
it's in tracker files, I'm just copy paste

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by zappbrannigan34** [comment]
where is nnm club? not added
