### ISSUE TITLE
Add/update aria2 shell script link

### ISSUE THREAD

**Issue by HaleTom** [ngosang/trackerslist#462]
The currently linked shell script overwrites any existing config in `aria2.conf`, which is hardly ideal:
https://github.com/wuyuansushen/aria2c_TrackersList/blob/master/TLUpdate.sh#L69-L70

I wrote a script with the following improvements:
- Preserves existing user config
- Only changes the `bt-tracker=` line
- Respects the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
- Much shorter and cleaner

https://gist.github.com/HaleTom/fe873dc2f3c5bd14f7418efefc2b91a8

Please consider adding / updating with the above gist link.

**Comment by lyyJoker** [comment]
unsubscribe



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ngosang/trackerslist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月5日(星期六) 下午2:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ngosang/trackerslist] Add/update aria2 shell script link (Issue #462)





 
The currently linked shell script overwrites any existing config in aria2.conf, which is hardly ideal:
 https://github.com/wuyuansushen/aria2c_TrackersList/blob/master/TLUpdate.sh#L69-L70
 
I wrote a (IMHO much cleaner, simpler) script which preserves the existing user config, and only changes the bt-tracker= line:
 https://gist.github.com/HaleTom/fe873dc2f3c5bd14f7418efefc2b91a8
 
Please consider adding / updating with the above gist link.

**Comment by ngosang** [comment]
Added. Thank you!
