### ISSUE TITLE
How does the best ranking work?

### ISSUE THREAD

**Issue by ayyyiieneheuihues** [ngosang/trackerslist#463]
Hi, I know in an earlier issue #51 you mentioned that you don't want to make your bot open source due to ugly code. That's fine. However, can you give any insight as to how you determine what makes a tracker "best"? If you could let me know I'd appreciate it 👍.

**Comment by ngosang** [comment]
Sure.
1. I have 5 reference torrent files which I change from time to time. 2 popular torrents, DMCA torrent, really old torrent (few seeds), Fake torrent.
2. For each tracker I request peers for each torrent.
3. I measure the uptime, latency, number of seeds, number of peers, number of downloads, fake seeds, IP Country, Cloudflare...
4. I remove offline trackers. I remove private trackers. I remove duplicate trackers based on the domain, IP and number of seeds.
5. I rank the trackers based on 3) and build the lists.
