### ISSUE TITLE
How can I use in Synology NAS?

### ISSUE THREAD

**Issue by chuanxinwong** [ngosang/trackerslist#464]
Synology NAS needs to be imported .dlm file, but here is the txt file，I do not know what to do；
How do I change the format? 
Thanks!

**Comment by ngosang** [comment]
I have no idea.

**Comment by TheK0tYaRa** [comment]
Have you considered asking on the forum?
https://community.synology.com/enu/forum/1/post/119382

**Comment by TheK0tYaRa** [comment]
I personally suggest modifying every torrent file and magnet via shell script

**Comment by chuanxinwong** [comment]
Then I decided to install QbitTorrent in docker, Download station is not easy to use。
if I use the words to be impolite, it may be a translation problem。
Thank you again。
