### ISSUE TITLE
Bot not updating trackers

### ISSUE THREAD

**Issue by TavoOvalle** [ngosang/trackerslist#465]
Hi, first of all, thank you for your work, I use this website every day. 

In the last few days the bot has not updated the trackers, the last update was 4 days ago.

**Comment by ngosang** [comment]
The bot will be offline until 1st sept. Sorry for the inconvenience.
I'm doing some hardware updates and this has low priority.
The lists don't change very often so it won't be a problem.

**Comment by ngosang** [comment]
All is up and running!
