### ISSUE TITLE
Possible blacklist trackers (Bitdefender flagged)

### ISSUE THREAD

**Issue by dizzyMongoose** [ngosang/trackerslist#467]
My Bitdefender is constantly blocking the following tracker IPs for claimed phishing attempts:

107.189.31.134:6969/announce (tracker.qu.ax)
91.224.92.110:6969/announce (tracker.sheesh.rip)

**Comment by ngosang** [comment]
I scanned both trackers with VirusTotal and they are safe.
You could follow this guide => https://www.bitdefender.com/consumer/support/answer/1519/
