### ISSUE TITLE
New tracker

### ISSUE THREAD

**Issue by ed25519xyz** [ngosang/trackerslist#476]
udp://x.paranoid.agency:6969/announce
tcp://y.paranoid.agency:6969/announce
udp://z.paranoid.agency:6969/announce
tcp://x.paranoid.agency:6969/announce
udp://y.paranoid.agency:6969/announce
tcp://z.paranoid.agency:6969/announce

**Comment by ngosang** [comment]
Added these:
> http://x.paranoid.agency:6969/announce
udp://x.paranoid.agency:6969/announce

The others are blacklisted as duplicated. Thank you!

**Comment by ngosang** [comment]
It means that I don't want to have too many trackers operated by the same person on the list. I also don't want to have trackers in the list that return the same peers. For the Bittorrent ecosystem it is better to have few very large trackers operated by different people.
