### ISSUE TITLE
New HTTPS Tracker

### ISSUE THREAD

**Issue by WhitePr** [ngosang/trackerslist#488]
`https://tracker.gcrreen.xyz:443/announce`

Proxy using CloudFlare

**Comment by lirener** [comment]
我已经在我的Qbittorrent为您提交 建议你也向我 一样 复刻一份该项目 然后修改 并且拉去请求 让作者 一键更新！
（I've submitted it to you on my Qbittorrent and I suggest you do the same with me, make a copy of the project, then modify it, and pull it to request the author to update it with one click!）

![原神蓝发女点头抬头示意你懂我意思吧小老弟](https://github.com/ngosang/trackerslist/assets/19354130/1e490f7c-99a3-4d90-994a-91782086eb53)

**Comment by ngosang** [comment]
Added. Thank you!
