### ISSUE TITLE
New Tracker Server

### ISSUE THREAD

**Issue by lirener** [ngosang/trackerslist#489]
`New Tracker Server`
# support（支持）：ipv4 + ipv6

Server status query（服务器状态查询）：http://bt.rer.lol:2710/stats
~Example（例子）：http://bt.rer.lol:[port]/stats~

New Tracker List（新增服务器列表）：
```
wss://bt.rer.lol:233/announce

udp://bt.rer.lol:2710/announce
```
Bt_Tracker Project Address：
使用node安装bittorrent-tracker建立tracker服务器：https://github.com/webtorrent/bittorrent-tracker

Q&A and consultation（有任何问题欢迎联系我）：
https://www.tiktok.com/@rer_carry

![蓝发女给你打call加油](https://github.com/ngosang/trackerslist/assets/19354130/59103971-5a3f-4875-8d29-72a061e91962)

**Comment by ngosang** [comment]
Added. Thank you!
