### ISSUE TITLE
Different trackers between “Raw” and “Mirror” links of the same category.

### ISSUE THREAD

**Issue by NonVolatileHuman** [ngosang/trackerslist#499]
In the “trackers: best” list, the trackers in the “raw” link are different from those in the “mirror” link.

![image](https://github.com/ngosang/trackerslist/assets/75540320/e1c696d9-3eeb-4540-8b8e-00bf0fb11c52)

*Left: Raw, Right: Mirror 2

**Comment by renfei** [comment]
jsdelivr uses cloudflare's CDN service, the content is cached and is not real-time data.

![image](https://github.com/ngosang/trackerslist/assets/6532952/5b0bab92-6727-4e0d-9a99-75f0ee8fbfe6)

**Comment by NonVolatileHuman** [comment]
Understandable, will use the raw data from now on, thank you.
