### ISSUE TITLE
open public tracker

### ISSUE THREAD

**Issue by internet-scum** [ngosang/trackerslist#500]
```
http://r.l5.ca:6969/announce
udp://r.l5.ca:6969/announce
```

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by internet-scum** [comment]
this tracker was down for some time, but is now back and operating-- it's been indexed with 95+% uptime on newtrackon.com-- will it be re-indexed by this repo?

**Comment by ngosang** [comment]
Added. Thank you!
