### ISSUE TITLE
Hey boss, I recently captured some information（嘿 BOSS,最近我抓到一些信息情报）

### ISSUE THREAD

**Issue by lirener** [ngosang/trackerslist#501]
```
无法工作的重定向（Redirects that don't work）
http://openbittorrent.com/announce		->	http://tracker.openbittorrent.com/announce
https://tr.burnabyhighstar.com:443/announce	->	http://46.245.92.93:80/connect/de/
```

```
不必要的重定向[可能]（Unnecessary redirects [possibly]）
https://tracker1.ctix.cn:443/announce	->	http://tracker.opentrackr.org:1337/announce
https://tracker2.ctix.cn:443/announce	->	http://tracker.opentrackr.org:1337/announce
https://tracker1.520.jp:443/announce	->	http://tracker.opentrackr.org:1337/announce
```

```
修正重定向（Fix redirects）
http://tracker.enitin.xyz:80/announce	->	https://tracker.enitin.xyz/announce
https://1337.abcvg.info:443/announce	->	http://1337.abcvg.info/announce
```

```
被DNS污染（Polluted by DNS）
http://t.acg.rip:6699/announce
http://tracker.bt4g.com:2095/announce
https://tracker.cangku.moe:443/announce
```
![污染检测](https://github.com/ngosang/trackerslist/assets/19354130/364ca319-272c-476e-9919-80d35b31b0b2)
污染域名检测：https://www.htool.com/domain/pollutions.html

```
无法正确记录做种/用户IP（Seeding/user IPs cannot be recorded correctly）：
http://bvarf.tracker.sh:2086/announce（该节点你每请求1次就会多1次seeds）
https://trackers.mlsub.net/announce
https://trackers.mlsub.net:443/announce
http://run-2.publictracker.xyz:6969/announce
http://v6-tracker.0g.cx:6969/announce
http://p2p.0g.cx:6969/announce
https://www.peckservers.com:9443/announce
https://yolo.liberbear.com/announce
http://184.60.171.247:9000/announce
http://www.peckservers.com:9000/announce
http://free.publictracker.xyz:6969/announce
https://dev.tracker.cf-identity-wallet.metadata.dev.cf-deployments.org/announce
https://dev.tracker.cf-identity-wallet.metadata.dev.cf-deployments.org:443/announce
```
![错误引导IP](https://github.com/ngosang/trackerslist/assets/19354130/399bffa6-01d3-4784-8e67-0c745485f019)
![错误引导IP-2](https://github.com/ngosang/trackerslist/assets/19354130/f6ea9bd3-76a0-4d46-aba2-bf5adc39b211)
![无限新增错误IP](https://github.com/ngosang/trackerslist/assets/19354130/b7a50368-0ecf-4548-a6f7-f92e2fcbb824)

上面的这些trackr经过我的检测 无法正确记录做种用户的IP
（The trackrs above have been tested by me and cannot correctly record the IP of the seeding user.）

------------------------------------------------------

以上情报 来自我的工作站检测 检测地点中国cn
（The above information comes from my workstation testing location China CN）
```
tracker工作状态查询[cn]（Working status）：https://tracker.rer.lol/stats
tracker日志历史信息[cn]（Historical events）：https://tracker.rer.lol/eventlog
tracker问题提交反馈[cn]（Need Help）：https://tracker.rer.lol/help
```

**Comment by renfei** [comment]
This repo is open to the world, and DNS pollution only in `China` will not be considered a problem.

However, some Trackers do return a 301 Moved Permanently status.

Your monitoring tools are great !

这个仓库面向全世界，仅仅在`中国`受到 DNS污染 不会被认为是问题。

不过，有些 Tracker 确实返回 301 Moved Permanently 状态。

你的监控工具非常棒！

**Comment by lirener** [comment]
Thank Q Approbation（感谢认可）

![QQ截图20240117083642](https://github.com/ngosang/trackerslist/assets/19354130/9fa4bd1e-760c-44a6-af0e-8fcacc705f8d)

**Comment by ngosang** [comment]
I reviewed the redirects and they are already fixed.
About the DNS pollution I can't do anything. In the rest of the world they are working just fine. You can use a VPN or a secure DNS server.
