### ISSUE TITLE
UDP Tracker IPv4 + IPv6 mixed use probability error

### ISSUE THREAD

**Issue by lirener** [ngosang/trackerslist#504]
你好 boss！最近我捕捉到了一个概率性错误
hey boss! Recently I caught a probabilistic error

udp tracker ipv4+ipv6混合使用概率出错
UDP Tracker IPv4 + IPv6 mixed use probability error

Refer to the application error reason（应用错误原因参考）
look this：https://github.com/webtorrent/bittorrent-tracker/issues/508

所以我必须分开ipv4和ipv6 udp tracker 变更后tracker如下：
So I have to separate the IPv4 and IPv6 udp tracker after the change tracker is as follows：

```
udp://ipv4.rer.lol:2710/announce

udp://bt.rer.lol:6969/announce
```

**Comment by ngosang** [comment]
Added. Thank you!
