### ISSUE TITLE
Is your bot open source?

### ISSUE THREAD

**Issue by IA21** [ngosang/trackerslist#51]
If not, may I ask why?

**Comment by ngosang** [comment]
Not yet, ugly code.

**Comment by josch** [comment]
Would you consider publishing the source anyway?

The advantage would be, that it would not make you the single point of failure of this list anymore. Even if you for any reason cannot continue this project anymore (imagine github removes this list or whatnot) others could continue instead.

**Comment by ngosang** [comment]
I'm a person compromised with open-source principles and if in the future I don't have time for this project anymore I will release the full source code. By now, I don't want to see a lot outdated trackers lists in GitHub. Only 1 updated list.
