### ISSUE TITLE
 https://bt.ptlsp.com/announce

### ISSUE THREAD

**Issue by PTLSP** [ngosang/trackerslist#511]
https://bt.ptlsp.com/announce
https://trackers.ptlsp.com/announce

**Comment by lemaximedu66** [comment]
can confirm it works.

**Comment by PTLSP** [comment]
Can my trackers be added to trackerslist? I want more people to use my tracker servers

**Comment by lemaximedu66** [comment]
Option 1 : Wait
Option 2 : do a pull request

**Comment by ngosang** [comment]
Added. Thank you!
