### ISSUE TITLE
first line of trackers_all.txt

### ISSUE THREAD

**Issue by InappRepo** [ngosang/trackerslist#520]
The first line of trackers_all gave doesn't make the tracker lis accepted on Transmission. if removed all is fine

**Comment by rautamiekka** [comment]
Weird, do you have any error messages ?

**Comment by ngosang** [comment]
It's working fine with Transmission. In fact we have several external tools working too. => https://github.com/ngosang/trackerslist?tab=readme-ov-file#third-party-tools
