### ISSUE TITLE
FUNDING.yml

### ISSUE THREAD

**Issue by ghost** [ngosang/trackerslist#521]

**Comment by Capgajah221** [comment]
> Hi. please, allow the community to send donations to support an incredible project. ![image](https://private-user-images.githubusercontent.com/165694895/327294190-da1e37e1-fd86-441b-b6e1-7bf6a97371aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTM3ODQsIm5iZiI6MTcxNjIxMzQ4NCwicGF0aCI6Ii8xNjU2OTQ4OTUvMzI3Mjk0MTkwLWRhMWUzN2UxLWZkODYtNDQxYi1iNmUxLTdiZjZhOTczNzFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMzU4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDYzNTgxODIyYzVmZmIxM2M2MjU1ODlmN2VhN2ExZmNhODQ3ZTE0NGIyZjExYjc0NzYyOTA5MWVlM2UxODM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ir6KbAGKWVDYzFhjMjB7Z-XX9tQ7xrWklnA75a06Pck)

https://github.com/ngosang/trackerslist/issues/521#issue-2304775952

**Comment by ngosang** [comment]
You already have donation buttons here => https://github.com/ngosang/trackerslist?tab=readme-ov-file#ngosangtrackerslist
