### ISSUE TITLE
is there an userscript version?

### ISSUE THREAD

**Issue by BURGERxBOY** [ngosang/trackerslist#522]
this probably isn't the place to ask, but it's the best i found.
-- i've been searching around trying to find an userscript for just utilising the tracker list from here, globally, within the google chrome browser.

to keep things light-weight ( not heavy on RAM and / or CPU usage ), but still improve download speeds, even if only slightly.
-- which is what brings me to ask here, directly, to find out if there is such an userscript out there, or if it would be possible to create one.

that said, when it comes to coding, i have little to no knowledge there.

**Comment by ngosang** [comment]
It's not clear to me what you are trying to do. There aren't userscripts / extensions / addons for web browsers as far as I know. The known scripts are here => https://github.com/ngosang/trackerslist?tab=readme-ov-file#third-party-tools
