### ISSUE TITLE
Hello I am new here and I use aria2 as my p20 downloader. However it doesn't work when I copy the tracker list into my configuration file. The speed remains at 0. What should I do to debug?

### ISSUE THREAD

**Issue by ipyton** [ngosang/trackerslist#525]
How can I figure out if the resource is invalid or the tracker list does not work?

**Comment by P0bo** [comment]
for aria2 u need to separate trackers using commas , insted of line break.

**Comment by ngosang** [comment]
I can't give support for every BitTorrent client but some users already make customs scripts to import trackers from this repository into aria2. You can checkout them and if you have questions you can quote/reach the original authors.

* https://github.com/ngosang/trackerslist?tab=readme-ov-file#third-party-tools
