### ISSUE TITLE
tracker sug.

### ISSUE THREAD

**Issue by Allesanddro** [ngosang/trackerslist#53]
udp://sandrotracker.biz:1337/announce
http://sandrotracker.biz:1337/announce

backup links 

udp://sandrotorde.de:1337/announce
http://sandrotorde.de:1337/announce

and yes iknow same ip just in case if 1 off mine domains run out
stats site https://sandrotracker.biz/tracker/

**Comment by ngosang** [comment]
Added. Thank you!
