### ISSUE TITLE
Got a new tracker

### ISSUE THREAD

**Issue by lighting9999** [ngosang/trackerslist#532]
[trackerlist.txt](https://github.com/user-attachments/files/16814140/trackerlist.txt)
tracker 有重复，请进行合并。

**Comment by Radhikastar** [comment]
trackers_all.txt

**Comment by Radhikastar** [comment]
Marck

**Comment by Radhikastar** [comment]
Hello

**Comment by Radhikastar** [comment]
### **__**

**Comment by lighting9999** [comment]
请问能进行合并吗？

**Comment by ngosang** [comment]
You should post the tracker in plain text. They will be reviewed manually before being added to the lists.
