### ISSUE TITLE
Artix trackers are not public and will not work

### ISSUE THREAD

**Issue by CorySanin** [ngosang/trackerslist#540]
title. Please remove artixlinux.org trackers.

**Comment by ngosang** [comment]
Done. Thank you!

**Comment by CorySanin** [comment]
They have been added back. Please stop adding artix to this list and inform whatever source you're getting these from that Artix can't be used for arbitrary torrents. Unless the checksum matches one of our official ISOs, it won't work. All this is doing is causing grief for our team, making us deal with pointless DMCA notifications from stupid content protection agencies that know how to read a tracker list but are too stupid to check if they actually work.

**Comment by ngosang** [comment]
Sorry for the inconvenience. I just blacklisted `udp://torrents.artixlinux.org:6969/announce`
