### ISSUE TITLE
Covert these trackers to Pihole/domains

### ISSUE THREAD

**Issue by WoefulWrecker** [ngosang/trackerslist#545]
Is there any possible for the author to create a pi-hole / domain formats to be able to add to pi-hole and other dns blocking  or unblocking apps?

Thanks in advance.

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by rautamiekka** [comment]
> maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

Spam.

**Comment by ngosang** [comment]
I don't know about those format and what you are trying to archive.
Please, give technical information and examples.
