### ISSUE TITLE
New Tracker

### ISSUE THREAD

**Issue by 9bishi** [ngosang/trackerslist#551]
https://tr.zukizuki.org/announce

**Comment by ngosang** [comment]
Added. Thank you!

**Comment by lyyJoker** [comment]
unsubscribe,please.
When I clicked the unsubscribe button, it showed" Whoops! That unsubscribe link isn't valid for your account". Please help me unsubscribe, thank you!

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ngosang/trackerslist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月10日(星期天) 凌晨1:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ngosang/trackerslist] New Tracker (Issue #551)





 
Added. Thank you!
