### ISSUE TITLE
[addition] got few more. verified alive.

### ISSUE THREAD

**Issue by eladkarako** [ngosang/trackerslist#57]
<pre>
http://5.79.83.193:2710/announce

http://5.79.83.194:2710/announce

http://173.254.204.71:1096/announce

http://182.176.139.129:6969/announce

http://182.176.139.149:6969/announce

http://182.190.3.68:6969/announce

http://210.244.71.25:6969/announce

http://210.244.71.26:6969/announce

http://tracker1.wasabii.com.tw:6969/announce

http://tracker2.wasabii.com.tw:6969/announce

udp://9.rarbg.com:2710/announce

udp://9.rarbg.me:2710/announce

udp://9.rarbg.to:2710/announce

udp://62.138.0.158:6969/announce

udp://74.82.52.209:6969/announce

udp://87.98.148.74:1337/announce

udp://87.233.192.220:6969/announce

udp://151.80.120.112:2710/announce

udp://151.80.120.113:2710/announce

udp://151.80.120.114:2710/announce

udp://151.80.120.115:2710/announce

udp://163.172.81.35:1337/announce

udp://163.172.157.35:1337/announce

udp://182.176.139.129:80/announce

udp://182.176.139.129:2710/announce

udp://182.176.139.129:6969/announce

udp://182.190.3.68:6969/announce

udp://182.190.3.99:6969/announce

udp://182.190.4.52:6969/announce

udp://191.96.249.23:6969/announce

udp://212.47.227.58:6969/announce

udp://eddie4.nl:6969/announce

udp://explodie.org:6969/announce

udp://opentrackr.org:1337/announce

udp://p4p.arenabg.ch:1337/announce

udp://p4p.arenabg.com:1337/announce

udp://public.popcorn-tracker.org:6969/announce

udp://shadowshq.yi.org:6969/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://tracker.opentrackr.org:1337/announce

udp://tracker.pirateparty.gr:6969/announce

udp://tracker.zer0day.to:1337/announce

</pre>

list has:
explicit ports: helps for some router blocking + some websites maintain different trackers on different ports (will more ports)
IPs alternative to hostnames (helps with ISP hostname blocking trough DNS redirects)
and <code>/announce</code> variation.
<sub><em>source: <a href="http://icompile.eladkarako.com/trackers-utorrent-format/">icompile.eladkarako.com/trackers-utorrent-format/</a>. Credit is not required.</em></sub>

**Comment by ngosang** [comment]
all of them are already in the list. thank you!
