### ISSUE TITLE
Propose of adding new trackers to the list. #1

### ISSUE THREAD

**Issue by Misiek304** [ngosang/trackerslist#6]
Hi,

I was wondering if you could add those trackers to the check list. Also how long does a tracker needs to be down to get removed from the list?

udp://tracker.desu.sh:6969
http://bt4.rutracker.cc/ann?magnet
udp://bt2.54new.com:8080
udp://tracker.istole.it:80

**Comment by ngosang** [comment]
* udp://tracker.desu.sh:6969 => It's ok but it is very new, I'll wait a few days to see if it is still active.
* http://bt4.rutracker.cc/ann?magnet => Registered torrents
* udp://bt2.54new.com:8080 => Registered torrents
* udp://tracker.istole.it:80 => Not working

**Comment by Misiek304** [comment]
Thank you for looking into it.
