### ISSUE TITLE
tracker's list.

### ISSUE THREAD

**Issue by laptopsftw** [ngosang/trackerslist#60]
udp://tracker.leechers-paradise.org:6969

udp://zer0day.ch:1337

udp://open.demonii.com:1337

udp://tracker.coppersurfer.tk:6969

udp://exodus.desync.com:6969

udp://tracker4.piratux.com:6969/announce

http://85.17.19.180/announce

http://retracker.omsk.ru:2710/announce

http://bt.3dmgame.com:2710/announce

http://tracker.prq.to/announce

http://tracker.prq.to/announce.php

udp://tracker.opentrackr.org:1337/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.openbittorrent.com:80/announce

http://glotorrents.pw:80/announce

udp://tracker.pirateparty.gr:6969/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://9.rarbg.com:2730/announce

udp://p4p.arenabg.com:1337/announce

http://asnet.pw:2710/announce

udp://public.popcorn-tracker.org:6969/announce

udp://tracker.internetwarriors.net:1337/announce

udp://tracker1.wasabii.com.tw:6969/announce

udp://tracker.zer0day.to:1337/announce

http://mgtracker.org:6969/announce

udp://tracker.mg64.net:6969/announce

udp://peerfect.org:6969/announce

udp://open.facedatabg.net:6969/announce

udp://mgtracker.org:6969/announce

http://tracker.mg64.net:6881/announce

http://ipv4.tracker.harry.lu:80/announce

udp://ipv4.tracker.harry.lu:80/announce

http://retracker.telecom.by:80/announce

udp://tracker.tvunderground.org.ru:3218/announce

udp://tracker.swateam.org.uk:2710/announce

http://tracker1.wasabii.com.tw:6969/announce

http://tracker.torrentyorg.pl:80/announce

http://tracker.grepler.com:6969/announce

http://tracker.electro-torrent.pl:80/announce

http://tracker.devil-torrents.pl:80/announce

http://tracker.city9x.com:2710/announce

http://torrentsmd.me:8080/announce

http://t.nyaatracker.com:80/announce

http://retracker.mgts.by:80/announce

http://pt.lax.mx:80/announce

http://agusiq-torrents.pl:6969/announce

udp://zephir.monocul.us:6969/announce

udp://ulfbrueggemann.no-ip.org:6969/announce

udp://trackerxyz.tk:1337/announce

udp://tracker2.wasabii.com.tw:6969/announce

udp://tracker2.christianbro.pw:6969/announce

udp://tracker.xku.tv:6969/announce

udp://tracker.vanitycore.co:6969/announce

udp://tracker.torrent.eu.org:451/announce

udp://tracker.tiny-vps.com:6969/announce

udp://tracker.skyts.net:6969/announce

udp://tracker.safe.moe:6969/announce

udp://tracker.piratepublic.com:1337/announce

udp://tracker.kuroy.me:5944/announce

udp://tracker.kamigami.org:2710/announce

udp://tracker.halfchub.club:6969/announce

udp://tracker.grepler.com:6969/announce

udp://tracker.filetracker.pl:8089/announce

udp://tracker.files.fm:6969/announce

udp://tracker.edoardocolombo.eu:6969/announce

udp://tracker.doko.moe:6969/announce

udp://tracker.dler.org:6969/announce

udp://tracker.desu.sh:6969/announce

udp://tracker.cypherpunks.ru:6969/announce

udp://tracker.cyberia.is:6969/announce

udp://tracker.christianbro.pw:6969/announce

udp://tracker.bluefrog.pw:2710/announce

udp://tracker.acg.gg:2710/announce

udp://tr.cili001.com:6666/announce

udp://thetracker.org:80/announce

udp://retracker.lanta-net.ru:2710/announce

udp://packages.crunchbangplusplus.org:6969/announce

udp://oscar.reyesleon.xyz:6969/announce

udp://open.stealth.si:80/announce

udp://inferno.demonoid.pw:3418/announce

udp://explodie.org:6969/announce

udp://bt.xxx-tracker.com:2710/announce

udp://86.19.29.160:6969/announce

udp://208.67.16.113:8000/announce

https://tracker.bittor.xyz:443/announce

https://opentracker-milanesi.rhcloud.com:443/announce

http://tracker2.wasabii.com.tw:6969/announce

http://tracker.vanitycore.co:6969/announce

http://tracker.kuroy.me:5944/announce

http://tracker.filetracker.pl:8089/announce

http://sandrotracker.biz:1337/announce

http://open.acgtracker.com:1096/announce

http://grifon.info:80/announce

http://fxtt.ru:80/announce

udp://z.crazyhd.com:2710/announce

udp://tracker1.xku.tv:6969/announce

udp://tracker.justseed.it:1337/announce

udp://sandrotracker.biz:1337/announce

udp://allesanddro.de:1337/announce

http://tracker.videodrugproject.com:80/announce

http://tracker.tfile.me:80/announce

http://share.camoe.cn:8080/announce

http://182.176.139.129:6969/announce

http://91.218.230.81:6969/announce

http://5.79.83.193:2710/announce

udp://tracker.ilibr.org:80/announce

http://retracker.krs-ix.ru:80/announce

http://tracker.dutchtracking.com:80/announce

http://torrentsmd.com:8080/announce

udp://eddie4.nl:6969/announce

http://tracker.bittor.pw:80/announce

http://mgtracker.org:2710/announce

udp://tracker.eddie4.nl:6969/announce

http://t2.pow7.com/announce

udp://shadowshq.yi.org:6969/announce

http://www.wareztorrent.com:80/announce

http://open.touki.ru/announce.php

udp://tracker.sktorrent.net:6969

http://tracker2.itzmx.com:6961/announce

http://pow7.com:80/announce

http://atrack.pow7.com/announce

udp://tracker.mg64.net:2710/announce

http://tracker.ex.ua:80/announce

http://tracker.kicks-ass.net:80/announce

http://bt.henbt.com:2710/announce

udp://62.138.0.158:6969/announce

udp://tracker2.indowebster.com:6969/announce

http://tracker.dutchtracking.nl:80/announce

http://secure.pow7.com/announce

http://p4p.arenabg.ch:1337/announce

http://thetracker.org:80/announce

http://tracker.edoardocolombo.eu:6969/announce

http://t1.pow7.com/announce

udp://shadowshq.eddie4.nl:6969/announce

http://tracker.tfile.me/announce

http://tracker.dutchtracking.com/announce

udp://zer0day.ch:1337/announce
*udp://zer0day.to:1337/announce

udp://9.rarbg.me:2750/announce

udp://9.rarbg.to:2720/announce

udp://tracker.sktorrent.net:6969/announce

http://p4p.arenabg.com:1337/announce

udp://tracker.aletorrenty.pl:2710/announce

http://tracker.aletorrenty.pl:2710/announce

http://tracker.bittorrent.am/announce

udp://tracker.kicks-ass.net:80/announce

http://tracker.kicks-ass.net/announce

http://tracker.baravik.org:6970/announce

udp://torrent.gresille.org:80/announce

http://torrent.gresille.org/announce

http://tracker.skyts.net:6969/announce

http://tracker.internetwarriors.net:1337/announce

http://tracker.dutchtracking.nl/announce

udp://tracker.yoshi210.com:6969/announce

udp://mgtracker.org:2710/announce

http://tracker.yoshi210.com:6969/announce

http://tracker.tiny-vps.com:6969/announce

udp://tracker.ex.ua:80/announce

udp://91.218.230.81:6969/announce

https://www.wareztorrent.com/announce

http://www.wareztorrent.com/announce

http://tracker.ex.ua/announce

http://tracker.calculate.ru:6969/announce

udp://tracker.flashtorrents.org:6969/announce

http://tracker.tvunderground.org.ru:3218/announce

http://tracker.flashtorrents.org:6969/announce

http://retracker.gorcomnet.ru/announce

http://bt.pusacg.org:8080/announce

http://87.248.186.252:8080/announce

udp://182.176.139.129:6969/announce

http://retracker.krs-ix.ru/announce

http://tracker.dler.org:6969/announce

http://bt2.careland.com.cn:6969/announce

http://open.lolicon.eu:7777/announce

udp://213.163.67.56:1337/announce

http://213.163.67.56:1337/announce

udp://185.86.149.205:1337/announce

http://74.82.52.209:6969/announce

udp://94.23.183.33:6969/announce

udp://74.82.52.209:6969/announce

udp://151.80.120.114:2710/announce

udp://109.121.134.121:1337/announce

udp://168.235.67.63:6969/announce

http://109.121.134.121:1337/announce

udp://178.33.73.26:2710/announce

http://178.33.73.26:2710/announce

udp://85.17.19.180:80/announce

http://210.244.71.25:6969/announce

http://213.159.215.198:6970/announce

udp://191.101.229.236:1337/announce

http://178.175.143.27/announce

udp://89.234.156.205:80/announce

http://91.216.110.47/announce

http://114.55.113.60:6969/announce

http://195.123.209.37:1337/announce

udp://114.55.113.60:6969/announce

http://210.244.71.26:6969/announce

udp://107.150.14.110:6969/announce

udp://5.79.249.77:6969/announce

udp://195.123.209.37:1337/announce

udp://37.19.5.155:2710/announce

http://107.150.14.110:6969/announce

http://5.79.249.77:6969/announce

udp://185.5.97.139:8089/announce

udp://194.106.216.222:80/announce

https://104.28.17.69/announce

http://104.28.16.69/announce

http://185.5.97.139:8089/announce

http://194.106.216.222/announce

http://80.246.243.18:6969/announce

http://37.19.5.139:6969/announce

udp://5.79.83.193:6969/announce

udp://46.4.109.148:6969/announce

udp://51.254.244.161:6969/announce

udp://188.165.253.109:1337/announce

http://91.217.91.21:3218/announce

http://37.19.5.155:6881/announce

http://46.4.109.148:6969/announce

http://51.254.244.161:6969/announce

http://104.28.1.30:8080/announce

http://81.200.2.231/announce

http://157.7.202.64:8080/announce

udp://128.199.70.66:5944/announce

http://128.199.70.66:5944/announce

http://188.165.253.109:1337/announce

http://93.92.64.5/announce

http://173.254.204.71:1096/announce

udp://195.123.209.40:80/announce

udp://62.212.85.66:2710/announce

http://125.227.35.196:6969/announce

http://59.36.96.77:6969/announce

http://87.253.152.137/announce

http://158.69.146.212:7777/announce

udp://87.233.192.220:6969/announce

udp://151.80.120.113:2710/announce

udp://77.78.130.136:1337/announce

http://95.213.191.124:2710/announce

udp://191.96.249.23:6969/announce

http://163.172.157.35:1337/announce

udp://163.172.157.35:1337/announce

udp://185.82.217.160:1337/announce

udp://210.244.71.25:6969/announce

udp://87.98.148.74:1337/announce

http://5.79.83.193:6969/announce

udp://77.91.229.218:6969/announce

udp://62.210.110.127:6969/announce

udp://5.79.83.194:6969/announce

http://5.79.83.194:6881/announce

http://163.172.180.68:80/announce

udp://163.172.180.68:80/announce

http://213.184.225.53:80/announce

udp://91.217.91.21:3218/announce

udp://75.127.14.224:2710/announce

http://188.165.220.112:80/announce

http://164.132.200.122:80/announce

http://185.38.248.162:80/announce

http://64.78.163.242:2710/announce

http://103.3.63.11:80/announce

http://82.209.230.66:80/announce

http://107.174.238.55:80/announce

http://178.33.50.164:6969/announce

udp://212.47.227.58:6969/announce

udp://79.251.38.148:6969/announce

udp://82.45.40.204:1337/announce

udp://210.244.71.26:6969/announce

udp://5.226.21.164:6969/announce

udp://173.254.219.72:6969/announce

udp://163.172.140.46:6969/announce

udp://91.216.110.52:451/announce

udp://5.79.209.57:6969/announce

udp://211.149.236.45:6969/announce

udp://62.112.8.71:6969/announce

udp://192.99.81.115:1337/announce

udp://139.162.46.83:5944/announce

udp://37.187.123.8:2710/announce

udp://87.120.254.233:6969/announce

udp://91.121.174.197:8089/announce

udp://87.110.219.191:6969/announce

udp://51.254.141.22:6969/announce

udp://185.145.130.254:6969/announce

udp://125.227.35.196:6969/announce

udp://185.53.178.8:6969/announce

udp://77.51.181.209:6969/announce

udp://198.167.223.75:6969/announce

udp://178.32.221.207:6969/announce

udp://85.204.49.104:2710/announce

udp://68.64.165.106:2710/announce

udp://58.222.20.247:6666/announce

udp://176.31.253.219:80/announce

udp://193.203.61.5:2710/announce

udp://138.68.225.164:6969/announce

udp://158.69.92.213:6969/announce

udp://163.172.177.129:80/announce

udp://91.214.70.157:3418/announce

https://163.172.158.121:443/announce

https://52.87.197.238:443/announce

http://163.172.140.46:6969/announce

http://139.162.46.83:5944/announce

http://91.121.174.197:8089/announce

http://213.153.71.22:1337/announce

http://85.12.225.4:80/announce

http://195.88.220.21:80/announce

udp://167.114.97.225:2710/announce

udp://45.77.11.89:6969/announce

udp://94.23.217.90:1337/announce

udp://213.153.71.22:1337/announce

http://149.202.60.146:80/announce

http://188.126.79.87:80/announce

http://198.251.81.243:8080/announce

http://85.28.1.169:2710/announce

udp://p4p.arenabg.ch:1337

udp://p4p.arenabg.com:1337

http://bttracker.crunchbanglinux.org:6969/announce

udp://tracker.trackerfix.com:85/announce

udp://www.eddie4.nl:6969/announce

http://retracker.kld.ru:2710/announce

http://bt.careland.com.cn:6969/announce

http://tracker.best-torrents.net:6969/announce

http://tracker.torrenty.org:6969/announce

http://tracker.btzoo.eu:80/announce

http://pow7.com/announce

http://tracker.novalayer.org:6969/announce

http://193.107.16.156:2710/announce

http://cpleft.com:2710/announce

udp://retracker.hotplug.ru:2710/announce

http://retracker.kld.ru/announce

http://inferno.demonoid.me:3414/announce

http://announce.torrentsmd.com:6969/announce

udp://coppersurfer.tk:6969/announce

udp://exodus.desync.com:6969/announce

udp://open.demonii.com:1337/announce

udp://tracker.prq.to/announce

http://exodus.desync.com/announce

http://ipv4.tracker.harry.lu/announce

http://tracker.torrentbay.to:6969/announce

udp://11.rarbg.com/announce

udp://tracker.1337x.org:80/announce

udp://tracker.istole.it:80/announce

udp://tracker.ccc.de:80/announce

udp://fr33dom.h33t.com:3310/announce

udp://tracker.publicbt.com:80/announce

udp://tracker.ilibr.org:6969/announce

udp://tracker.istole.it:80

udp://tracker.istole.it:6969

udp://tracker.openbittorrent.com:80

udp://tracker.prq.to:80/announce

udp://tracker.prq.to:6969/announce

udp://tracker.publicbt.com:80

udp://tracker.yify-torrents.com/announce

udp://tracker.yify-torrents.com:80/announce

udp://tracker.yify-torrents.com:6969/announce

udp://tracker.yts.re/announce

http://bovetorrents.hol.es/announce.php

http://blackcat.filers.ru:1337/announce

http://tracker.coppersurfer.tk:6969/announce

udp://tracker.opentrackr.org:1337

http://www.mvgroup.org:2710/announce

udp://tracker.glotorrents.com:6969/announce

udp://tracker.dutchtracking.com:6969/announce

udp://tc.animereactor.ru:8082/announce

udp://retracker.nts.su:2710/announce

udp://wambo.club:1337/announce

udp://tracker4.itzmx.com:2710/announce

udp://santost12.xyz:6969/announce

udp://bt.aoeex.com:8000/announce

https://tracker.bt-hash.com:443/announce

udp://glotorrents.pw:6969/announce

udp://tracker.trackerfix.com:80/announce

http://9.rarbg.com:2710/announce

http://explodie.org:6969/announce

udp://9.rarbg.me:2710/announce

udp://tracker.btzoo.eu:80/announce

http://retracker.hotplug.ru:2710/announce

udp://9.rarbg.com:2710/announce

http://tracker.trackerfix.com/announce

udp://9.rarbg.to:2710/announce

udp://11.rarbg.com:6969/announce

udp://11.rarbg.com:80/announce

udp://11.rarbg.me:6969/announce

udp://11.rarbg.me:80/announce

udp://11.rarbg.to:6969/announce

udp://11.rarbg.to:80/announce

udp://208.67.16.113:8000/annonuce

udp://berylliumsurfer.tk:6969/announce

udp://bismuthsurfer.tk:6969/announce

udp://galliumsurfer.tk:6969/announce

udp://germaniumsurfer.tk:6969/announce

udp://glotorrents.com:6969/announce

udp://indiumsurfer.tk:6969/announce

udp://ironsurfer.tk:6969/announce

udp://p4p.arenabg.ch:1337/announc

udp://p4p.arenabg.ch:1337/announce

udp://poloniumsurfer.tk:6969/announce

udp://pubt.net:2710/announce

udp://rhodiumsurfer.tk:6969/announce

udp://tinsurfer.tk:6969/announce

udp://tracker.bittor.pw:1337

udp://tracker.blackunicorn.xyz:6969/announce

udp://tracker.coppersurfer.tk:1337/announce

udp://tracker.openbittorrent.com:6969/announce

udp://tracker.pomf.se:80/announce

udp://tracker.pubt.net:2710/announce

udp://tracker.tricitytorrents.com:2710/announce

http://149.5.241.17:6969/announce

http://210.244.71.11:6969/announce

http://atrack.moviesndroids.com/announce

http://bt.rutracker.cc/ann

http://bt2.rutracker.cc/ann

http://bt3.rutracker.cc/ann

http://bt4.rutracker.cc/ann

http://bt4.rutracker.cc/ann?magnet

http://glotorrents.com:6969/announce

http://glotorrents.pw:6969/announce

http://retracker.2kom.ru/announce

http://t.bitlove.org/announce

http://thetracker.org/announce

http://torrent.gresille.org:80/announce

http://tracker.bittor.pw:1337/announce

http://tracker.glotorrents.com:6969/announce

http://tracker.opentrackr.org:1337/announce

http://tracker.tricitytorrents.com:2710/announce

http://ulfbrueggemann.no-ip.org:6969/announce

udp://castradio.net:6969/announce

http://castradio.net:6969/announce

http://coppersurfer.tk:6969/announce

udp://open.demonii.com:6969/announce

http://open.demonii.com:1337/announce

http://open.demonii.com:6969/announce

udp://exodus.desync.com:80/announce

udp://tracker.leechers-paradise.org:80/announce

http://tracker.leechers-paradise.org:80/announce

http://tracker.leechers-paradise.org:6969/announce

http://tracker.openbittorrent.com:80/announce

http://tracker.openbittorrent.com:6969/announce

udp://tracker.publicbt.com:6969/announce

http://tracker.publicbt.com:80/announce

http://tracker.publicbt.com:6969/announce

udp://tracker.x4w.co:6969/announce

http://tracker.x4w.co:6969/announce

http://tracker.sktorrent.net:6969/announce

udp://tracker.baravik.org:6970/announce

http://bt.artvid.ru:6969/announce

udp://tracker.sith.su:80/announce

udp://tracker.cuntflaps.me:6969/announce

http://retracker.gorcomnet.ru:80/announce

http://tracker.skyts.cn:6969/announce

udp://inferno.demonoid.ooo:3389/announce

udp://91.216.110.47:80/announce

http://81.169.145.151/announce

http://37.19.5.155:6969/announce

http://77.91.229.218:6881/announce

http://104.28.17.69/announce

http://76.73.76.244:6961/announce

http://open.nyaatorrents.info:6544/announce

**Comment by ngosang** [comment]
Added http://torrent.nwps.ws:6969/announce Thank you.
Please, next time take some time to clean the list.
