### ISSUE TITLE
Unlisted anime trackers

### ISSUE THREAD

**Issue by akiraaisha** [ngosang/trackerslist#65]
http://nyaa.tracker.wf:7777/announce
http://tracker.minglong.org:8080/announce
http://open.touki.ru/announce.php

**Comment by lirener** [comment]
relay(接力棒)
http://tracker.btsync.cf:233/announce
http://tracker.btsync.ga:80/announce
http://tracker.btsync.tk:443/announce
http://tracker.btsync.buzz:233/announce

**Comment by ngosang** [comment]
These trackers are in the blacklist because only work with torrents registered in their websites. Try to add these trackers to torrents downloaded from other sites.
```
http://nyaa.tracker.wf:7777/announce
http://tracker.minglong.org:8080/announce
http://open.touki.ru/announce.php
```

Added
```
http://tracker.btsync.cf:2710/announce
http://tracker.btsync.tk:443/announce
```

I'm working in ws support.

**Comment by ngosang** [comment]
Implemented WS/WSS support.

**Comment by lirener** [comment]
I don't know how to test the tracker WSS support
HTTP and UDP should work at present
（我不知道如何测试那些tracker的WSS支持）
（目前http和UDP应该能用）

**Comment by lirener** [comment]
tracker.btsync.cf => tracker.btsync.gq

**Comment by ngosang** [comment]
```
tracker.btsync.cf => tracker.btsync.gq
```
Changed. Thank you.
