### ISSUE TITLE
Why both http and udp on trackers_best

### ISSUE THREAD

**Issue by Misiek304** [ngosang/trackerslist#7]
I was wondering why your trackers_best list is showing both http and udp links to the same trackers. Isn't it a bad practise to have a multiple addresses pointing to the same tracker?

Also another question how to you check tracker popularity? I would like to read more about how the trackers are being chosen for trackers_best list.

**Comment by ngosang** [comment]
> I was wondering why your trackers_best list is showing both http and udp links to the same trackers. Isn't it a bad practise to have a multiple addresses pointing to the same tracker?

It's a bad practice but there are more important issues... e.g. many users are having problems with UDP trackers. My recommendation is to use the **UDP trackers list** if you don't have problems with UDP trackers.

> Also another question how to you check tracker popularity? I would like to read more about how the trackers are being chosen for trackers_best list.

There are several criteria. My bot query the trackers with popular torrents and checks which trackers are returning more seeds/peers, latency, reliability, offline time...

**Comment by Misiek304** [comment]
How many tracker do you recommend using with a single torrent/magnet? Your trackers_best list is holding 20! I read that using many trackers with DHT enabled is pretty useless and puts more stress on the trackers. Do you agree?

**Comment by ngosang** [comment]
> How many tracker do you recommend using with a single torrent/magnet? Your trackers_best list is holding 20! I read that using many trackers with DHT enabled is pretty useless and puts more stress on the trackers. Do you agree?

Depend on the number of seeds and peers. For popular TV shows with 1 or 2 working trackers is enough. For almost dead torrents you should add as much as possible to increase your chances of finding peers.

I usually add the UDP trackers list to all my torrents.

**Comment by Misiek304** [comment]
To summarize you are recommending adding the whole UDP trackers list to all of my torrents? There is 28 trackers on that list right now. That's a lot.

**Comment by ngosang** [comment]
> To summarize you are recommending adding the whole UDP trackers list to all of my torrents?

Yes
