### ISSUE TITLE
Open anime trackers

### ISSUE THREAD

**Issue by agentrfr** [ngosang/trackerslist#70]
http://bt.beatrice-raws.org/announce

http://nyaa.tracker.wf:7777/announce

**Comment by agentrfr** [comment]
Uh I just tried nyaa.tracker.wf and it sometimes allows unlisted torrents to be announced and sometimes doesnt... odd.

From #65 http://nyaa.tracker.wf:7777/announce was mentioned as on blacklist but does not appear there??

**Comment by ngosang** [comment]
Both added to blacklist. Thank you.
