### ISSUE TITLE
AcgnX Torrent Public Tracker Server

### ISSUE THREAD

**Issue by Lypt** [ngosang/trackerslist#71]
http://open.acgnxtracker.com/announce
https://open.acgnxtracker.com/announce

You can see more about Project AcgnX Torrent Public Tracker Server in here: https://www.acgnxtracker.com/

**Comment by Lypt** [comment]
udp://104.238.198.186:8000/announce
http://104.238.198.186:8000/announce

http://77.106.108.90:2710/announce

**Comment by ngosang** [comment]
```
http://open.acgnxtracker.com/announce
https://open.acgnxtracker.com/announce
udp://104.238.198.186:8000/announce
http://104.238.198.186:8000/announce
```
Added. Thank you.
