### ISSUE TITLE
Hidden Foreign Whitespace Characters

### ISSUE THREAD

**Issue by Alkaris** [ngosang/trackerslist#76]
When I ran the updater script to get the new tracker list to import into Transmission, it complains that some of the URL's are malformed because they contain some hidden whitespace character, which I cannot seem to identify since it doesn't seem to show in text editors for some reason, because it's treated as an invisible whitespace character.

![shutter__2018-22-03-12-18__06_03_02_pm](https://user-images.githubusercontent.com/6682988/37271331-62ff4f76-2622-11e8-87db-f671cdfe980e.png)

it looks to be like it's a tab or newline whitespace character, or acts like one, but when it's put into a text editor it doesn't show up as one.

**Comment by kevinvanrijn** [comment]
[Notepad++ has the ability to show end of line characters.](https://stackoverflow.com/questions/1446370/text-editor-which-shows-r-n)

As for what's causing this I have no idea. Looking at [trackers_all.txt](https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt) the files saved to this repo use Unix line endings. 'LF' (000A)

Maybe your application expects DOS line endings? 'LF + CR' (000A, 000D) [Or something else insane?](https://en.wikipedia.org/wiki/Newline#Representations_in_different_character_encoding_specifications)

For DOS line endings an application like [unix2dos](https://en.wikipedia.org/wiki/Unix2dos) would be able to convert the files on the fly.

**Comment by kevinvanrijn** [comment]
By "what's causing this" I mean the underlying cause. Also, thinking about this for one more second, could Transmission be trying to interpret the whole file as a single tracker?

**Comment by Alkaris** [comment]
My text editors by default use UNIX LF compatibility, Xed, Kate, Nano, and Sublime Text 3. I'm not entirely sure if Transmission is interpreting a copy+paste from the text file as one single tracker, because when I paste it in, it copies as it's shown in the text file.

![shutter__2018-38-03-12-18__08_03_32_pm](https://user-images.githubusercontent.com/6682988/37277707-7387b154-2635-11e8-9b7c-206d8279a7b0.png)

**Comment by Alkaris** [comment]
OK so I tried testing with other tracker lists the `trackers_best.txt` and I had no issue copy+pasting directly from that file into Transmission. Just seems to be something wrong with the file for `trackers_all.txt` for some odd reason, which I'm not too entirely sure why, and a fresh pull from the github repo was done.

**Comment by kevinvanrijn** [comment]
Both files have Unix line endings (on my end at least).

The only difference that leaves us with is the amount of trackers. Does Transmission have a limit on how many trackers a single torrent can have / a limit on how much trackers can be imported at once?

(Unless its a specific tracker that Transmission is tripping over somehow someway. But that can't reasonably be it.)

**Comment by Alkaris** [comment]
I believe Transmission allows you to add as many trackers as you want, since adding more trackers gives you more peers, and more peers means faster download rate from those peers you're connected to that are seeding. So I don't think it's hitting a cap limit on the number of trackers.

it could quite possibly be one or more of the trackers in the list that's causing it to think there's a malformed URL in the list.

**Comment by oilervoss** [comment]
The [script](https://github.com/oilervoss/transmission) I wrote uses the trackers_best_ip.txt file. As a fail-safe option, it uses a string URL list in-script. I couldn't find any wild character. 

@Alkaris : The URL tracker.city9x.com on your attached picture isn't in my script neither in @ngosang IP file.

**Comment by Alkaris** [comment]
@oilervoss it's definitely there, cuz I deleted the file and redownloaded and it's still there in the file.
