### ISSUE TITLE
New Trackers

### ISSUE THREAD

**Issue by SPDurkee** [ngosang/trackerslist#77]
udp://exodus.desync.com:6969

udp://open.demonii.com:1337

udp://tracker.leechers-paradise.org:6969

http://tracker.trackerfix.com:80/announce

udp://eddie4.nl:6969/announce

udp://tracker.pirateparty.gr:6969/announce

**Comment by francisuk1989** [comment]
Duplicate IP address that used by other Domains

**Comment by ngosang** [comment]
All these trackers are already in the list.
