### ISSUE TITLE
Why should there be `127.0.0.1` in trackers ip list?

### ISSUE THREAD

**Issue by Cabbagec** [ngosang/trackerslist#81]
**Updated 2018-04-13 00:00:03**
`trackers_best_ip (20 trackers)`:
```
...
udp://123.249.16.65:2710/announce
udp://127.0.0.1:6969/announce
udp://210.244.71.25:6969/announce
...
```
There are also two `127.0.0.1` addresses on that day's `trackers_all_ip (90 trackers)` list.

**Comment by aurora-potter** [comment]
@Cabbagec In casess when there's a local BitTorrent tracker server on a system.
The most likely address for such a server is udp://127.0.0.1:6969/announce

- If there's such a server on a system, it may run on a different protocol or port and it can even be binded to another IP adddress, and after all, it may not have any data available for a requested torrent.

It may not be of much usefulness, but it's certainly of no harm.

**Comment by aurora-potter** [comment]
@Cabbagec In cases where there's a local BitTorrent tracker server on a system.
The most likely address for such a server is udp://127.0.0.1:6969/announce

If there's such a server on a system, it may run on a different protocol or port and it can even be binded to another IP adddress, and after all, it may not have any data available for a requested torrent.
It may not be of much usefulness, but it's certainly of no harm.

**Comment by ngosang** [comment]
The DNS domain of the tracker "christianbro.pw" is pointing to 127.0.0.1. It's bad configured so I'm removing from the list.
Anyway, this is not a security issue because your bittorrent client will try to connect to your own computer.
