### ISSUE TITLE
运行多年的公共tracker

### ISSUE THREAD

**Issue by 1265578519** [ngosang/trackerslist#83]
http://bbs.itzmx.com/thread-4-1-1.html

http://tracker1.itzmx.com:8080/announce

http://tracker2.itzmx.com:6961/announce

http://tracker3.itzmx.com:6961/announce

http://tracker4.itzmx.com:2710/announce

udp://tracker1.itzmx.com:8080/announce

udp://tracker2.itzmx.com:6961/announce

udp://tracker3.itzmx.com:6961/announce

udp://tracker4.itzmx.com:2710/announce

**Comment by Z4HD** [comment]
发Pull Request，请

**Comment by ngosang** [comment]
```
http://tracker2.itzmx.com:6961/announce
http://tracker4.itzmx.com:2710/announce
udp://tracker4.itzmx.com:2710/announce
```
Are in the list already. The other trackers have the same IP, so they are replicas. Thank you anyway.
