### ISSUE TITLE
[Request] Import From Other Tracker Lists

### ISSUE THREAD

**Issue by zero77** [ngosang/trackerslist#85]
There seem to be lots of good lists on git hub and pastbin that are updated regularly, it may be worth scraping them.
Thanks

**Comment by SPDurkee** [comment]
Can you suggest some of those lists here, so the developer doesn't have to go looking for them?

**Comment by zero77** [comment]
@SPDurkee 
Sorry for the very late response.

Of hand I cannot recommend any good lists other than newTrackon, which I think is already used.

Generally, there seams to be lots of new lists of different sizes popping up on github and pastbin, from time to time.

Additionally, you could try scraping torrent sites, to find the latest trackers but, specifically for the newly uploaded torrents and then under the trackers part of each torrent.

**Comment by ngosang** [comment]
Sorry but I'm closing this. I always try to grab the best trackers from other lists but in this issue there aren't any.

**Comment by zero77** [comment]
@ngosang 
Have you considered scraping torrent sites, to find the latest trackers being used but, specifically for the newly uploaded torrents.

But under the trackers part of each torrent, where the trackers that are being used for that torrent are showed.
