### ISSUE TITLE
udp://open.demonii.si:1337/announce

### ISSUE THREAD

**Issue by Ibitzy** [ngosang/trackerslist#86]
udp://open.demonii.si:1337/announce

**Comment by Theli93** [comment]
That one isn't working for me.

Demonii went offline in [2015](https://torrentfreak.com/demonii-torrent-tracker-shuts-down-for-good-151116/), so it is typically thought of as [unsafe](https://www.reddit.com/r/trackers/comments/45ucce/is_demonii_safe/).

**Comment by ngosang** [comment]
As @Theli93 said, not working from here neither.
