### ISSUE TITLE
offline2

### ISSUE THREAD

**Issue by exekutive** [ngosang/trackerslist#91]
these trackers from the "best ip" list are offline in Canada

udp://103.224.212.222:6969/announce
udp://111.6.78.96:6969/announce
udp://123.249.16.65:2710/announce
udp://173.254.219.72:6969/announce
udp://210.244.71.25:6969/announce
udp://35.187.36.248:1337/announce
udp://54.36.163.162:1337/announce
udp://69.94.136.151:6969/announce
udp://78.142.19.42:1337/announce
udp://90.179.64.91:1337/announce

**Comment by ngosang** [comment]
The server is located in Europe so, it's possible... Sorry, I can't help you.

**Comment by exekutive** [comment]
How about a "North America compatible" list?
