### ISSUE TITLE
icon for trackerslist.

### ISSUE THREAD

**Issue by somratking420** [ngosang/trackerslist#92]
Hi @ngosang  , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by SoapDev2018** [comment]
Hello there @somratking420, not sure how this project needs a logo and icon

**Comment by somratking420** [comment]
ok sir

**Comment by somratking420** [comment]
Let me know when the logo pleased  tell.

**Comment by SDMU** [comment]
Close this please
