### ISSUE TITLE
add some public trackers

### ISSUE THREAD

**Issue by petesimon** [ngosang/trackerslist#96]
hello sir. i use a "seedever" seedbox in europe, and i populate my trackers list using your trackers and these other trackers too.

udp://tracker.pirateparty.gr:6969/announce - source website http://tracker.pirateparty.gr
udp://tracker.open-internet.nl:6969/announce - source website http://open-internet.nl/ (was eddie4.nl)

**Comment by petesimon** [comment]
![2018-07-27 09_35_05-tracker pirateparty gr](https://user-images.githubusercontent.com/2879849/43298896-49f8ab14-9182-11e8-91ee-1fd1e951cb94.jpg)
![2018-07-27 09_49_18-open-internet bittorrent tracker](https://user-images.githubusercontent.com/2879849/43298912-5d32f27a-9182-11e8-9e5b-dca362b07c59.jpg)

screenshots

**Comment by ngosang** [comment]
Added, thank you.

**Comment by ngosang** [comment]
Btw, udp://tracker.pirateparty.gr:6969/announce is a proxy for udp://tracker.coppersurfer.tk:6969/announce
