### ISSUE TITLE
new tracker http://tr.bangumi.moe:6969/announce

### ISSUE THREAD

**Issue by LiZhenhuan1019** [ngosang/trackerslist#98]
source website: https://bangumi.moe/help

tracker: 

https://tr.bangumi.moe:9696/announce

http://tr.bangumi.moe:6969/announce

udp://tr.bangumi.moe:6969/announce

**Comment by ngosang** [comment]
I get the message "Requested download is not authorized to use with this tracker". Looks like a private tracker.
